# Generated for MPSqre Build360 Phase 29.

import decimal
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("cost_center_code", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orgops_departments", to="tenant.company")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="orgops_departments", to="tenant.location")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="orgops.department")),
            ],
            options={"db_table": "orgops_department"},
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("level_code", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orgops_designations", to="tenant.company")),
            ],
            options={"db_table": "orgops_designation"},
        ),
        migrations.CreateModel(
            name="WorkCalendar",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("timezone", models.CharField(max_length=64)),
                ("working_days", models.JSONField(default=list)),
                ("standard_hours_per_day", models.DecimalField(decimal_places=2, default=decimal.Decimal("8.00"), max_digits=4)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orgops_work_calendars", to="tenant.company")),
            ],
            options={"db_table": "orgops_work_calendar"},
        ),
        migrations.CreateModel(
            name="EmployeeOrganizationProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employment_type_code", models.CharField(default="FULL_TIME", max_length=100)),
                ("worker_category_code", models.CharField(blank=True, max_length=100)),
                ("mobile", models.CharField(blank=True, max_length=32)),
                ("emergency_contact", models.JSONField(blank=True, default=dict)),
                ("status_code", models.CharField(default="ACTIVE", max_length=100)),
                ("probation_end", models.DateField(blank=True, null=True)),
                ("confirmation_date", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orgops_employee_profiles", to="tenant.company")),
                ("department", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="employee_profiles", to="orgops.department")),
                ("designation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="employee_profiles", to="orgops.designation")),
                ("employee", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="organization_profile", to="employee.employee")),
                ("work_calendar", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="employee_profiles", to="orgops.workcalendar")),
            ],
            options={"db_table": "orgops_employee_profile"},
        ),
        migrations.CreateModel(
            name="OrganizationAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assignment_type_code", models.CharField(default="PRIMARY", max_length=100)),
                ("project_code", models.CharField(blank=True, max_length=100)),
                ("site_code", models.CharField(blank=True, max_length=100)),
                ("work_package_code", models.CharField(blank=True, max_length=100)),
                ("allocation_percent", models.DecimalField(decimal_places=2, default=decimal.Decimal("100.00"), max_digits=5)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orgops_assignments", to="tenant.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="organization_assignments", to="employee.employee")),
                ("location", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="orgops_assignments", to="tenant.location")),
            ],
            options={"db_table": "orgops_assignment"},
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                ("unit_code", models.CharField(default="DAYS", max_length=50)),
                ("requires_approval", models.BooleanField(default=True)),
                ("is_paid", models.BooleanField(default=True)),
                ("annual_entitlement", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orgops_leave_types", to="tenant.company")),
            ],
            options={"db_table": "orgops_leave_type"},
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                ("reason", models.TextField(blank=True)),
                ("status_code", models.CharField(default="SUBMITTED", max_length=100)),
                ("requested_by_public_id", models.UUIDField()),
                ("reviewed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orgops_leave_requests", to="tenant.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="organization_leave_requests", to="employee.employee")),
                ("leave_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="orgops.leavetype")),
            ],
            options={"db_table": "orgops_leave_request"},
        ),
        migrations.CreateModel(
            name="AttendanceEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("work_date", models.DateField()),
                ("status_code", models.CharField(default="PRESENT", max_length=100)),
                ("hours_worked", models.DecimalField(decimal_places=2, default=decimal.Decimal("0.00"), max_digits=5)),
                ("source_code", models.CharField(default="MANUAL", max_length=100)),
                ("check_in_at", models.DateTimeField(blank=True, null=True)),
                ("check_out_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("recorded_by_public_id", models.UUIDField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orgops_attendance_entries", to="tenant.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="organization_attendance_entries", to="employee.employee")),
            ],
            options={"db_table": "orgops_attendance_entry"},
        ),
        migrations.CreateModel(
            name="PeopleImportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_name", models.CharField(max_length=250)),
                ("status_code", models.CharField(default="PROCESSING", max_length=100)),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("success_rows", models.PositiveIntegerField(default=0)),
                ("failed_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.JSONField(default=list)),
                ("created_by_public_id", models.UUIDField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orgops_import_jobs", to="tenant.company")),
            ],
            options={"db_table": "orgops_import_job"},
        ),
        migrations.AddConstraint(model_name="department", constraint=models.UniqueConstraint(fields=("company", "code"), name="orgops_dept_code_uq")),
        migrations.AddConstraint(model_name="department", constraint=models.CheckConstraint(condition=~models.Q(("id", models.F("parent_id"))), name="orgops_dept_no_self_ck")),
        migrations.AddIndex(model_name="department", index=models.Index(fields=["company", "is_active", "name"], name="orgops_dept_active_idx")),
        migrations.AddConstraint(model_name="designation", constraint=models.UniqueConstraint(fields=("company", "code"), name="orgops_desig_code_uq")),
        migrations.AddIndex(model_name="designation", index=models.Index(fields=["company", "is_active", "name"], name="orgops_desig_active_idx")),
        migrations.AddConstraint(model_name="workcalendar", constraint=models.UniqueConstraint(fields=("company", "code"), name="orgops_calendar_code_uq")),
        migrations.AddConstraint(model_name="workcalendar", constraint=models.CheckConstraint(condition=models.Q(("standard_hours_per_day__gt", 0), ("standard_hours_per_day__lte", 24)), name="orgops_calendar_hours_ck")),
        migrations.AddIndex(model_name="workcalendar", index=models.Index(fields=["company", "is_active", "name"], name="orgops_calendar_active_idx")),
        migrations.AddIndex(model_name="employeeorganizationprofile", index=models.Index(fields=["company", "department", "status_code"], name="orgops_profile_dept_idx")),
        migrations.AddIndex(model_name="employeeorganizationprofile", index=models.Index(fields=["company", "designation", "status_code"], name="orgops_profile_desig_idx")),
        migrations.AddConstraint(model_name="organizationassignment", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gte", models.F("effective_from")), _connector="OR"), name="orgops_assign_range_ck")),
        migrations.AddConstraint(model_name="organizationassignment", constraint=models.CheckConstraint(condition=models.Q(("allocation_percent__gt", 0), ("allocation_percent__lte", 100)), name="orgops_assign_alloc_ck")),
        migrations.AddIndex(model_name="organizationassignment", index=models.Index(fields=["company", "employee", "effective_from"], name="orgops_assign_employee_idx")),
        migrations.AddIndex(model_name="organizationassignment", index=models.Index(fields=["company", "project_code", "site_code"], name="orgops_assign_scope_idx")),
        migrations.AddConstraint(model_name="leavetype", constraint=models.UniqueConstraint(fields=("company", "code"), name="orgops_leave_type_code_uq")),
        migrations.AddConstraint(model_name="leavetype", constraint=models.CheckConstraint(condition=models.Q(("annual_entitlement__isnull", True), ("annual_entitlement__gte", 0), _connector="OR"), name="orgops_leave_entitle_ck")),
        migrations.AddIndex(model_name="leavetype", index=models.Index(fields=["company", "is_active", "name"], name="orgops_leave_type_active_idx")),
        migrations.AddConstraint(model_name="leaverequest", constraint=models.CheckConstraint(condition=models.Q(("end_date__gte", models.F("start_date"))), name="orgops_leave_range_ck")),
        migrations.AddConstraint(model_name="leaverequest", constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="orgops_leave_qty_ck")),
        migrations.AddIndex(model_name="leaverequest", index=models.Index(fields=["company", "status_code", "start_date"], name="orgops_leave_state_idx")),
        migrations.AddIndex(model_name="leaverequest", index=models.Index(fields=["company", "employee", "start_date"], name="orgops_leave_employee_idx")),
        migrations.AddConstraint(model_name="attendanceentry", constraint=models.UniqueConstraint(fields=("company", "employee", "work_date"), name="orgops_attendance_day_uq")),
        migrations.AddConstraint(model_name="attendanceentry", constraint=models.CheckConstraint(condition=models.Q(("hours_worked__gte", 0), ("hours_worked__lte", 24)), name="orgops_attendance_hours_ck")),
        migrations.AddConstraint(model_name="attendanceentry", constraint=models.CheckConstraint(condition=models.Q(("check_out_at__isnull", True), ("check_in_at__isnull", True), ("check_out_at__gte", models.F("check_in_at")), _connector="OR"), name="orgops_attendance_time_ck")),
        migrations.AddIndex(model_name="attendanceentry", index=models.Index(fields=["company", "work_date", "status_code"], name="orgops_attendance_daily_idx")),
        migrations.AddIndex(model_name="peopleimportjob", index=models.Index(fields=["company", "status_code", "created_at"], name="orgops_import_job_state_idx")),
    ]
