from django.urls import path

from modules.integration.api.views import (
    ApiClientListCreateView,
    ApiClientRevokeView,
    ApiClientRotateView,
    ConnectorHealthView,
    ConnectorListCreateView,
    ConnectorStatusView,
    ExchangeRateListCreateView,
    IntegrationProviderCatalogView,
    IntegrationSummaryView,
    LocalizationPackListCreateView,
    LocalizationPublishView,
    MappingListCreateView,
    MappingPublishView,
    MetaLeadConnectorListCreateView,
    MetaLeadConnectorStatusView,
    MetaLeadConnectorTestView,
    MetaLeadReceiptRetryView,
    MetaLeadVerifyTokenRotateView,
    MetaLeadWebhookView,
    SyncRunCompleteView,
    SyncRunListCreateView,
    WebhookListCreateView,
    WebhookSimulationView,
    WebhookStatusView,
)

urlpatterns = [
    path("summary", IntegrationSummaryView.as_view()),
    path("provider-catalog", IntegrationProviderCatalogView.as_view()),
    path("localization-packs", LocalizationPackListCreateView.as_view()),
    path("localization-packs/<uuid:public_id>/publish", LocalizationPublishView.as_view()),
    path("exchange-rates", ExchangeRateListCreateView.as_view()),
    path("connectors", ConnectorListCreateView.as_view()),
    path("connectors/<uuid:public_id>/health", ConnectorHealthView.as_view()),
    path("connectors/<uuid:public_id>/status", ConnectorStatusView.as_view()),
    path("api-clients", ApiClientListCreateView.as_view()),
    path("api-clients/<uuid:public_id>/rotate", ApiClientRotateView.as_view()),
    path("api-clients/<uuid:public_id>/revoke", ApiClientRevokeView.as_view()),
    path("webhooks", WebhookListCreateView.as_view()),
    path("webhooks/<uuid:public_id>/simulate", WebhookSimulationView.as_view()),
    path("webhooks/<uuid:public_id>/status", WebhookStatusView.as_view()),
    path("mappings", MappingListCreateView.as_view()),
    path("meta-leads", MetaLeadConnectorListCreateView.as_view()),
    path("meta-leads/<uuid:public_id>/status", MetaLeadConnectorStatusView.as_view()),
    path("meta-leads/<uuid:public_id>/test", MetaLeadConnectorTestView.as_view()),
    path("meta-leads/<uuid:public_id>/rotate-verify-token", MetaLeadVerifyTokenRotateView.as_view()),
    path("meta-leads/receipts/<uuid:public_id>/retry", MetaLeadReceiptRetryView.as_view()),
    path("meta-leads/webhook/<uuid:public_id>", MetaLeadWebhookView.as_view()),
    path("mappings/<uuid:public_id>/publish", MappingPublishView.as_view()),
    path("sync-runs", SyncRunListCreateView.as_view()),
    path("sync-runs/<uuid:public_id>/complete", SyncRunCompleteView.as_view()),
]
