# Generated for MPSqre Build360 Phase 20.

import decimal
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee", "0001_initial"),
        ("projects", "0001_initial"),
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=180)),
                ("cost_code", models.CharField(blank=True, max_length=80)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=20)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("manager_employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="managed_departments", to="employee.employee")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="peopleops.department")),
            ],
            options={"db_table": "peopleops_department", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="LeavePolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=180)),
                ("leave_type", models.CharField(choices=[("annual", "Annual leave"), ("sick", "Sick leave"), ("casual", "Casual leave"), ("parental", "Parental leave"), ("unpaid", "Unpaid leave")], max_length=20)),
                ("annual_days", models.DecimalField(decimal_places=2, max_digits=6)),
                ("carry_forward_days", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=6)),
                ("requires_approval", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "peopleops_leave_policy", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("currency", models.CharField(max_length=3)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("locked", "Locked"), ("approved", "Approved"), ("posted", "Posted"), ("cancelled", "Cancelled")], default="draft", max_length=20)),
                ("gross_total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("deduction_total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("net_total", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("created_by_user_public_id", models.UUIDField()),
                ("approved_by_user_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("evidence_sha256", models.CharField(blank=True, max_length=64)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "peopleops_payroll_run", "ordering": ["-period_end", "code"]},
        ),
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_start", models.DateField()),
                ("total_hours", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=7)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted"), ("approved", "Approved"), ("rejected", "Rejected")], default="draft", max_length=20)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.CharField(blank=True, max_length=1000)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("approver_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="timesheet_decisions", to="tenant.membership")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="timesheets", to="employee.employee")),
            ],
            options={"db_table": "peopleops_timesheet", "ordering": ["-week_start", "employee_id"]},
        ),
        migrations.CreateModel(
            name="EmploymentContract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_number", models.CharField(max_length=80)),
                ("position_title", models.CharField(max_length=180)),
                ("employment_type", models.CharField(choices=[("permanent", "Permanent"), ("fixed_term", "Fixed term"), ("consultant", "Consultant"), ("intern", "Intern")], max_length=20)),
                ("start_on", models.DateField()),
                ("end_on", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("annual_compensation", models.DecimalField(decimal_places=2, max_digits=18)),
                ("pay_frequency", models.CharField(choices=[("monthly", "Monthly"), ("biweekly", "Biweekly"), ("weekly", "Weekly")], max_length=20)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("ended", "Ended"), ("cancelled", "Cancelled")], default="draft", max_length=20)),
                ("created_by_user_public_id", models.UUIDField()),
                ("approved_by_user_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("department", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="employment_contracts", to="peopleops.department")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="employment_contracts", to="employee.employee")),
            ],
            options={"db_table": "peopleops_contract", "ordering": ["-start_on", "contract_number"]},
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_year", models.PositiveSmallIntegerField()),
                ("opening_days", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=7)),
                ("accrued_days", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=7)),
                ("taken_days", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=7)),
                ("adjustment_days", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=7)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leave_balances", to="employee.employee")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="balances", to="peopleops.leavepolicy")),
            ],
            options={"db_table": "peopleops_leave_balance"},
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("start_on", models.DateField()),
                ("end_on", models.DateField()),
                ("requested_days", models.DecimalField(decimal_places=2, max_digits=6)),
                ("reason", models.CharField(blank=True, max_length=1000)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("submitted", "Submitted"), ("approved", "Approved"), ("rejected", "Rejected"), ("cancelled", "Cancelled")], default="draft", max_length=20)),
                ("requester_user_public_id", models.UUIDField()),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.CharField(blank=True, max_length=1000)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("approver_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="leave_decisions", to="tenant.membership")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leave_requests", to="employee.employee")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="peopleops.leavepolicy")),
            ],
            options={"db_table": "peopleops_leave_request", "ordering": ["-start_on", "-created_at"]},
        ),
        migrations.CreateModel(
            name="TimesheetLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("work_date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("project", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="people_timesheet_lines", to="projects.project")),
                ("timesheet", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lines", to="peopleops.timesheet")),
            ],
            options={"db_table": "peopleops_timesheet_line"},
        ),
        migrations.CreateModel(
            name="PayrollEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("deduction_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=18)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("components", models.JSONField(default=dict)),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_entries", to="employee.employee")),
                ("payroll_run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="entries", to="peopleops.payrollrun")),
            ],
            options={"db_table": "peopleops_payroll_entry"},
        ),
        migrations.AddConstraint(model_name="department", constraint=models.UniqueConstraint(fields=("company", "code"), name="ppl_dept_code_uq")),
        migrations.AddIndex(model_name="department", index=models.Index(fields=["company", "status"], name="ppl_dept_status_idx")),
        migrations.AddConstraint(model_name="leavepolicy", constraint=models.UniqueConstraint(fields=("company", "code"), name="ppl_leave_policy_uq")),
        migrations.AddConstraint(model_name="leavepolicy", constraint=models.CheckConstraint(condition=models.Q(("annual_days__gte", 0)), name="ppl_leave_days_ck")),
        migrations.AddConstraint(model_name="leavepolicy", constraint=models.CheckConstraint(condition=models.Q(("carry_forward_days__gte", 0)), name="ppl_leave_carry_ck")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.UniqueConstraint(fields=("company", "code"), name="ppl_payroll_code_uq")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=models.Q(("period_end__gte", models.F("period_start"))), name="ppl_payroll_dates_ck")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=models.Q(("gross_total__gte", 0)), name="ppl_payroll_gross_ck")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=models.Q(("deduction_total__gte", 0)), name="ppl_payroll_deduct_ck")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=models.Q(("net_total__gte", 0)), name="ppl_payroll_net_ck")),
        migrations.AddIndex(model_name="payrollrun", index=models.Index(fields=["company", "status", "period_end"], name="ppl_payroll_status_idx")),
        migrations.AddConstraint(model_name="timesheet", constraint=models.UniqueConstraint(fields=("company", "employee", "week_start"), name="ppl_timesheet_week_uq")),
        migrations.AddConstraint(model_name="timesheet", constraint=models.CheckConstraint(condition=models.Q(("total_hours__gte", 0)), name="ppl_timesheet_hours_ck")),
        migrations.AddIndex(model_name="timesheet", index=models.Index(fields=["company", "status", "week_start"], name="ppl_timesheet_status_idx")),
        migrations.AddConstraint(model_name="employmentcontract", constraint=models.UniqueConstraint(fields=("company", "contract_number"), name="ppl_contract_number_uq")),
        migrations.AddConstraint(model_name="employmentcontract", constraint=models.CheckConstraint(condition=models.Q(("end_on__isnull", True), ("end_on__gte", models.F("start_on")), _connector="OR"), name="ppl_contract_dates_ck")),
        migrations.AddConstraint(model_name="employmentcontract", constraint=models.CheckConstraint(condition=models.Q(("annual_compensation__gte", 0)), name="ppl_contract_pay_ck")),
        migrations.AddIndex(model_name="employmentcontract", index=models.Index(fields=["company", "status", "start_on"], name="ppl_contract_status_idx")),
        migrations.AddConstraint(model_name="leavebalance", constraint=models.UniqueConstraint(fields=("company", "employee", "policy", "period_year"), name="ppl_leave_balance_uq")),
        migrations.AddConstraint(model_name="leavebalance", constraint=models.CheckConstraint(condition=models.Q(("taken_days__gte", 0)), name="ppl_leave_taken_ck")),
        migrations.AddIndex(model_name="leavebalance", index=models.Index(fields=["company", "employee", "period_year"], name="ppl_leave_balance_idx")),
        migrations.AddConstraint(model_name="leaverequest", constraint=models.CheckConstraint(condition=models.Q(("end_on__gte", models.F("start_on"))), name="ppl_leave_dates_ck")),
        migrations.AddConstraint(model_name="leaverequest", constraint=models.CheckConstraint(condition=models.Q(("requested_days__gt", 0)), name="ppl_leave_request_days_ck")),
        migrations.AddIndex(model_name="leaverequest", index=models.Index(fields=["company", "status", "start_on"], name="ppl_leave_request_idx")),
        migrations.AddConstraint(model_name="timesheetline", constraint=models.CheckConstraint(condition=models.Q(("hours__gt", 0), ("hours__lte", 24)), name="ppl_time_line_hours_ck")),
        migrations.AddIndex(model_name="timesheetline", index=models.Index(fields=["company", "work_date"], name="ppl_time_line_date_idx")),
        migrations.AddConstraint(model_name="payrollentry", constraint=models.UniqueConstraint(fields=("company", "payroll_run", "employee"), name="ppl_payroll_entry_uq")),
        migrations.AddConstraint(model_name="payrollentry", constraint=models.CheckConstraint(condition=models.Q(("gross_amount__gte", 0)), name="ppl_entry_gross_ck")),
        migrations.AddConstraint(model_name="payrollentry", constraint=models.CheckConstraint(condition=models.Q(("deduction_amount__gte", 0)), name="ppl_entry_deduct_ck")),
        migrations.AddConstraint(model_name="payrollentry", constraint=models.CheckConstraint(condition=models.Q(("net_amount__gte", 0)), name="ppl_entry_net_ck")),
    ]
