# Generated for MPSqre Build360 Phase 17.
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="ComplianceFramework",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("framework_type", models.CharField(choices=[("internal", "Internal baseline"), ("iso_27001", "ISO 27001 aligned"), ("privacy", "Privacy readiness"), ("customer", "Customer assurance"), ("regulatory", "Regulatory readiness")], max_length=24)),
                ("jurisdiction", models.CharField(blank=True, max_length=100)),
                ("version_label", models.CharField(max_length=60)),
                ("description", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("retired", "Retired")], default="draft", max_length=20)),
                ("effective_from", models.DateField(blank=True, null=True)),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("certification_claim", models.BooleanField(default=False)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "compliance_framework",
                "ordering": ["code", "version_label"],
                "indexes": [models.Index(fields=["company", "framework_type", "status"], name="cmp_framework_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code", "version_label"), name="cmp_framework_ver_uq"),
                    models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), models.Q(("effective_from__isnull", False), ("effective_to__gt", models.F("effective_from"))), _connector="OR"), name="cmp_framework_dates_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceControl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("domain", models.CharField(choices=[("governance", "Governance"), ("access", "Access control"), ("data", "Data protection"), ("secure_delivery", "Secure delivery"), ("operations", "Security operations"), ("incident", "Incident response"), ("continuity", "Business continuity"), ("third_party", "Third-party risk"), ("privacy", "Privacy")], max_length=24)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], max_length=16)),
                ("evidence_frequency_days", models.PositiveSmallIntegerField(default=90)),
                ("status", models.CharField(choices=[("active", "Active"), ("retired", "Retired")], default="active", max_length=16)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("framework", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="controls", to="compliance.complianceframework")),
                ("owner_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="owned_compliance_controls", to="tenant.membership")),
            ],
            options={
                "db_table": "compliance_control",
                "ordering": ["framework", "code"],
                "indexes": [models.Index(fields=["company", "domain", "status"], name="cmp_control_domain_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("framework", "code"), name="cmp_control_code_uq"),
                    models.CheckConstraint(condition=models.Q(("evidence_frequency_days__gte", 1), ("evidence_frequency_days__lte", 3650)), name="cmp_control_frequency_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assessment_code", models.CharField(max_length=100)),
                ("assessment_type", models.CharField(choices=[("internal", "Internal"), ("readiness", "Readiness"), ("customer", "Customer assurance"), ("regulatory", "Regulatory")], max_length=24)),
                ("scope", models.CharField(max_length=500)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("status", models.CharField(choices=[("draft", "Draft"), ("in_progress", "In progress"), ("submitted", "Submitted"), ("approved", "Approved"), ("rejected", "Rejected")], default="draft", max_length=20)),
                ("score_percent", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("evidence_sha256", models.CharField(blank=True, max_length=64)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.CharField(blank=True, max_length=1000)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("assessor_membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compliance_assessments", to="tenant.membership")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("framework", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assessments", to="compliance.complianceframework")),
                ("reviewer_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_compliance_assessments", to="tenant.membership")),
            ],
            options={
                "db_table": "compliance_assessment",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company", "status", "created_at"], name="cmp_assessment_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "assessment_code"), name="cmp_assessment_code_uq"),
                    models.CheckConstraint(condition=models.Q(("period_end__gte", models.F("period_start"))), name="cmp_assessment_period_ck"),
                    models.CheckConstraint(condition=models.Q(("score_percent__gte", 0), ("score_percent__lte", 100)), name="cmp_assessment_score_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskRegisterItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("risk_code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(choices=[("security", "Security"), ("privacy", "Privacy"), ("availability", "Availability"), ("third_party", "Third party"), ("compliance", "Compliance"), ("delivery", "Delivery")], max_length=24)),
                ("likelihood", models.PositiveSmallIntegerField()),
                ("impact", models.PositiveSmallIntegerField()),
                ("score", models.PositiveSmallIntegerField()),
                ("treatment", models.CharField(choices=[("mitigate", "Mitigate"), ("avoid", "Avoid"), ("transfer", "Transfer"), ("accept", "Accept")], max_length=16)),
                ("treatment_plan", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("treatment", "Treatment in progress"), ("accepted", "Accepted"), ("closed", "Closed")], default="open", max_length=16)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_by_public_id", models.UUIDField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("owner_membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_risks", to="tenant.membership")),
            ],
            options={
                "db_table": "compliance_risk_register",
                "ordering": ["-score", "risk_code"],
                "indexes": [models.Index(fields=["company", "status", "score"], name="cmp_risk_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "risk_code"), name="cmp_risk_code_uq"),
                    models.CheckConstraint(condition=models.Q(("likelihood__gte", 1), ("likelihood__lte", 5)), name="cmp_risk_likelihood_ck"),
                    models.CheckConstraint(condition=models.Q(("impact__gte", 1), ("impact__lte", 5)), name="cmp_risk_impact_ck"),
                    models.CheckConstraint(condition=models.Q(("score__gte", 1), ("score__lte", 25)), name="cmp_risk_score_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("exception_code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=220)),
                ("justification", models.TextField()),
                ("compensating_controls", models.TextField()),
                ("risk_rating", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], max_length=16)),
                ("status", models.CharField(choices=[("requested", "Requested"), ("approved", "Approved"), ("rejected", "Rejected"), ("revoked", "Revoked"), ("expired", "Expired")], default="requested", max_length=16)),
                ("expires_at", models.DateTimeField()),
                ("decision_reason", models.CharField(blank=True, max_length=1000)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("control", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="exceptions", to="compliance.compliancecontrol")),
                ("requested_by_membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requested_security_exceptions", to="tenant.membership")),
                ("reviewer_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_security_exceptions", to="tenant.membership")),
            ],
            options={
                "db_table": "compliance_security_exception",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company", "status", "expires_at"], name="cmp_exception_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "exception_code"), name="cmp_exception_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="AccessReviewCampaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("campaign_code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=220)),
                ("scope", models.CharField(choices=[("all_memberships", "All active memberships"), ("privileged_roles", "Privileged roles")], max_length=24)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("submitted", "Submitted"), ("approved", "Approved"), ("closed", "Closed")], default="draft", max_length=16)),
                ("due_at", models.DateTimeField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("owner_membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_access_reviews", to="tenant.membership")),
                ("reviewer_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="reviewed_access_campaigns", to="tenant.membership")),
            ],
            options={
                "db_table": "compliance_access_review",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company", "status", "due_at"], name="cmp_access_review_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "campaign_code"), name="cmp_access_review_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="ControlEvaluation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("result", models.CharField(choices=[("pending", "Pending"), ("compliant", "Compliant"), ("partial", "Partially compliant"), ("non_compliant", "Non-compliant"), ("not_applicable", "Not applicable")], default="pending", max_length=20)),
                ("evidence_summary", models.TextField(blank=True)),
                ("evidence_reference", models.CharField(blank=True, max_length=500)),
                ("remediation_due_at", models.DateTimeField(blank=True, null=True)),
                ("assessed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("assessment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluations", to="compliance.complianceassessment")),
                ("assessed_by_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="compliance_control_evaluations", to="tenant.membership")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("control", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluations", to="compliance.compliancecontrol")),
            ],
            options={
                "db_table": "compliance_control_evaluation",
                "ordering": ["control__code"],
                "indexes": [models.Index(fields=["company", "result", "remediation_due_at"], name="cmp_evaluation_result_idx")],
                "constraints": [models.UniqueConstraint(fields=("assessment", "control"), name="cmp_evaluation_control_uq")],
            },
        ),
        migrations.CreateModel(
            name="AccessReviewItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role_public_id", models.UUIDField()),
                ("role_code", models.CharField(max_length=100)),
                ("role_name", models.CharField(max_length=200)),
                ("permission_count", models.PositiveIntegerField(default=0)),
                ("decision", models.CharField(choices=[("pending", "Pending"), ("retain", "Retain"), ("remove", "Remove"), ("modify", "Modify")], default="pending", max_length=16)),
                ("reason", models.CharField(blank=True, max_length=1000)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("campaign", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="compliance.accessreviewcampaign")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="access_review_items", to="tenant.membership")),
                ("reviewed_by_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="completed_access_reviews", to="tenant.membership")),
            ],
            options={
                "db_table": "compliance_access_review_item",
                "ordering": ["membership__user__email", "role_code"],
                "indexes": [models.Index(fields=["company", "decision", "reviewed_at"], name="cmp_access_item_idx")],
                "constraints": [models.UniqueConstraint(fields=("campaign", "membership", "role_public_id"), name="cmp_access_item_role_uq")],
            },
        ),
    ]
