from django.urls import path

from .views import (
    ActivityAttachmentDownloadView,
    ActivityAttachmentListCreateView,
    ActivityDashboardView,
    ActivityDetailView,
    ActivityListCreateView,
    ContactDuplicateView,
    ContactListCreateView,
    ContactRevealView,
    ContactTimelineView,
    ContactToLeadView,
    CrmAccountView,
    CrmAccountWorkspaceView,
    CrmAutomationExecutionListView,
    CrmAutomationRuleDetailView,
    CrmAutomationRuleListCreateView,
    CrmConfigurationView,
    CrmCustomFieldListCreateView,
    CrmIndustryPackApplyView,
    CrmLeadSourceListCreateView,
    CrmMyWorkView,
    CrmPeopleView,
    CrmPipelineListCreateView,
    CrmRelationshipWorkspaceView,
    CrmSummaryView,
    CustomerDetailView,
    CustomerListCreateView,
    LeadConvertView,
    LeadDetailView,
    LeadIntelligenceOverrideView,
    LeadIntelligenceView,
    LeadListCreateView,
    LeadTimelineView,
    LeadTransitionView,
    OpportunityListCreateView,
    OpportunityPreconstructionView,
    OpportunityProjectConvertView,
    OpportunityTransitionView,
    PipelineStageListCreateView,
)

urlpatterns = [
    path("automations", CrmAutomationRuleListCreateView.as_view(), name="crm-automations"),
    path("automations/executions", CrmAutomationExecutionListView.as_view(), name="crm-automation-executions"),
    path("automations/<uuid:public_id>", CrmAutomationRuleDetailView.as_view(), name="crm-automation-rule"),
    path("configuration", CrmConfigurationView.as_view(), name="crm-configuration"),
    path("configuration/apply-pack", CrmIndustryPackApplyView.as_view(), name="crm-configuration-apply-pack"),
    path("pipelines", CrmPipelineListCreateView.as_view(), name="crm-pipelines"),
    path("custom-fields", CrmCustomFieldListCreateView.as_view(), name="crm-custom-fields"),
    path("lead-sources", CrmLeadSourceListCreateView.as_view(), name="crm-lead-sources"),
    path("summary", CrmSummaryView.as_view(), name="crm-summary"),
    path("my-work", CrmMyWorkView.as_view(), name="crm-my-work"),
    path("people", CrmPeopleView.as_view(), name="crm-people"),
    path("people/<uuid:public_id>", CrmRelationshipWorkspaceView.as_view(), name="crm-person-workspace"),
    path("accounts", CrmAccountView.as_view(), name="crm-accounts"),
    path("accounts/<uuid:public_id>", CrmAccountWorkspaceView.as_view(), name="crm-account-workspace"),
    path("stages", PipelineStageListCreateView.as_view(), name="crm-stages"),
    path("customers", CustomerListCreateView.as_view(), name="crm-customers"),
    path("customers/<uuid:public_id>", CustomerDetailView.as_view(), name="crm-customer"),
    path("contacts", ContactListCreateView.as_view(), name="crm-contacts"),
    path("contacts/duplicates", ContactDuplicateView.as_view(), name="crm-contact-duplicates"),
    path(
        "contacts/<uuid:public_id>/reveal",
        ContactRevealView.as_view(),
        name="crm-contact-reveal",
    ),
    path(
        "contacts/<uuid:public_id>/convert-lead",
        ContactToLeadView.as_view(),
        name="crm-contact-convert-lead",
    ),
    path(
        "contacts/<uuid:public_id>/timeline",
        ContactTimelineView.as_view(),
        name="crm-contact-timeline",
    ),
    path("leads", LeadListCreateView.as_view(), name="crm-leads"),
    path("leads/<uuid:public_id>", LeadDetailView.as_view(), name="crm-lead"),
    path("leads/<uuid:public_id>/timeline", LeadTimelineView.as_view(), name="crm-lead-timeline"),
    path("leads/<uuid:public_id>/intelligence", LeadIntelligenceView.as_view(), name="crm-lead-intelligence"),
    path("leads/<uuid:public_id>/intelligence/override", LeadIntelligenceOverrideView.as_view(), name="crm-lead-intelligence-override"),
    path(
        "leads/<uuid:public_id>/transition",
        LeadTransitionView.as_view(),
        name="crm-lead-transition",
    ),
    path(
        "leads/<uuid:public_id>/convert",
        LeadConvertView.as_view(),
        name="crm-lead-convert",
    ),
    path(
        "opportunities",
        OpportunityListCreateView.as_view(),
        name="crm-opportunities",
    ),
    path(
        "opportunities/<uuid:public_id>/transition",
        OpportunityTransitionView.as_view(),
        name="crm-opportunity-transition",
    ),
    path(
        "opportunities/<uuid:public_id>/start-preconstruction",
        OpportunityPreconstructionView.as_view(),
        name="crm-opportunity-start-preconstruction",
    ),
    path(
        "opportunities/<uuid:public_id>/convert-project",
        OpportunityProjectConvertView.as_view(),
        name="crm-opportunity-convert-project",
    ),
    path("activities", ActivityListCreateView.as_view(), name="crm-activities"),
    path("activities/<uuid:public_id>", ActivityDetailView.as_view(), name="crm-activity"),
    path("activities/dashboard", ActivityDashboardView.as_view(), name="crm-activity-dashboard"),
    path(
        "activities/<uuid:public_id>/attachments",
        ActivityAttachmentListCreateView.as_view(),
        name="crm-activity-attachments",
    ),
    path(
        "activities/<uuid:public_id>/attachments/<uuid:attachment_public_id>/download",
        ActivityAttachmentDownloadView.as_view(),
        name="crm-activity-attachment-download",
    ),
]
