# Generated for MPSqre Build360 Phase 23 Equipment & Fleet Operations.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(max_length=80)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(default=dict)),
                ("change_note", models.CharField(blank=True, max_length=500)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment_policy_versions", to="tenant.company")),
            ],
            options={"db_table": "equipmentops_policy_version"},
        ),
        migrations.CreateModel(
            name="EquipmentAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("category_code", models.CharField(max_length=80)),
                ("asset_type_code", models.CharField(max_length=80)),
                ("ownership_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("manufacturer", models.CharField(blank=True, max_length=150)),
                ("model_reference", models.CharField(blank=True, max_length=150)),
                ("serial_number", models.CharField(blank=True, max_length=150)),
                ("registration_number", models.CharField(blank=True, max_length=150)),
                ("commissioned_on", models.DateField(blank=True, null=True)),
                ("decommissioned_on", models.DateField(blank=True, null=True)),
                ("home_location_public_id", models.UUIDField(blank=True, null=True)),
                ("responsible_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("capacity_value", models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ("capacity_unit_code", models.CharField(blank=True, max_length=50)),
                ("meter_type_code", models.CharField(blank=True, max_length=50)),
                ("current_meter_value", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("acquisition_cost", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("next_service_on", models.DateField(blank=True, null=True)),
                ("next_service_meter", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("compliance_due_on", models.DateField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment_assets", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="equipmentops.equipmentpolicyversion")),
            ],
            options={"db_table": "equipmentops_asset"},
        ),
        migrations.CreateModel(
            name="EquipmentDeployment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deployment_code", models.CharField(max_length=100)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("location_public_id", models.UUIDField(blank=True, null=True)),
                ("operator_employee_public_id", models.UUIDField(blank=True, null=True)),
                ("status_code", models.CharField(max_length=80)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("planned_meter_start", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("planned_meter_end", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("source_reference", models.CharField(blank=True, max_length=150)),
                ("metadata", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deployments", to="equipmentops.equipmentasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment_deployments", to="tenant.company")),
            ],
            options={"db_table": "equipmentops_deployment"},
        ),
        migrations.CreateModel(
            name="EquipmentMeterReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reading_at", models.DateTimeField()),
                ("meter_type_code", models.CharField(max_length=50)),
                ("reading_value", models.DecimalField(decimal_places=2, max_digits=18)),
                ("source_code", models.CharField(max_length=80)),
                ("recorded_by_public_id", models.UUIDField()),
                ("evidence_object_key", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(default=dict)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="meter_readings", to="equipmentops.equipmentasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment_meter_readings", to="tenant.company")),
                ("deployment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="meter_readings", to="equipmentops.equipmentdeployment")),
            ],
            options={"db_table": "equipmentops_meter_reading"},
        ),
        migrations.CreateModel(
            name="MaintenanceWorkOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("maintenance_type_code", models.CharField(max_length=80)),
                ("priority_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("reported_at", models.DateTimeField()),
                ("scheduled_start", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("meter_at_open", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("summary", models.CharField(max_length=300)),
                ("details", models.TextField(blank=True)),
                ("vendor_public_id", models.UUIDField(blank=True, null=True)),
                ("estimated_cost", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("actual_cost", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("currency", models.CharField(max_length=3)),
                ("requires_approval", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="work_orders", to="equipmentops.equipmentasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment_work_orders", to="tenant.company")),
            ],
            options={"db_table": "equipmentops_maintenance_order"},
        ),
        migrations.CreateModel(
            name="EquipmentInspection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inspection_code", models.CharField(max_length=100)),
                ("inspection_type_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("result_code", models.CharField(max_length=80)),
                ("inspected_at", models.DateTimeField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("inspector_public_id", models.UUIDField()),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ("findings_count", models.PositiveIntegerField(default=0)),
                ("certificate_reference", models.CharField(blank=True, max_length=150)),
                ("evidence_object_key", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(default=dict)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inspections", to="equipmentops.equipmentasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment_inspections", to="tenant.company")),
            ],
            options={"db_table": "equipmentops_inspection"},
        ),
        migrations.CreateModel(
            name="EquipmentApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_code", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("requested_from_membership_public_id", models.UUIDField()),
                ("requested_by_public_id", models.UUIDField()),
                ("requested_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by_public_id", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_code", models.CharField(blank=True, max_length=80)),
                ("decision_reason", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment_approvals", to="tenant.company")),
                ("work_order", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approvals", to="equipmentops.maintenanceworkorder")),
            ],
            options={"db_table": "equipmentops_approval"},
        ),
        migrations.CreateModel(
            name="EquipmentRisk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("risk_code", models.CharField(max_length=100)),
                ("severity_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("message", models.CharField(max_length=1000)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("resolution_code", models.CharField(blank=True, max_length=80)),
                ("resolution_note", models.CharField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(default=dict)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="risks", to="equipmentops.equipmentasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="equipment_risks", to="tenant.company")),
                ("work_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="risks", to="equipmentops.maintenanceworkorder")),
            ],
            options={"db_table": "equipmentops_risk"},
        ),
        migrations.AddConstraint(model_name="equipmentpolicyversion", constraint=models.UniqueConstraint(fields=("company", "code", "version"), name="eqpol_company_code_ver_uq")),
        migrations.AddConstraint(model_name="equipmentpolicyversion", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="eqpol_effective_range_ck")),
        migrations.AddConstraint(model_name="equipmentpolicyversion", constraint=models.CheckConstraint(condition=models.Q(("retired_at__isnull", True), ("published_at__isnull", False), _connector="OR"), name="eqpol_retired_publish_ck")),
        migrations.AddIndex(model_name="equipmentpolicyversion", index=models.Index(fields=["company", "code", "status_code"], name="eqpol_company_status_idx")),
        migrations.AddIndex(model_name="equipmentpolicyversion", index=models.Index(fields=["company", "effective_from", "effective_to"], name="eqpol_effective_idx")),
        migrations.AddConstraint(model_name="equipmentasset", constraint=models.UniqueConstraint(fields=("company", "asset_code"), name="eqasset_company_code_uq")),
        migrations.AddConstraint(model_name="equipmentasset", constraint=models.CheckConstraint(condition=models.Q(("current_meter_value__gte", 0)), name="eqasset_meter_nonneg_ck")),
        migrations.AddConstraint(model_name="equipmentasset", constraint=models.CheckConstraint(condition=models.Q(("acquisition_cost__gte", 0)), name="eqasset_cost_nonneg_ck")),
        migrations.AddConstraint(model_name="equipmentasset", constraint=models.CheckConstraint(condition=models.Q(("decommissioned_on__isnull", True), ("commissioned_on__isnull", True), ("decommissioned_on__gte", models.F("commissioned_on")), _connector="OR"), name="eqasset_dates_ck")),
        migrations.AddIndex(model_name="equipmentasset", index=models.Index(fields=["company", "status_code", "category_code"], name="eqasset_status_cat_idx")),
        migrations.AddIndex(model_name="equipmentasset", index=models.Index(fields=["company", "next_service_on"], name="eqasset_service_due_idx")),
        migrations.AddIndex(model_name="equipmentasset", index=models.Index(fields=["company", "compliance_due_on"], name="eqasset_compliance_idx")),
        migrations.AddConstraint(model_name="equipmentdeployment", constraint=models.UniqueConstraint(fields=("company", "deployment_code"), name="eqdeploy_company_code_uq")),
        migrations.AddConstraint(model_name="equipmentdeployment", constraint=models.CheckConstraint(condition=models.Q(("ends_at__isnull", True), ("ends_at__gt", models.F("starts_at")), _connector="OR"), name="eqdeploy_date_range_ck")),
        migrations.AddConstraint(model_name="equipmentdeployment", constraint=models.CheckConstraint(condition=models.Q(("planned_meter_start__isnull", True), ("planned_meter_start__gte", 0), _connector="OR"), name="eqdeploy_start_meter_ck")),
        migrations.AddConstraint(model_name="equipmentdeployment", constraint=models.CheckConstraint(condition=models.Q(("planned_meter_end__isnull", True), ("planned_meter_start__isnull", True), ("planned_meter_end__gte", models.F("planned_meter_start")), _connector="OR"), name="eqdeploy_meter_range_ck")),
        migrations.AddIndex(model_name="equipmentdeployment", index=models.Index(fields=["company", "status_code", "starts_at"], name="eqdeploy_status_start_idx")),
        migrations.AddIndex(model_name="equipmentdeployment", index=models.Index(fields=["asset", "status_code", "ends_at"], name="eqdeploy_asset_status_idx")),
        migrations.AddConstraint(model_name="equipmentmeterreading", constraint=models.UniqueConstraint(fields=("asset", "meter_type_code", "reading_at"), name="eqmeter_asset_type_time_uq")),
        migrations.AddConstraint(model_name="equipmentmeterreading", constraint=models.CheckConstraint(condition=models.Q(("reading_value__gte", 0)), name="eqmeter_value_nonneg_ck")),
        migrations.AddIndex(model_name="equipmentmeterreading", index=models.Index(fields=["company", "reading_at"], name="eqmeter_company_time_idx")),
        migrations.AddIndex(model_name="equipmentmeterreading", index=models.Index(fields=["asset", "meter_type_code", "reading_at"], name="eqmeter_asset_time_idx")),
        migrations.AddConstraint(model_name="maintenanceworkorder", constraint=models.UniqueConstraint(fields=("company", "code"), name="eqwork_company_code_uq")),
        migrations.AddConstraint(model_name="maintenanceworkorder", constraint=models.CheckConstraint(condition=models.Q(("estimated_cost__gte", 0)), name="eqwork_est_cost_nonneg_ck")),
        migrations.AddConstraint(model_name="maintenanceworkorder", constraint=models.CheckConstraint(condition=models.Q(("actual_cost__gte", 0)), name="eqwork_act_cost_nonneg_ck")),
        migrations.AddConstraint(model_name="maintenanceworkorder", constraint=models.CheckConstraint(condition=models.Q(("scheduled_end__isnull", True), ("scheduled_start__isnull", True), ("scheduled_end__gt", models.F("scheduled_start")), _connector="OR"), name="eqwork_schedule_range_ck")),
        migrations.AddConstraint(model_name="maintenanceworkorder", constraint=models.CheckConstraint(condition=models.Q(("completed_at__isnull", True), ("completed_at__gte", models.F("reported_at")), _connector="OR"), name="eqwork_complete_time_ck")),
        migrations.AddIndex(model_name="maintenanceworkorder", index=models.Index(fields=["company", "status_code", "priority_code"], name="eqwork_status_priority_idx")),
        migrations.AddIndex(model_name="maintenanceworkorder", index=models.Index(fields=["asset", "status_code", "scheduled_start"], name="eqwork_asset_schedule_idx")),
        migrations.AddConstraint(model_name="equipmentinspection", constraint=models.UniqueConstraint(fields=("company", "inspection_code"), name="eqinspect_company_code_uq")),
        migrations.AddConstraint(model_name="equipmentinspection", constraint=models.CheckConstraint(condition=models.Q(("score__isnull", True), ("score__gte", 0), _connector="OR"), name="eqinspect_score_nonneg_ck")),
        migrations.AddIndex(model_name="equipmentinspection", index=models.Index(fields=["company", "valid_until", "result_code"], name="eqinspect_valid_result_idx")),
        migrations.AddIndex(model_name="equipmentinspection", index=models.Index(fields=["asset", "inspected_at"], name="eqinspect_asset_time_idx")),
        migrations.AddConstraint(model_name="equipmentapproval", constraint=models.UniqueConstraint(fields=("work_order", "step_code"), name="eqapproval_order_step_uq")),
        migrations.AddIndex(model_name="equipmentapproval", index=models.Index(fields=["company", "status_code", "requested_at"], name="eqapproval_status_idx")),
        migrations.AddIndex(model_name="equipmentapproval", index=models.Index(fields=["company", "due_at", "decided_at"], name="eqapproval_due_idx")),
        migrations.AddIndex(model_name="equipmentrisk", index=models.Index(fields=["company", "status_code", "severity_code"], name="eqrisk_status_severity_idx")),
        migrations.AddIndex(model_name="equipmentrisk", index=models.Index(fields=["asset", "resolved_at", "due_at"], name="eqrisk_asset_due_idx")),
    ]
