# Generated for MPSqre Build360 Phase 16.
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="PilotProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cohort_code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=220)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("preparing", "Preparing"), ("ready", "Ready"), ("live", "Live"), ("paused", "Paused"), ("completed", "Completed")], default="draft", max_length=30)),
                ("target_start_date", models.DateField(blank=True, null=True)),
                ("target_go_live_at", models.DateTimeField(blank=True, null=True)),
                ("actual_go_live_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("owner_membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_pilot_programs", to="tenant.membership")),
            ],
            options={
                "db_table": "pilotops_program",
                "indexes": [models.Index(fields=["company", "status"], name="pilot_program_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "cohort_code"), name="pilot_program_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="PilotChecklistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("category", models.CharField(choices=[("governance", "Governance"), ("identity", "Identity and access"), ("master_data", "Master data"), ("training", "Training"), ("process", "Business process"), ("technical", "Technical readiness"), ("security", "Security"), ("data", "Data readiness"), ("go_live", "Go-live"), ("support", "Support")], max_length=30)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("is_required", models.BooleanField(default=True)),
                ("sequence", models.PositiveIntegerField(default=100)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("in_progress", "In progress"), ("completed", "Completed"), ("waived", "Waived"), ("blocked", "Blocked")], default="pending", max_length=30)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("waiver_reason", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("owner_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="pilot_checklist_items", to="tenant.membership")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="checklist_items", to="pilotops.pilotprogram")),
            ],
            options={
                "db_table": "pilotops_checklist_item",
                "indexes": [models.Index(fields=["company", "program", "status"], name="pilot_check_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "program", "code"), name="pilot_check_item_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="MasterDataReadiness",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("domain_code", models.CharField(max_length=100)),
                ("domain_name", models.CharField(max_length=200)),
                ("minimum_records", models.PositiveIntegerField(default=1)),
                ("current_records", models.PositiveIntegerField(default=0)),
                ("is_required", models.BooleanField(default=True)),
                ("status", models.CharField(choices=[("not_started", "Not started"), ("in_progress", "In progress"), ("ready", "Ready"), ("blocked", "Blocked")], default="not_started", max_length=30)),
                ("validation_summary", models.JSONField(default=dict)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="master_data_domains", to="pilotops.pilotprogram")),
            ],
            options={
                "db_table": "pilotops_master_data",
                "indexes": [models.Index(fields=["company", "program", "status"], name="pilot_master_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "program", "domain_code"), name="pilot_master_domain_uq")],
            },
        ),
        migrations.CreateModel(
            name="TrainingModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True)),
                ("audience_codes", models.JSONField(default=list)),
                ("is_required", models.BooleanField(default=True)),
                ("sequence", models.PositiveIntegerField(default=100)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("retired", "Retired")], default="draft", max_length=30)),
                ("content_url", models.URLField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="training_modules", to="pilotops.pilotprogram")),
            ],
            options={
                "db_table": "pilotops_training_module",
                "constraints": [models.UniqueConstraint(fields=("company", "program", "code"), name="pilot_training_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="TrainingCompletion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("assigned", "Assigned"), ("in_progress", "In progress"), ("completed", "Completed"), ("waived", "Waived")], default="assigned", max_length=30)),
                ("score_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("assigned_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="training_completions", to="tenant.membership")),
                ("module", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="completions", to="pilotops.trainingmodule")),
            ],
            options={
                "db_table": "pilotops_training_completion",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "module", "membership"), name="pilot_training_member_uq"),
                    models.CheckConstraint(condition=models.Q(score_percent__isnull=True) | (models.Q(score_percent__gte=0) & models.Q(score_percent__lte=100)), name="pilot_training_score_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ReadinessAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("assessed_at", models.DateTimeField()),
                ("assessed_by_public_id", models.UUIDField()),
                ("score_percent", models.PositiveSmallIntegerField()),
                ("critical_blockers", models.JSONField(default=list)),
                ("warnings", models.JSONField(default=list)),
                ("metrics", models.JSONField(default=dict)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="readiness_assessments", to="pilotops.pilotprogram")),
            ],
            options={
                "db_table": "pilotops_readiness_assessment",
                "indexes": [models.Index(fields=["company", "program", "assessed_at"], name="pilot_readiness_time_idx")],
                "constraints": [models.CheckConstraint(condition=models.Q(score_percent__lte=100), name="pilot_readiness_score_ck")],
            },
        ),
        migrations.CreateModel(
            name="GoLivePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_at", models.DateTimeField(blank=True, null=True)),
                ("cutover_window_minutes", models.PositiveIntegerField(default=120)),
                ("support_window_hours", models.PositiveIntegerField(default=72)),
                ("rollback_reference", models.CharField(blank=True, max_length=300)),
                ("cutover_steps", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("in_review", "In review"), ("approved", "Approved"), ("in_progress", "In progress"), ("live", "Live"), ("rolled_back", "Rolled back"), ("cancelled", "Cancelled")], default="draft", max_length=30)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("program", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="go_live_plan", to="pilotops.pilotprogram")),
            ],
            options={
                "db_table": "pilotops_go_live_plan",
                "indexes": [models.Index(fields=["company", "status"], name="pilot_golive_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="GoLiveSignoff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("area", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=220)),
                ("is_required", models.BooleanField(default=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected"), ("waived", "Waived")], default="pending", max_length=30)),
                ("signed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="signoffs", to="pilotops.goliveplan")),
                ("signer_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="go_live_signoffs", to="tenant.membership")),
            ],
            options={
                "db_table": "pilotops_go_live_signoff",
                "constraints": [models.UniqueConstraint(fields=("company", "plan", "code"), name="pilot_golive_signoff_uq")],
            },
        ),
        migrations.CreateModel(
            name="AdoptionSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("training_completion_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("completed_checklist_items", models.PositiveIntegerField(default=0)),
                ("total_checklist_items", models.PositiveIntegerField(default=0)),
                ("key_activity_count", models.PositiveIntegerField(default=0)),
                ("metrics", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="adoption_snapshots", to="pilotops.pilotprogram")),
            ],
            options={
                "db_table": "pilotops_adoption_snapshot",
                "indexes": [models.Index(fields=["company", "program", "period_end"], name="pilot_adoption_time_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "program", "period_end"), name="pilot_adoption_period_uq"),
                    models.CheckConstraint(condition=models.Q(period_end__gte=models.F("period_start")), name="pilot_adoption_period_ck"),
                    models.CheckConstraint(condition=models.Q(training_completion_percent__gte=0) & models.Q(training_completion_percent__lte=100), name="pilot_adoption_training_ck"),
                ],
            },
        ),
    ]
