import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("adminops", "0001_initial"),
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=180)),
                ("provider", models.CharField(choices=[("generic", "Provider neutral"), ("aws", "Amazon Web Services"), ("azure", "Microsoft Azure"), ("gcp", "Google Cloud"), ("render", "Render"), ("vercel", "Vercel"), ("cloudflare", "Cloudflare")], max_length=24)),
                ("region", models.CharField(max_length=100)),
                ("data_residency", models.CharField(max_length=100)),
                ("backend_service", models.CharField(blank=True, max_length=160)),
                ("frontend_service", models.CharField(blank=True, max_length=160)),
                ("database_service", models.CharField(blank=True, max_length=160)),
                ("cache_service", models.CharField(blank=True, max_length=160)),
                ("object_storage_service", models.CharField(blank=True, max_length=160)),
                ("worker_service", models.CharField(blank=True, max_length=160)),
                ("secret_manager_service", models.CharField(blank=True, max_length=160)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("ready", "Ready"), ("active", "Active"), ("suspended", "Suspended"), ("retired", "Retired")], default="draft", max_length=20)),
                ("production_approved", models.BooleanField(default=False)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cloud_targets", to="adminops.runtimeenvironment")),
            ],
            options={"db_table": "cloudops_target", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="DeploymentPipeline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("source_branch", models.CharField(default="main", max_length=160)),
                ("trigger_mode", models.CharField(choices=[("manual", "Manual"), ("push", "Source push"), ("tag", "Release tag")], default="manual", max_length=20)),
                ("quality_gates", models.JSONField(default=list)),
                ("requires_approval", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pipelines", to="cloudops.cloudtarget")),
            ],
            options={"db_table": "cloudops_pipeline", "ordering": ["target__code", "code"]},
        ),
        migrations.CreateModel(
            name="BackupPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("resource_type", models.CharField(choices=[("database", "PostgreSQL database"), ("object_storage", "Object storage"), ("configuration", "Configuration and secrets inventory"), ("full", "Full platform backup")], max_length=24)),
                ("schedule_cron", models.CharField(max_length=100)),
                ("retention_days", models.PositiveIntegerField(default=30)),
                ("encryption_required", models.BooleanField(default=True)),
                ("point_in_time_recovery", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="backup_policies", to="cloudops.cloudtarget")),
            ],
            options={"db_table": "cloudops_backup_policy", "ordering": ["target__code", "code"]},
        ),
        migrations.CreateModel(
            name="SecretRotationPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("secret_provider", models.CharField(max_length=100)),
                ("secret_reference", models.CharField(max_length=500)),
                ("rotation_interval_days", models.PositiveIntegerField(default=90)),
                ("last_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("next_rotation_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("current", "Current"), ("due", "Due"), ("overdue", "Overdue"), ("suspended", "Suspended")], default="due", max_length=20)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="secret_policies", to="cloudops.cloudtarget")),
            ],
            options={"db_table": "cloudops_secret_policy", "ordering": ["target__code", "code"]},
        ),
        migrations.CreateModel(
            name="DeploymentExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("requested", "Requested"), ("validated", "Validated"), ("approved", "Approved"), ("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("rolled_back", "Rolled back")], default="requested", max_length=20)),
                ("source_revision", models.CharField(max_length=160)),
                ("artifact_sha256", models.CharField(max_length=64)),
                ("migration_plan_sha256", models.CharField(blank=True, max_length=64)),
                ("deployment_url", models.URLField(blank=True)),
                ("requested_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("executed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("logs_sha256", models.CharField(blank=True, max_length=64)),
                ("error_summary", models.CharField(blank=True, max_length=1000)),
                ("rollback_reference", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("pipeline", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="executions", to="cloudops.deploymentpipeline")),
                ("release", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cloud_deployments", to="adminops.releaserecord")),
            ],
            options={"db_table": "cloudops_deployment", "ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="BackupExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("running", "Running"), ("succeeded", "Succeeded"), ("failed", "Failed"), ("verified", "Verified")], max_length=20)),
                ("backup_reference", models.CharField(blank=True, max_length=500)),
                ("backup_sha256", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("recovery_point_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("evidence_sha256", models.CharField(blank=True, max_length=64)),
                ("error_summary", models.CharField(blank=True, max_length=1000)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="executions", to="cloudops.backuppolicy")),
            ],
            options={"db_table": "cloudops_backup_execution", "ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="RestoreExercise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(choices=[("planned", "Planned"), ("running", "Running"), ("passed", "Passed"), ("failed", "Failed"), ("approved", "Approved")], default="planned", max_length=20)),
                ("requested_by_public_id", models.UUIDField()),
                ("reviewed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("measured_rpo_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("measured_rto_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("evidence_sha256", models.CharField(blank=True, max_length=64)),
                ("notes", models.CharField(blank=True, max_length=1000)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("backup_execution", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="restore_exercises", to="cloudops.backupexecution")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("target", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="restore_exercises", to="cloudops.cloudtarget")),
            ],
            options={"db_table": "cloudops_restore_exercise", "ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(model_name="cloudtarget", constraint=models.UniqueConstraint(fields=("company", "code"), name="cld_target_code_uq")),
        migrations.AddIndex(model_name="cloudtarget", index=models.Index(fields=["company", "status", "provider"], name="cld_target_status_idx")),
        migrations.AddConstraint(model_name="deploymentpipeline", constraint=models.UniqueConstraint(fields=("target", "code"), name="cld_pipeline_code_uq")),
        migrations.AddIndex(model_name="deploymentpipeline", index=models.Index(fields=["company", "is_active", "trigger_mode"], name="cld_pipeline_active_idx")),
        migrations.AddConstraint(model_name="backuppolicy", constraint=models.UniqueConstraint(fields=("target", "code"), name="cld_backup_policy_uq")),
        migrations.AddIndex(model_name="backuppolicy", index=models.Index(fields=["company", "is_active", "resource_type"], name="cld_backup_active_idx")),
        migrations.AddConstraint(model_name="secretrotationpolicy", constraint=models.UniqueConstraint(fields=("target", "code"), name="cld_secret_policy_uq")),
        migrations.AddIndex(model_name="secretrotationpolicy", index=models.Index(fields=["company", "status", "next_rotation_at"], name="cld_secret_due_idx")),
        migrations.AddIndex(model_name="deploymentexecution", index=models.Index(fields=["company", "status", "created_at"], name="cld_deploy_status_idx")),
        migrations.AddIndex(model_name="deploymentexecution", index=models.Index(fields=["pipeline", "created_at"], name="cld_deploy_pipe_idx")),
        migrations.AddIndex(model_name="backupexecution", index=models.Index(fields=["company", "status", "started_at"], name="cld_backup_run_idx")),
        migrations.AddIndex(model_name="restoreexercise", index=models.Index(fields=["company", "status", "created_at"], name="cld_restore_status_idx")),
    ]
