import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial"), ("landops", "0003_seed_defaults")]

    operations = [
        migrations.CreateModel(
            name="CapitalPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("covenant_alert_days", models.PositiveIntegerField(default=30)),
                ("commitment_expiry_alert_days", models.PositiveIntegerField(default=45)),
                ("maximum_leverage_percent", models.DecimalField(decimal_places=4, default=Decimal("70.0000"), max_digits=7)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_policies", to="tenant.company")),
            ],
            options={
                "db_table": "capitalops_policy",
                "indexes": [models.Index(fields=["company", "status_code"], name="cap_policy_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "version"), name="cap_policy_ver_uq"),
                    models.CheckConstraint(condition=models.Q(effective_to__isnull=True) | models.Q(effective_from__isnull=True) | models.Q(effective_to__gt=models.F("effective_from")), name="cap_policy_dates_ck"),
                    models.CheckConstraint(condition=models.Q(maximum_leverage_percent__gte=0) & models.Q(maximum_leverage_percent__lte=100), name="cap_policy_lev_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FundingProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("program_code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("program_type_code", models.CharField(default="PROJECT_FINANCE", max_length=60)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("land_opportunity_public_id", models.UUIDField(blank=True, null=True)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("target_capital", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("target_equity", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("target_debt", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("sponsor_public_id", models.UUIDField()),
                ("committee_public_id", models.UUIDField(blank=True, null=True)),
                ("start_on", models.DateField(blank=True, null=True)),
                ("target_close_on", models.DateField(blank=True, null=True)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_programs", to="tenant.company")),
            ],
            options={
                "db_table": "capitalops_program",
                "indexes": [
                    models.Index(fields=["company", "status_code", "target_close_on"], name="cap_program_status_idx"),
                    models.Index(fields=["company", "project_public_id"], name="cap_program_proj_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "program_code"), name="cap_program_code_uq"),
                    models.CheckConstraint(condition=models.Q(target_capital__gte=0), name="cap_program_total_ck"),
                    models.CheckConstraint(condition=models.Q(target_equity__gte=0), name="cap_program_equity_ck"),
                    models.CheckConstraint(condition=models.Q(target_debt__gte=0), name="cap_program_debt_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("investor_code", models.CharField(max_length=80)),
                ("legal_name", models.CharField(max_length=240)),
                ("investor_type_code", models.CharField(default="INSTITUTIONAL", max_length=60)),
                ("jurisdiction_code", models.CharField(blank=True, max_length=80)),
                ("contact_data", models.JSONField(blank=True, default=dict)),
                ("kyc_status_code", models.CharField(default="PENDING", max_length=30)),
                ("risk_rating_code", models.CharField(default="MEDIUM", max_length=30)),
                ("accredited_flag", models.BooleanField(default=False)),
                ("created_by_public_id", models.UUIDField()),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verification_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_investors", to="tenant.company")),
            ],
            options={
                "db_table": "capitalops_investor",
                "indexes": [
                    models.Index(fields=["company", "kyc_status_code"], name="cap_investor_kyc_idx"),
                    models.Index(fields=["company", "risk_rating_code"], name="cap_investor_risk_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("company", "investor_code"), name="cap_investor_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="JointVentureArrangement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("venture_code", models.CharField(max_length=80)),
                ("partner_name", models.CharField(max_length=240)),
                ("partner_reference", models.UUIDField(blank=True, null=True)),
                ("ownership_percent", models.DecimalField(decimal_places=4, max_digits=7)),
                ("profit_share_percent", models.DecimalField(decimal_places=4, max_digits=7)),
                ("governance", models.JSONField(blank=True, default=dict)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_joint_ventures", to="tenant.company")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="joint_ventures", to="capitalops.fundingprogram")),
            ],
            options={
                "db_table": "capitalops_joint_venture",
                "indexes": [models.Index(fields=["company", "status_code"], name="cap_jv_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("program", "venture_code"), name="cap_jv_code_uq"),
                    models.CheckConstraint(condition=models.Q(ownership_percent__gt=0) & models.Q(ownership_percent__lte=100), name="cap_jv_owner_ck"),
                    models.CheckConstraint(condition=models.Q(profit_share_percent__gte=0) & models.Q(profit_share_percent__lte=100), name="cap_jv_profit_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CapitalCommitment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("commitment_number", models.CharField(max_length=80)),
                ("commitment_type_code", models.CharField(default="EQUITY", max_length=60)),
                ("committed_amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("called_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("funded_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("committed_on", models.DateField()),
                ("expiry_on", models.DateField(blank=True, null=True)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_commitments", to="tenant.company")),
                ("investor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="commitments", to="capitalops.investorprofile")),
                ("joint_venture", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="commitments", to="capitalops.jointventurearrangement")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commitments", to="capitalops.fundingprogram")),
            ],
            options={
                "db_table": "capitalops_commitment",
                "indexes": [models.Index(fields=["company", "status_code", "expiry_on"], name="cap_commit_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "commitment_number"), name="cap_commitment_no_uq"),
                    models.CheckConstraint(condition=models.Q(committed_amount__gt=0), name="cap_commit_amount_ck"),
                    models.CheckConstraint(condition=models.Q(called_amount__gte=0), name="cap_commit_called_ck"),
                    models.CheckConstraint(condition=models.Q(funded_amount__gte=0), name="cap_commit_funded_ck"),
                    models.CheckConstraint(condition=(models.Q(investor__isnull=False) & models.Q(joint_venture__isnull=True)) | (models.Q(investor__isnull=True) & models.Q(joint_venture__isnull=False)), name="cap_commit_party_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DebtFacility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("facility_code", models.CharField(max_length=80)),
                ("lender_name", models.CharField(max_length=240)),
                ("facility_type_code", models.CharField(default="TERM_LOAN", max_length=60)),
                ("principal_limit", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("interest_rate_percent", models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ("tenor_months", models.PositiveIntegerField(default=12)),
                ("start_on", models.DateField(blank=True, null=True)),
                ("maturity_on", models.DateField(blank=True, null=True)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("security_summary", models.TextField(blank=True)),
                ("covenants", models.JSONField(blank=True, default=dict)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_debt_facilities", to="tenant.company")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="debt_facilities", to="capitalops.fundingprogram")),
            ],
            options={
                "db_table": "capitalops_debt_facility",
                "indexes": [models.Index(fields=["company", "status_code", "maturity_on"], name="cap_facility_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "facility_code"), name="cap_facility_code_uq"),
                    models.CheckConstraint(condition=models.Q(principal_limit__gt=0), name="cap_facility_limit_ck"),
                    models.CheckConstraint(condition=models.Q(interest_rate_percent__gte=0), name="cap_facility_rate_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DrawdownRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_number", models.CharField(max_length=80)),
                ("request_type_code", models.CharField(default="DEBT_DRAWDOWN", max_length=60)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("requested_on", models.DateField()),
                ("required_by", models.DateField(blank=True, null=True)),
                ("purpose", models.TextField(blank=True)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("requested_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("disbursed_on", models.DateField(blank=True, null=True)),
                ("disbursement_reference", models.CharField(blank=True, max_length=160)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("commitment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="drawdowns", to="capitalops.capitalcommitment")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_drawdowns", to="tenant.company")),
                ("debt_facility", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="drawdowns", to="capitalops.debtfacility")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="drawdowns", to="capitalops.fundingprogram")),
            ],
            options={
                "db_table": "capitalops_drawdown",
                "indexes": [models.Index(fields=["company", "status_code", "required_by"], name="cap_draw_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "request_number"), name="cap_drawdown_no_uq"),
                    models.CheckConstraint(condition=models.Q(amount__gt=0), name="cap_drawdown_amount_ck"),
                    models.CheckConstraint(condition=(models.Q(debt_facility__isnull=False) & models.Q(commitment__isnull=True)) | (models.Q(debt_facility__isnull=True) & models.Q(commitment__isnull=False)), name="cap_drawdown_source_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CovenantTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("test_number", models.CharField(max_length=80)),
                ("covenant_code", models.CharField(max_length=80)),
                ("tested_on", models.DateField()),
                ("metric_value", models.DecimalField(decimal_places=6, max_digits=20)),
                ("threshold_operator", models.CharField(default="LTE", max_length=10)),
                ("threshold_value", models.DecimalField(decimal_places=6, max_digits=20)),
                ("compliant", models.BooleanField(default=True)),
                ("status_code", models.CharField(default="OPEN", max_length=30)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("tested_by_public_id", models.UUIDField()),
                ("reviewed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_covenant_tests", to="tenant.company")),
                ("debt_facility", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="covenant_tests", to="capitalops.debtfacility")),
            ],
            options={
                "db_table": "capitalops_covenant",
                "indexes": [
                    models.Index(fields=["company", "status_code", "tested_on"], name="cap_cov_status_idx"),
                    models.Index(fields=["company", "compliant"], name="cap_cov_comp_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("company", "test_number"), name="cap_covenant_no_uq")],
            },
        ),
        migrations.CreateModel(
            name="InvestorDistribution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("distribution_number", models.CharField(max_length=80)),
                ("distribution_type_code", models.CharField(default="RETURN_OF_CAPITAL", max_length=60)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("declared_on", models.DateField()),
                ("payable_on", models.DateField(blank=True, null=True)),
                ("paid_on", models.DateField(blank=True, null=True)),
                ("payment_reference", models.CharField(blank=True, max_length=160)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_distributions", to="tenant.company")),
                ("investor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="distributions", to="capitalops.investorprofile")),
                ("joint_venture", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="distributions", to="capitalops.jointventurearrangement")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="distributions", to="capitalops.fundingprogram")),
            ],
            options={
                "db_table": "capitalops_distribution",
                "indexes": [models.Index(fields=["company", "status_code", "payable_on"], name="cap_dist_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "distribution_number"), name="cap_distribution_no_uq"),
                    models.CheckConstraint(condition=models.Q(amount__gt=0), name="cap_distribution_amt_ck"),
                    models.CheckConstraint(condition=(models.Q(investor__isnull=False) & models.Q(joint_venture__isnull=True)) | (models.Q(investor__isnull=True) & models.Q(joint_venture__isnull=False)), name="cap_distribution_party_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CapitalEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type_code", models.CharField(max_length=60)),
                ("event_on", models.DateTimeField()),
                ("summary", models.CharField(max_length=500)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("actor_public_id", models.UUIDField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="capital_events", to="tenant.company")),
                ("program", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="capitalops.fundingprogram")),
            ],
            options={
                "db_table": "capitalops_event",
                "indexes": [models.Index(fields=["company", "program", "event_on"], name="cap_event_program_idx")],
            },
        ),
    ]
