"use client";
import type { Route } from "next";
import Link from "next/link";
import { useEffect, useState } from "react";
export type Project = { public_id: string; code: string; name: string };
type EventItem = { kind: string; occurred_at: string; title: string; detail: string; tone: string; href: Route; reference: string };
type Payload = { project: Project & { stage_name: string }; summary: Record<string, number | null>; events: EventItem[] };
const tone: Record<string,string> = { ATTENTION:"bg-red-500", WARNING:"bg-amber-500", SUCCESS:"bg-emerald-500", INFO:"bg-blue-500" };
export function SitePulseWorkspace({ initialProjects, initialProject }: Readonly<{ initialProjects: Project[]; initialProject: string }>) {
  const first = initialProjects.some((p)=>p.public_id===initialProject) ? initialProject : initialProjects[0]?.public_id ?? "";
  const [project,setProject]=useState(first); const [payload,setPayload]=useState<Payload|null>(null); const [loading,setLoading]=useState(Boolean(first)); const [message,setMessage]=useState("");
  useEffect(()=>{ const c=new AbortController(); queueMicrotask(()=>{if(c.signal.aborted)return; if(!project){setPayload(null);setLoading(false);return;} setLoading(true);setMessage("");
    void fetch(`/api/project360/projects/${project}/site-timeline`,{signal:c.signal,cache:"no-store"}).then(async r=>{const b=await r.json() as Payload & {message?:string}; if(!r.ok)throw new Error(b.message??"Site pulse could not load."); return b;}).then(b=>{if(!c.signal.aborted){setPayload(b);setLoading(false);}}).catch(e=>{if(!c.signal.aborted){setMessage(e instanceof Error?e.message:"Site pulse could not load.");setLoading(false);}});}); return()=>c.abort();},[project]);
  const stats = payload ? [["Tasks",payload.summary.tasks],["Overdue",payload.summary.overdue_tasks],["Inspections today",payload.summary.inspections_today],["Open NCRs",payload.summary.open_ncrs],["Safety 30d",payload.summary.incidents_30d],["Receipts 7d",payload.summary.receipts_7d]] : [];
  return <main className="min-h-screen bg-[var(--background)] px-4 py-6 sm:px-7 lg:px-10"><div className="mx-auto max-w-[1400px] space-y-6">
    <header className="rounded-[30px] border border-[var(--border)] bg-white p-6 shadow-sm lg:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--brand)]">Project 360 · Site pulse</p><h1 className="mt-2 text-3xl font-semibold">One timeline for what changed on the project.</h1><p className="mt-2 text-sm text-[var(--muted)]">Tasks, quality, safety, material receipts and design issues are projected from their governed records.</p></div><select className="rounded-2xl border border-[var(--border)] bg-white px-4 py-3 text-sm font-semibold lg:w-[380px]" onChange={e=>setProject(e.target.value)} value={project}><option value="">Select project</option>{initialProjects.map(p=><option key={p.public_id} value={p.public_id}>{p.code} · {p.name}</option>)}</select></div>
    {payload?<div className="mt-6 grid gap-3 sm:grid-cols-3 lg:grid-cols-6">{stats.map(([l,v])=><div className="rounded-2xl bg-slate-50 p-4" key={String(l)}><p className="text-[11px] font-semibold text-[var(--muted)]">{l}</p><p className="mt-2 text-2xl font-semibold">{v ?? "—"}</p></div>)}</div>:null}</header>
    {message?<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{message}</div>:null}
    {loading?<div className="h-52 animate-pulse rounded-[28px] bg-slate-200"/>:null}
    {payload?<section className="rounded-[28px] border border-[var(--border)] bg-white p-5 shadow-sm sm:p-6"><div className="space-y-0">{payload.events.map((e,i)=><div className="grid grid-cols-[28px_1fr] gap-4" key={`${e.kind}-${e.occurred_at}-${i}`}><div className="flex flex-col items-center"><span className={`mt-1 h-3 w-3 rounded-full ${tone[e.tone]??tone.INFO}`}/>{i<payload.events.length-1?<span className="mt-1 h-full min-h-16 w-px bg-slate-200"/>:null}</div><Link className="mb-4 rounded-2xl border border-[var(--border)] p-4 transition hover:border-[var(--brand)]" href={e.href}><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-bold">{e.kind.replaceAll("_"," ")}</span>{e.reference?<span className="text-xs text-[var(--muted)]">{e.reference}</span>:null}<span className="ml-auto text-xs text-[var(--muted)]">{new Date(e.occurred_at).toLocaleString()}</span></div><h3 className="mt-2 font-semibold">{e.title}</h3><p className="mt-1 text-sm text-[var(--muted)]">{e.detail}</p></Link></div>)}</div>{!payload.events.length?<p className="p-8 text-center text-sm text-[var(--muted)]">No governed site events are available yet.</p>:null}</section>:null}
  </div></main>;
}
