# Generated for MPSqre Build360 Phase 5 projects.
import decimal
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="DeliveryStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(choices=[("project", "Project"), ("task", "Task"), ("design_version", "Design version"), ("estimate_version", "Estimate version")], max_length=30)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                ("outcome", models.CharField(choices=[("open", "Open"), ("review", "Under review"), ("approved", "Approved"), ("rejected", "Rejected"), ("issued", "Issued"), ("complete", "Complete"), ("cancelled", "Cancelled"), ("superseded", "Superseded")], default="open", max_length=30)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("allowed_next_codes", models.JSONField(default=list)),
                ("is_initial", models.BooleanField(default=False)),
                ("allows_baseline", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "project_delivery_stage", "ordering": ["entity_type", "sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("customer_public_id", models.UUIDField(blank=True, null=True)),
                ("opportunity_public_id", models.UUIDField(blank=True, null=True)),
                ("manager_membership_public_id", models.UUIDField()),
                ("location", models.JSONField(default=dict)),
                ("planned_start_date", models.DateField(blank=True, null=True)),
                ("planned_end_date", models.DateField(blank=True, null=True)),
                ("actual_start_date", models.DateField(blank=True, null=True)),
                ("actual_end_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("approved_budget", models.DecimalField(decimal_places=4, default=decimal.Decimal("0"), max_digits=19)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("baseline_version", models.PositiveIntegerField(default=0)),
                ("baselined_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("stage", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="projects", to="projects.deliverystage")),
            ],
            options={"db_table": "project_project"},
        ),
        migrations.CreateModel(
            name="ProjectStageHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_stage_code", models.CharField(blank=True, max_length=80)),
                ("to_stage_code", models.CharField(max_length=80)),
                ("changed_by_public_id", models.UUIDField()),
                ("changed_at", models.DateTimeField()),
                ("reason_code", models.CharField(blank=True, max_length=100)),
                ("project_version", models.PositiveBigIntegerField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="stage_history", to="projects.project")),
            ],
            options={"db_table": "project_stage_history"},
        ),
        migrations.CreateModel(
            name="WbsNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="projects.wbsnode")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="wbs_nodes", to="projects.project")),
            ],
            options={"db_table": "project_wbs_node"},
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("assignee_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("planned_start_date", models.DateField(blank=True, null=True)),
                ("planned_end_date", models.DateField(blank=True, null=True)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("dependencies", models.JSONField(default=list)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tasks", to="projects.project")),
                ("stage", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tasks", to="projects.deliverystage")),
                ("wbs_node", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="tasks", to="projects.wbsnode")),
            ],
            options={"db_table": "project_task"},
        ),
        migrations.CreateModel(
            name="ProjectBaseline",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("baseline_number", models.PositiveIntegerField()),
                ("source_project_version", models.PositiveBigIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("created_by_public_id", models.UUIDField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="baselines", to="projects.project")),
            ],
            options={"db_table": "project_baseline"},
        ),
        migrations.AddConstraint(model_name="deliverystage", constraint=models.UniqueConstraint(fields=("company", "entity_type", "code"), name="prj_stage_company_code_uq")),
        migrations.AddConstraint(model_name="deliverystage", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="prj_stage_range_valid")),
        migrations.AddIndex(model_name="deliverystage", index=models.Index(fields=["company", "entity_type", "is_active", "sort_order"], name="prj_stage_active_idx")),
        migrations.AddConstraint(model_name="project", constraint=models.UniqueConstraint(fields=("company", "code"), name="prj_company_code_uq")),
        migrations.AddConstraint(model_name="project", constraint=models.CheckConstraint(condition=models.Q(("planned_end_date__isnull", True), ("planned_start_date__isnull", True), ("planned_end_date__gte", models.F("planned_start_date")), _connector="OR"), name="prj_plan_dates_valid")),
        migrations.AddConstraint(model_name="project", constraint=models.CheckConstraint(condition=models.Q(("approved_budget__gte", 0)), name="prj_budget_nonnegative")),
        migrations.AddIndex(model_name="project", index=models.Index(fields=["company", "stage", "planned_end_date"], name="prj_stage_end_idx")),
        migrations.AddIndex(model_name="project", index=models.Index(fields=["company", "manager_membership_public_id", "stage"], name="prj_manager_stage_idx")),
        migrations.AddConstraint(model_name="projectstagehistory", constraint=models.UniqueConstraint(fields=("company", "project", "project_version"), name="prj_stage_hist_version_uq")),
        migrations.AddIndex(model_name="projectstagehistory", index=models.Index(fields=["company", "project", "changed_at"], name="prj_stage_hist_lookup_idx")),
        migrations.AddConstraint(model_name="wbsnode", constraint=models.UniqueConstraint(fields=("company", "project", "code"), name="prj_wbs_code_uq")),
        migrations.AddIndex(model_name="wbsnode", index=models.Index(fields=["company", "project", "parent", "sort_order"], name="prj_wbs_tree_idx")),
        migrations.AddConstraint(model_name="projecttask", constraint=models.UniqueConstraint(fields=("company", "project", "code"), name="prj_task_code_uq")),
        migrations.AddConstraint(model_name="projecttask", constraint=models.CheckConstraint(condition=models.Q(("progress_percent__lte", 100)), name="prj_task_progress_valid")),
        migrations.AddConstraint(model_name="projecttask", constraint=models.CheckConstraint(condition=models.Q(("planned_end_date__isnull", True), ("planned_start_date__isnull", True), ("planned_end_date__gte", models.F("planned_start_date")), _connector="OR"), name="prj_task_dates_valid")),
        migrations.AddIndex(model_name="projecttask", index=models.Index(fields=["company", "project", "stage"], name="prj_task_stage_idx")),
        migrations.AddIndex(model_name="projecttask", index=models.Index(fields=["company", "assignee_membership_public_id", "stage"], name="prj_task_assignee_idx")),
        migrations.AddConstraint(model_name="projectbaseline", constraint=models.UniqueConstraint(fields=("company", "project", "baseline_number"), name="prj_baseline_number_uq")),
        migrations.AddIndex(model_name="projectbaseline", index=models.Index(fields=["company", "project", "baseline_number"], name="prj_baseline_lookup_idx")),
    ]
