from django.urls import path

from .views import (
    DeliveryStageListCreateView,
    ExecutivePortfolioView,
    GuidedWorkbenchView,
    ProjectBaselineListView,
    ProjectBaselineView,
    ProjectDesignBoardView,
    ProjectDetailView,
    ProjectEvidencePanelView,
    ProjectExperienceView,
    ProjectFromCrmOpportunityView,
    ProjectHandoverBoardView,
    ProjectListCreateView,
    ProjectProcurementFlowView,
    ProjectSiteTimelineView,
    ProjectSummaryView,
    ProjectTaskListCreateView,
    ProjectTransitionView,
    ProjectWbsListCreateView,
    TaskTransitionView,
    UniversalSearchView,
)

urlpatterns = [
    path("workbench", GuidedWorkbenchView.as_view(), name="project-guided-workbench"),
    path("executive", ExecutivePortfolioView.as_view(), name="project-executive-portfolio"),
    path("search", UniversalSearchView.as_view(), name="project-universal-search"),
    path("summary", ProjectSummaryView.as_view(), name="project-summary"),
    path("stages", DeliveryStageListCreateView.as_view(), name="project-stages"),
    path("from-crm-opportunity/<uuid:opportunity_public_id>", ProjectFromCrmOpportunityView.as_view(), name="project-from-crm-opportunity"),
    path("items", ProjectListCreateView.as_view(), name="projects"),
    path("<uuid:public_id>", ProjectDetailView.as_view(), name="project-detail"),
    path("<uuid:public_id>/experience", ProjectExperienceView.as_view(), name="project-experience"),
    path("<uuid:public_id>/design-board", ProjectDesignBoardView.as_view(), name="project-design-board"),
    path("<uuid:public_id>/site-timeline", ProjectSiteTimelineView.as_view(), name="project-site-timeline"),
    path("<uuid:public_id>/procurement-flow", ProjectProcurementFlowView.as_view(), name="project-procurement-flow"),
    path("<uuid:public_id>/handover-board", ProjectHandoverBoardView.as_view(), name="project-handover-board"),
    path("<uuid:public_id>/evidence", ProjectEvidencePanelView.as_view(), name="project-evidence-panel"),
    path(
        "<uuid:public_id>/transition",
        ProjectTransitionView.as_view(),
        name="project-transition",
    ),
    path("<uuid:public_id>/baseline", ProjectBaselineView.as_view(), name="project-baseline"),
    path(
        "<uuid:public_id>/baselines",
        ProjectBaselineListView.as_view(),
        name="project-baselines",
    ),
    path("<uuid:public_id>/wbs", ProjectWbsListCreateView.as_view(), name="project-wbs"),
    path(
        "<uuid:public_id>/tasks",
        ProjectTaskListCreateView.as_view(),
        name="project-tasks",
    ),
    path("tasks/<uuid:public_id>/transition", TaskTransitionView.as_view(), name="task-transition"),
]
