import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="PropertyPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("lease_expiry_alert_days", models.PositiveIntegerField(default=90)),
                ("invoice_grace_days", models.PositiveIntegerField(default=5)),
                ("case_response_minutes", models.PositiveIntegerField(default=240)),
                ("case_resolution_minutes", models.PositiveIntegerField(default=2880)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="property_lease_policies", to="tenant.company")),
            ],
            options={
                "db_table": "leaseops_policy",
                "indexes": [models.Index(fields=["company", "status_code"], name="lea_policy_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "version"), name="lea_policy_ver_uq"),
                    models.CheckConstraint(condition=models.Q(effective_to__isnull=True) | models.Q(effective_from__isnull=True) | models.Q(effective_to__gt=models.F("effective_from")), name="lea_policy_dates_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ManagedProperty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("property_type_code", models.CharField(default="RESIDENTIAL", max_length=60)),
                ("facility_public_id", models.UUIDField(blank=True, null=True)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("external_reference", models.CharField(blank=True, max_length=160)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("timezone", models.CharField(blank=True, max_length=80)),
                ("gross_area", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("area_unit_code", models.CharField(default="SQ_M", max_length=30)),
                ("ownership_code", models.CharField(default="OWNED", max_length=40)),
                ("status_code", models.CharField(default="ACTIVE", max_length=30)),
                ("manager_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="managed_properties", to="tenant.company")),
            ],
            options={
                "db_table": "leaseops_property",
                "indexes": [
                    models.Index(fields=["company", "status_code"], name="lea_property_status_idx"),
                    models.Index(fields=["company", "facility_public_id"], name="lea_property_fac_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="lea_property_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="TenantAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_code", models.CharField(max_length=80)),
                ("legal_name", models.CharField(max_length=240)),
                ("display_name", models.CharField(max_length=240)),
                ("tenant_type_code", models.CharField(default="ORGANIZATION", max_length=40)),
                ("contact_name", models.CharField(blank=True, max_length=160)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("tax_reference", models.CharField(blank=True, max_length=120)),
                ("billing_address", models.JSONField(blank=True, default=dict)),
                ("status_code", models.CharField(default="ACTIVE", max_length=30)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tenant_accounts", to="tenant.company")),
            ],
            options={
                "db_table": "leaseops_tenant",
                "indexes": [models.Index(fields=["company", "status_code"], name="lea_tenant_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "account_code"), name="lea_tenant_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="LeaseableUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("unit_type_code", models.CharField(default="APARTMENT", max_length=60)),
                ("floor_reference", models.CharField(blank=True, max_length=80)),
                ("area", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("area_unit_code", models.CharField(default="SQ_M", max_length=30)),
                ("bedroom_count", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("parking_count", models.PositiveSmallIntegerField(default=0)),
                ("market_rent", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("status_code", models.CharField(default="AVAILABLE", max_length=30)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leaseable_units", to="tenant.company")),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="units", to="leaseops.managedproperty")),
            ],
            options={
                "db_table": "leaseops_unit",
                "indexes": [
                    models.Index(fields=["company", "status_code"], name="lea_unit_status_idx"),
                    models.Index(fields=["company", "property", "unit_type_code"], name="lea_unit_type_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("property", "code"), name="lea_unit_code_uq"),
                    models.CheckConstraint(condition=models.Q(market_rent__isnull=True) | models.Q(market_rent__gte=0), name="lea_unit_rent_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaseAgreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lease_number", models.CharField(max_length=80)),
                ("lease_type_code", models.CharField(default="STANDARD", max_length=40)),
                ("start_on", models.DateField()),
                ("end_on", models.DateField()),
                ("billing_cycle_code", models.CharField(default="MONTHLY", max_length=30)),
                ("base_rent", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("security_deposit", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("escalation_percent", models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ("escalation_frequency_months", models.PositiveIntegerField(default=12)),
                ("notice_days", models.PositiveIntegerField(default=30)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("terminated_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lease_agreements", to="tenant.company")),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leases", to="leaseops.managedproperty")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leases", to="leaseops.tenantaccount")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leases", to="leaseops.leaseableunit")),
            ],
            options={
                "db_table": "leaseops_lease",
                "indexes": [
                    models.Index(fields=["company", "status_code", "end_on"], name="lea_lease_status_idx"),
                    models.Index(fields=["company", "tenant", "status_code"], name="lea_lease_tenant_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "lease_number"), name="lea_lease_no_uq"),
                    models.CheckConstraint(condition=models.Q(end_on__gt=models.F("start_on")), name="lea_lease_dates_ck"),
                    models.CheckConstraint(condition=models.Q(base_rent__gte=0), name="lea_lease_rent_ck"),
                    models.CheckConstraint(condition=models.Q(security_deposit__gte=0), name="lea_lease_deposit_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaseCharge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("charge_code", models.CharField(max_length=80)),
                ("charge_type_code", models.CharField(default="RENT", max_length=60)),
                ("description", models.CharField(max_length=240)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("frequency_code", models.CharField(default="MONTHLY", max_length=30)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("tax_code", models.CharField(blank=True, max_length=60)),
                ("recoverable", models.BooleanField(default=True)),
                ("status_code", models.CharField(default="ACTIVE", max_length=30)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lease_charges", to="tenant.company")),
                ("lease", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="charges", to="leaseops.leaseagreement")),
            ],
            options={
                "db_table": "leaseops_charge",
                "indexes": [models.Index(fields=["company", "lease", "status_code"], name="lea_charge_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("lease", "charge_code", "effective_from"), name="lea_charge_period_uq"),
                    models.CheckConstraint(condition=models.Q(amount__gte=0), name="lea_charge_amount_ck"),
                    models.CheckConstraint(condition=models.Q(effective_to__isnull=True) | models.Q(effective_to__gte=models.F("effective_from")), name="lea_charge_dates_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OccupancyRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("occupant_reference", models.CharField(blank=True, max_length=200)),
                ("move_in_on", models.DateField(blank=True, null=True)),
                ("move_out_on", models.DateField(blank=True, null=True)),
                ("occupant_count", models.PositiveIntegerField(default=1)),
                ("key_handover_evidence", models.JSONField(blank=True, default=dict)),
                ("meter_readings", models.JSONField(blank=True, default=dict)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("captured_by_public_id", models.UUIDField()),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="occupancy_records", to="tenant.company")),
                ("lease", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="occupancies", to="leaseops.leaseagreement")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="occupancies", to="leaseops.leaseableunit")),
            ],
            options={
                "db_table": "leaseops_occupancy",
                "indexes": [
                    models.Index(fields=["company", "status_code"], name="lea_occ_status_idx"),
                    models.Index(fields=["company", "unit", "move_in_on"], name="lea_occ_unit_idx"),
                ],
                "constraints": [models.CheckConstraint(condition=models.Q(move_out_on__isnull=True) | models.Q(move_in_on__isnull=True) | models.Q(move_out_on__gte=models.F("move_in_on")), name="lea_occ_dates_ck")],
            },
        ),
        migrations.CreateModel(
            name="RentInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(max_length=80)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("paid_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("external_finance_reference", models.CharField(blank=True, max_length=200)),
                ("created_by_public_id", models.UUIDField()),
                ("issued_by_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rent_invoices", to="tenant.company")),
                ("lease", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="leaseops.leaseagreement")),
            ],
            options={
                "db_table": "leaseops_invoice",
                "indexes": [
                    models.Index(fields=["company", "status_code", "due_date"], name="lea_inv_status_idx"),
                    models.Index(fields=["company", "lease", "period_start"], name="lea_inv_lease_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "invoice_number"), name="lea_invoice_no_uq"),
                    models.CheckConstraint(condition=models.Q(period_end__gte=models.F("period_start")), name="lea_inv_period_ck"),
                    models.CheckConstraint(condition=models.Q(due_date__gte=models.F("issue_date")), name="lea_inv_due_ck"),
                    models.CheckConstraint(condition=models.Q(gross_amount__gte=0), name="lea_inv_gross_ck"),
                    models.CheckConstraint(condition=models.Q(tax_amount__gte=0), name="lea_inv_tax_ck"),
                    models.CheckConstraint(condition=models.Q(paid_amount__gte=0), name="lea_inv_paid_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TenantExperienceCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_number", models.CharField(max_length=80)),
                ("category_code", models.CharField(default="SERVICE", max_length=60)),
                ("priority_code", models.CharField(default="NORMAL", max_length=30)),
                ("channel_code", models.CharField(default="PORTAL", max_length=30)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("status_code", models.CharField(default="NEW", max_length=30)),
                ("assigned_to_public_id", models.UUIDField(blank=True, null=True)),
                ("response_due_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_due_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("satisfaction_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tenant_experience_cases", to="tenant.company")),
                ("property", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="experience_cases", to="leaseops.managedproperty")),
                ("tenant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="experience_cases", to="leaseops.tenantaccount")),
                ("unit", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="experience_cases", to="leaseops.leaseableunit")),
            ],
            options={
                "db_table": "leaseops_case",
                "indexes": [
                    models.Index(fields=["company", "status_code", "priority_code"], name="lea_case_status_idx"),
                    models.Index(fields=["company", "resolution_due_at"], name="lea_case_due_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "case_number"), name="lea_case_no_uq"),
                    models.CheckConstraint(condition=models.Q(satisfaction_score__isnull=True) | (models.Q(satisfaction_score__gte=1) & models.Q(satisfaction_score__lte=5)), name="lea_case_score_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LeaseLifecycleEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type_code", models.CharField(max_length=60)),
                ("occurred_at", models.DateTimeField()),
                ("from_status_code", models.CharField(blank=True, max_length=30)),
                ("to_status_code", models.CharField(blank=True, max_length=30)),
                ("summary", models.CharField(max_length=300)),
                ("amount", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("currency_code", models.CharField(blank=True, max_length=3)),
                ("event_metadata", models.JSONField(blank=True, default=dict)),
                ("recorded_by_public_id", models.UUIDField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lease_lifecycle_events", to="tenant.company")),
                ("lease", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lifecycle_events", to="leaseops.leaseagreement")),
            ],
            options={
                "db_table": "leaseops_event",
                "indexes": [
                    models.Index(fields=["company", "lease", "occurred_at"], name="lea_event_lease_idx"),
                    models.Index(fields=["company", "event_type_code"], name="lea_event_type_idx"),
                ],
            },
        ),
    ]
