# Generated for MPSqre Build360 CRM Phase 4.
import decimal
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="PipelineStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(choices=[("lead", "Lead"), ("opportunity", "Opportunity")], max_length=30)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=160)),
                ("outcome", models.CharField(choices=[("open", "Open"), ("qualified", "Qualified"), ("disqualified", "Disqualified"), ("converted", "Converted"), ("won", "Won"), ("lost", "Lost")], default="open", max_length=30)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("probability_percent", models.PositiveSmallIntegerField(default=0)),
                ("allowed_next_codes", models.JSONField(default=list)),
                ("is_initial", models.BooleanField(default=False)),
                ("allows_conversion", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "crm_pipeline_stage", "ordering": ["entity_type", "sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("kind", models.CharField(choices=[("organization", "Organization"), ("person", "Person")], max_length=30)),
                ("display_name", models.CharField(max_length=250)),
                ("legal_name", models.CharField(blank=True, max_length=250)),
                ("normalized_name", models.CharField(max_length=250)),
                ("external_reference", models.CharField(blank=True, max_length=120)),
                ("source_code", models.CharField(blank=True, max_length=80)),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive"), ("archived", "Archived")], default="active", max_length=30)),
                ("owner_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "crm_customer"},
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(blank=True, max_length=120)),
                ("job_title", models.CharField(blank=True, max_length=160)),
                ("email_ciphertext", models.TextField(blank=True)),
                ("email_blind_index", models.CharField(blank=True, max_length=64)),
                ("phone_ciphertext", models.TextField(blank=True)),
                ("phone_blind_index", models.CharField(blank=True, max_length=64)),
                ("email_last_four", models.CharField(blank=True, max_length=4)),
                ("phone_last_four", models.CharField(blank=True, max_length=4)),
                ("consent_status", models.CharField(choices=[("unknown", "Unknown"), ("granted", "Granted"), ("withdrawn", "Withdrawn")], default="unknown", max_length=30)),
                ("preferred_channel_code", models.CharField(blank=True, max_length=40)),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="contacts", to="crm.customer")),
            ],
            options={"db_table": "crm_contact"},
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("source_code", models.CharField(blank=True, max_length=80)),
                ("owner_membership_public_id", models.UUIDField()),
                ("estimated_value", models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("next_follow_up_at", models.DateTimeField(blank=True, null=True)),
                ("qualified_at", models.DateTimeField(blank=True, null=True)),
                ("disqualified_at", models.DateTimeField(blank=True, null=True)),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_reason_code", models.CharField(blank=True, max_length=100)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="leads", to="crm.customer")),
                ("primary_contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="leads", to="crm.contact")),
                ("stage", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="leads", to="crm.pipelinestage")),
            ],
            options={"db_table": "crm_lead"},
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=250)),
                ("owner_membership_public_id", models.UUIDField()),
                ("amount", models.DecimalField(decimal_places=4, default=decimal.Decimal("0"), max_digits=19)),
                ("currency", models.CharField(max_length=3)),
                ("expected_close_date", models.DateField(blank=True, null=True)),
                ("probability_percent", models.PositiveSmallIntegerField(default=0)),
                ("won_at", models.DateTimeField(blank=True, null=True)),
                ("lost_at", models.DateTimeField(blank=True, null=True)),
                ("close_reason_code", models.CharField(blank=True, max_length=100)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="opportunities", to="crm.customer")),
                ("primary_contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="opportunities", to="crm.contact")),
                ("source_lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="opportunities", to="crm.lead")),
                ("stage", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="opportunities", to="crm.pipelinestage")),
            ],
            options={"db_table": "crm_opportunity"},
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity_type", models.CharField(choices=[("note", "Note"), ("call", "Call"), ("meeting", "Meeting"), ("site_visit", "Site visit"), ("follow_up", "Follow-up"), ("email", "Email")], max_length=30)),
                ("status", models.CharField(choices=[("planned", "Planned"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="planned", max_length=30)),
                ("subject", models.CharField(max_length=250)),
                ("notes", models.TextField(blank=True)),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("owner_membership_public_id", models.UUIDField()),
                ("created_by_public_id", models.UUIDField()),
                ("location", models.JSONField(default=dict)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("customer", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="activities", to="crm.customer")),
                ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="activities", to="crm.lead")),
                ("opportunity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="activities", to="crm.opportunity")),
            ],
            options={"db_table": "crm_activity"},
        ),
        migrations.CreateModel(
            name="StageHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(choices=[("lead", "Lead"), ("opportunity", "Opportunity")], max_length=30)),
                ("entity_public_id", models.UUIDField()),
                ("from_stage_code", models.CharField(blank=True, max_length=80)),
                ("to_stage_code", models.CharField(max_length=80)),
                ("changed_by_public_id", models.UUIDField()),
                ("changed_at", models.DateTimeField()),
                ("reason_code", models.CharField(blank=True, max_length=100)),
                ("entity_version", models.PositiveBigIntegerField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "crm_stage_history"},
        ),
        migrations.CreateModel(
            name="ConversionSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_version", models.PositiveBigIntegerField()),
                ("snapshot", models.JSONField(default=dict)),
                ("converted_by_public_id", models.UUIDField()),
                ("converted_at", models.DateTimeField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("customer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="crm.customer")),
                ("lead", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="conversion_snapshot", to="crm.lead")),
                ("opportunity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="crm.opportunity")),
            ],
            options={"db_table": "crm_conversion_snapshot"},
        ),
        migrations.AddConstraint(model_name="pipelinestage", constraint=models.UniqueConstraint(fields=("company", "entity_type", "code"), name="crm_stage_company_code_uq")),
        migrations.AddConstraint(model_name="pipelinestage", constraint=models.CheckConstraint(condition=models.Q(("probability_percent__lte", 100)), name="crm_stage_prob_valid")),
        migrations.AddConstraint(model_name="pipelinestage", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="crm_stage_range_valid")),
        migrations.AddIndex(model_name="pipelinestage", index=models.Index(fields=["company", "entity_type", "is_active", "sort_order"], name="crm_stage_active_idx")),
        migrations.AddConstraint(model_name="customer", constraint=models.UniqueConstraint(condition=models.Q(("external_reference", ""), _negated=True), fields=("company", "external_reference"), name="crm_customer_extref_uq")),
        migrations.AddIndex(model_name="customer", index=models.Index(fields=["company", "status", "normalized_name"], name="crm_customer_lookup_idx")),
        migrations.AddIndex(model_name="customer", index=models.Index(fields=["company", "owner_membership_public_id", "status"], name="crm_customer_owner_idx")),
        migrations.AddIndex(model_name="contact", index=models.Index(fields=["company", "email_blind_index"], name="crm_contact_email_idx")),
        migrations.AddIndex(model_name="contact", index=models.Index(fields=["company", "phone_blind_index"], name="crm_contact_phone_idx")),
        migrations.AddIndex(model_name="contact", index=models.Index(fields=["company", "customer", "is_active"], name="crm_contact_customer_idx")),
        migrations.AddIndex(model_name="lead", index=models.Index(fields=["company", "stage", "next_follow_up_at"], name="crm_lead_stage_follow_idx")),
        migrations.AddIndex(model_name="lead", index=models.Index(fields=["company", "owner_membership_public_id", "stage"], name="crm_lead_owner_idx")),
        migrations.AddIndex(model_name="lead", index=models.Index(fields=["company", "created_at"], name="crm_lead_created_idx")),
        migrations.AddConstraint(model_name="opportunity", constraint=models.CheckConstraint(condition=models.Q(("probability_percent__lte", 100)), name="crm_opp_prob_valid")),
        migrations.AddConstraint(model_name="opportunity", constraint=models.UniqueConstraint(condition=models.Q(("source_lead__isnull", False)), fields=("company", "source_lead"), name="crm_opp_source_lead_uq")),
        migrations.AddIndex(model_name="opportunity", index=models.Index(fields=["company", "stage", "expected_close_date"], name="crm_opp_stage_close_idx")),
        migrations.AddIndex(model_name="opportunity", index=models.Index(fields=["company", "owner_membership_public_id", "stage"], name="crm_opp_owner_idx")),
        migrations.AddConstraint(model_name="activity", constraint=models.CheckConstraint(condition=models.Q(("customer__isnull", False), ("lead__isnull", False), ("opportunity__isnull", False), _connector="OR"), name="crm_activity_parent_required")),
        migrations.AddIndex(model_name="activity", index=models.Index(fields=["company", "owner_membership_public_id", "scheduled_for"], name="crm_activity_owner_idx")),
        migrations.AddIndex(model_name="activity", index=models.Index(fields=["company", "status", "scheduled_for"], name="crm_activity_due_idx")),
        migrations.AddConstraint(model_name="stagehistory", constraint=models.UniqueConstraint(fields=("company", "entity_type", "entity_public_id", "entity_version"), name="crm_stage_hist_version_uq")),
        migrations.AddIndex(model_name="stagehistory", index=models.Index(fields=["company", "entity_type", "entity_public_id", "changed_at"], name="crm_stage_hist_lookup_idx")),
        migrations.AddConstraint(model_name="conversionsnapshot", constraint=models.UniqueConstraint(fields=("company", "lead"), name="crm_conversion_lead_uq")),
    ]
