import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial"), ("leaseops", "0003_seed_defaults")]

    operations = [
        migrations.CreateModel(
            name="SalesPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("reservation_expiry_hours", models.PositiveIntegerField(default=72)),
                ("collection_grace_days", models.PositiveIntegerField(default=7)),
                ("handover_alert_days", models.PositiveIntegerField(default=30)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_sales_policies", to="tenant.company")),
            ],
            options={
                "db_table": "salesops_policy",
                "indexes": [models.Index(fields=["company", "status_code"], name="sal_policy_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "version"), name="sal_policy_ver_uq"),
                    models.CheckConstraint(condition=models.Q(effective_to__isnull=True) | models.Q(effective_from__isnull=True) | models.Q(effective_to__gt=models.F("effective_from")), name="sal_policy_dates_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DevelopmentInventory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("property_public_id", models.UUIDField(blank=True, null=True)),
                ("development_type_code", models.CharField(default="RESIDENTIAL", max_length=60)),
                ("location", models.JSONField(blank=True, default=dict)),
                ("launch_on", models.DateField(blank=True, null=True)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("status_code", models.CharField(default="PLANNING", max_length=30)),
                ("manager_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_sales_inventories", to="tenant.company")),
            ],
            options={
                "db_table": "salesops_inventory",
                "indexes": [
                    models.Index(fields=["company", "status_code"], name="sal_inventory_status_idx"),
                    models.Index(fields=["company", "project_public_id"], name="sal_inventory_proj_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="sal_inventory_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="BuyerAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_code", models.CharField(max_length=80)),
                ("legal_name", models.CharField(max_length=240)),
                ("display_name", models.CharField(max_length=240)),
                ("buyer_type_code", models.CharField(default="INDIVIDUAL", max_length=40)),
                ("contact_name", models.CharField(blank=True, max_length=160)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("contact_phone", models.CharField(blank=True, max_length=40)),
                ("tax_reference", models.CharField(blank=True, max_length=120)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("crm_party_public_id", models.UUIDField(blank=True, null=True)),
                ("status_code", models.CharField(default="ACTIVE", max_length=30)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_sales_buyers", to="tenant.company")),
            ],
            options={
                "db_table": "salesops_buyer",
                "indexes": [models.Index(fields=["company", "status_code"], name="sal_buyer_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "account_code"), name="sal_buyer_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="SaleableUnit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("unit_type_code", models.CharField(default="APARTMENT", max_length=60)),
                ("tower_reference", models.CharField(blank=True, max_length=80)),
                ("floor_reference", models.CharField(blank=True, max_length=80)),
                ("carpet_area", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("saleable_area", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("area_unit_code", models.CharField(default="SQ_M", max_length=30)),
                ("list_price", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("tax_code", models.CharField(blank=True, max_length=60)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_saleable_units", to="tenant.company")),
                ("inventory", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="units", to="salesops.developmentinventory")),
            ],
            options={
                "db_table": "salesops_unit",
                "indexes": [
                    models.Index(fields=["company", "status_code"], name="sal_unit_status_idx"),
                    models.Index(fields=["company", "inventory", "unit_type_code"], name="sal_unit_type_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("inventory", "code"), name="sal_unit_code_uq"),
                    models.CheckConstraint(condition=models.Q(list_price__gte=0), name="sal_unit_price_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnitReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reservation_number", models.CharField(max_length=80)),
                ("reserved_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                ("token_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("status_code", models.CharField(default="ACTIVE", max_length=30)),
                ("source_code", models.CharField(default="DIRECT", max_length=60)),
                ("created_by_public_id", models.UUIDField()),
                ("converted_booking_public_id", models.UUIDField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("buyer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="salesops.buyeraccount")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_unit_reservations", to="tenant.company")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reservations", to="salesops.saleableunit")),
            ],
            options={
                "db_table": "salesops_reservation",
                "indexes": [
                    models.Index(fields=["company", "status_code", "expires_at"], name="sal_reservation_status_idx"),
                    models.Index(fields=["company", "unit", "status_code"], name="sal_reservation_unit_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "reservation_number"), name="sal_reservation_no_uq"),
                    models.CheckConstraint(condition=models.Q(expires_at__gt=models.F("reserved_at")), name="sal_reservation_dates_ck"),
                    models.CheckConstraint(condition=models.Q(token_amount__gte=0), name="sal_reservation_token_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BookingAgreement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking_number", models.CharField(max_length=80)),
                ("booking_date", models.DateField()),
                ("agreement_date", models.DateField(blank=True, null=True)),
                ("base_price", models.DecimalField(decimal_places=2, max_digits=18)),
                ("discount_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("other_charges", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("total_consideration", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("buyer", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bookings", to="salesops.buyeraccount")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_bookings", to="tenant.company")),
                ("reservation", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="bookings", to="salesops.unitreservation")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bookings", to="salesops.saleableunit")),
            ],
            options={
                "db_table": "salesops_booking",
                "indexes": [
                    models.Index(fields=["company", "status_code", "booking_date"], name="sal_booking_status_idx"),
                    models.Index(fields=["company", "buyer", "status_code"], name="sal_booking_buyer_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "booking_number"), name="sal_booking_no_uq"),
                    models.CheckConstraint(condition=models.Q(base_price__gte=0), name="sal_booking_base_ck"),
                    models.CheckConstraint(condition=models.Q(discount_amount__gte=0), name="sal_booking_discount_ck"),
                    models.CheckConstraint(condition=models.Q(tax_amount__gte=0), name="sal_booking_tax_ck"),
                    models.CheckConstraint(condition=models.Q(other_charges__gte=0), name="sal_booking_other_ck"),
                    models.CheckConstraint(condition=models.Q(total_consideration__gte=0), name="sal_booking_total_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentMilestone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField()),
                ("milestone_code", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=240)),
                ("due_on", models.DateField()),
                ("percentage", models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("paid_amount", models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ("status_code", models.CharField(default="SCHEDULED", max_length=30)),
                ("version", models.PositiveIntegerField(default=1)),
                ("booking", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payment_milestones", to="salesops.bookingagreement")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_payment_milestones", to="tenant.company")),
            ],
            options={
                "db_table": "salesops_milestone",
                "indexes": [
                    models.Index(fields=["company", "status_code", "due_on"], name="sal_milestone_due_idx"),
                    models.Index(fields=["company", "booking", "sequence"], name="sal_milestone_book_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("booking", "sequence"), name="sal_milestone_seq_uq"),
                    models.UniqueConstraint(fields=("booking", "milestone_code"), name="sal_milestone_code_uq"),
                    models.CheckConstraint(condition=models.Q(amount__gte=0), name="sal_milestone_amt_ck"),
                    models.CheckConstraint(condition=models.Q(tax_amount__gte=0), name="sal_milestone_tax_ck"),
                    models.CheckConstraint(condition=models.Q(paid_amount__gte=0), name="sal_milestone_paid_ck"),
                    models.CheckConstraint(condition=models.Q(percentage__isnull=True) | (models.Q(percentage__gte=0) & models.Q(percentage__lte=100)), name="sal_milestone_pct_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectionReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("receipt_number", models.CharField(max_length=80)),
                ("receipt_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("payment_method_code", models.CharField(default="BANK_TRANSFER", max_length=40)),
                ("payment_reference", models.CharField(blank=True, max_length=160)),
                ("finance_reference", models.CharField(blank=True, max_length=160)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("confirmed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("booking", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="receipts", to="salesops.bookingagreement")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_collection_receipts", to="tenant.company")),
                ("milestone", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="receipts", to="salesops.paymentmilestone")),
            ],
            options={
                "db_table": "salesops_receipt",
                "indexes": [
                    models.Index(fields=["company", "status_code", "receipt_date"], name="sal_receipt_status_idx"),
                    models.Index(fields=["company", "booking", "receipt_date"], name="sal_receipt_book_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "receipt_number"), name="sal_receipt_no_uq"),
                    models.CheckConstraint(condition=models.Q(amount__gt=0), name="sal_receipt_amt_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrokerCommission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("broker_reference", models.CharField(max_length=160)),
                ("broker_name", models.CharField(max_length=240)),
                ("commission_percent", models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ("commission_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("booking", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="broker_commissions", to="salesops.bookingagreement")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_broker_commissions", to="tenant.company")),
            ],
            options={
                "db_table": "salesops_commission",
                "indexes": [models.Index(fields=["company", "status_code"], name="sal_commission_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("booking", "broker_reference"), name="sal_commission_broker_uq"),
                    models.CheckConstraint(condition=models.Q(commission_percent__gte=0) & models.Q(commission_percent__lte=100), name="sal_commission_pct_ck"),
                    models.CheckConstraint(condition=models.Q(commission_amount__gte=0), name="sal_commission_amt_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomerHandover",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("planned_on", models.DateField(blank=True, null=True)),
                ("offered_on", models.DateField(blank=True, null=True)),
                ("possession_on", models.DateField(blank=True, null=True)),
                ("checklist", models.JSONField(blank=True, default=dict)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("open_defect_count", models.PositiveIntegerField(default=0)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("booking", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="handover", to="salesops.bookingagreement")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="development_customer_handovers", to="tenant.company")),
                ("unit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="customer_handovers", to="salesops.saleableunit")),
            ],
            options={
                "db_table": "salesops_handover",
                "indexes": [
                    models.Index(fields=["company", "status_code", "planned_on"], name="sal_handover_status_idx"),
                    models.Index(fields=["company", "unit"], name="sal_handover_unit_idx"),
                ],
            },
        ),
    ]
