# Generated for MPSqre Build360 Phase 10.
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="ImportTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("destination_code", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("schema", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "dataops_import_template",
                "ordering": ["name", "-version"],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code", "version"), name="dop_template_version_uq"),
                    models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("company", "code"), name="dop_template_active_uq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_name", models.CharField(max_length=240)),
                ("source_sha256", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("status", models.CharField(choices=[("uploaded", "Uploaded"), ("validated", "Validated"), ("invalid", "Invalid"), ("committing", "Committing"), ("committed", "Committed"), ("partial", "Partially committed"), ("failed", "Failed"), ("cancelled", "Cancelled")], default="uploaded", max_length=20)),
                ("requested_by_public_id", models.UUIDField()),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("valid_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                ("committed_rows", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("result_summary", models.JSONField(default=dict)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="jobs", to="dataops.importtemplate")),
            ],
            options={
                "db_table": "dataops_import_job",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company", "status", "created_at"], name="dop_job_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "idempotency_key"), name="dop_job_idempotency_uq")],
            },
        ),
        migrations.CreateModel(
            name="ImportStagingRow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("row_number", models.PositiveIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("normalized_payload", models.JSONField(default=dict)),
                ("row_sha256", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("valid", "Valid"), ("error", "Error"), ("committed", "Committed"), ("skipped", "Skipped")], default="valid", max_length=20)),
                ("target_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="rows", to="dataops.importjob")),
            ],
            options={
                "db_table": "dataops_import_row",
                "ordering": ["row_number"],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "job", "row_number"), name="dop_row_number_uq"),
                    models.UniqueConstraint(fields=("company", "job", "row_sha256"), name="dop_row_hash_uq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ImportRowError",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(blank=True, max_length=120)),
                ("error_code", models.CharField(max_length=100)),
                ("message", models.CharField(max_length=500)),
                ("masked_value", models.CharField(blank=True, max_length=200)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("row", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="errors", to="dataops.importstagingrow")),
            ],
            options={
                "db_table": "dataops_import_row_error",
                "indexes": [models.Index(fields=["company", "row", "error_code"], name="dop_row_error_idx")],
            },
        ),
        migrations.CreateModel(
            name="PrivacyRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_number", models.CharField(max_length=80)),
                ("request_type", models.CharField(choices=[("access", "Access"), ("rectification", "Rectification"), ("deletion", "Deletion"), ("restriction", "Restriction")], max_length=30)),
                ("subject_type", models.CharField(max_length=80)),
                ("subject_public_id", models.UUIDField()),
                ("status", models.CharField(choices=[("received", "Received"), ("verifying", "Verifying identity"), ("in_progress", "In progress"), ("completed", "Completed"), ("rejected", "Rejected"), ("cancelled", "Cancelled")], default="received", max_length=20)),
                ("requested_by_public_id", models.UUIDField()),
                ("assigned_to_public_id", models.UUIDField(blank=True, null=True)),
                ("due_at", models.DateTimeField()),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_summary", models.TextField(blank=True)),
                ("reason_code", models.CharField(blank=True, max_length=100)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "dataops_privacy_request",
                "indexes": [
                    models.Index(fields=["company", "status", "due_at"], name="dop_privacy_due_idx"),
                    models.Index(fields=["company", "subject_type", "subject_public_id"], name="dop_privacy_subject_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("company", "request_number"), name="dop_privacy_number_uq")],
            },
        ),
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_type", models.CharField(max_length=120)),
                ("retention_days", models.PositiveIntegerField()),
                ("legal_hold_default", models.BooleanField(default=False)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "dataops_retention_policy",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "record_type", "version"), name="dop_retention_version_uq"),
                    models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("company", "record_type"), name="dop_retention_active_uq"),
                    models.CheckConstraint(condition=models.Q(("retention_days__gte", 1)), name="dop_retention_days_ok"),
                    models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="dop_retention_range_ok"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecoveryVerification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=120)),
                ("scope", models.CharField(choices=[("backup", "Backup"), ("restore", "Restore"), ("rollback", "Rollback")], max_length=20)),
                ("status", models.CharField(choices=[("planned", "Planned"), ("running", "Running"), ("passed", "Passed"), ("failed", "Failed")], default="planned", max_length=20)),
                ("target_rpo_minutes", models.PositiveIntegerField()),
                ("measured_rpo_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("target_rto_minutes", models.PositiveIntegerField()),
                ("measured_rto_minutes", models.PositiveIntegerField(blank=True, null=True)),
                ("evidence_summary", models.TextField(blank=True)),
                ("performed_by_public_id", models.UUIDField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "dataops_recovery_verification",
                "indexes": [models.Index(fields=["company", "status", "created_at"], name="dop_recovery_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "reference"), name="dop_recovery_reference_uq")],
            },
        ),
    ]
