# Generated for MPSqre Build360 Phase 22 Workforce Planning.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkforcePolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(max_length=80)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(default=dict)),
                ("change_note", models.CharField(blank=True, max_length=500)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_policy_versions", to="tenant.company")),
            ],
            options={"db_table": "workforce_policy_version"},
        ),
        migrations.CreateModel(
            name="SkillDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("category_code", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("proficiency_scale", models.JSONField(default=list)),
                ("is_certification", models.BooleanField(default=False)),
                ("default_validity_days", models.PositiveIntegerField(blank=True, null=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("configuration", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_skill_definitions", to="tenant.company")),
            ],
            options={"db_table": "workforce_skill_definition"},
        ),
        migrations.CreateModel(
            name="WorkforcePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("status_code", models.CharField(max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("owner_membership_public_id", models.UUIDField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_plans", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="plans", to="workforceops.workforcepolicyversion")),
            ],
            options={"db_table": "workforce_plan"},
        ),
        migrations.CreateModel(
            name="WorkforceDemand",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("demand_code", models.CharField(max_length=100)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("location_public_id", models.UUIDField(blank=True, null=True)),
                ("cost_center_code", models.CharField(blank=True, max_length=100)),
                ("role_code", models.CharField(max_length=100)),
                ("employment_type_code", models.CharField(blank=True, max_length=80)),
                ("priority_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("quantity_required", models.PositiveIntegerField()),
                ("quantity_filled", models.PositiveIntegerField(default=0)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("estimated_cost", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("skill_requirements", models.JSONField(default=list)),
                ("configuration", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_demands", to="tenant.company")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="demands", to="workforceops.workforceplan")),
            ],
            options={"db_table": "workforce_demand"},
        ),
        migrations.CreateModel(
            name="WorkforceAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_public_id", models.UUIDField()),
                ("assignment_status_code", models.CharField(max_length=80)),
                ("allocation_percent", models.DecimalField(decimal_places=2, max_digits=5)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("source_reference", models.CharField(blank=True, max_length=150)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_assignments", to="tenant.company")),
                ("demand", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assignments", to="workforceops.workforcedemand")),
            ],
            options={"db_table": "workforce_assignment"},
        ),
        migrations.CreateModel(
            name="EmployeeSkillCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_public_id", models.UUIDField()),
                ("proficiency_code", models.CharField(max_length=80)),
                ("credential_reference", models.CharField(blank=True, max_length=150)),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("verification_status_code", models.CharField(max_length=80)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("evidence_object_key", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_credentials", to="tenant.company")),
                ("skill", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="employee_credentials", to="workforceops.skilldefinition")),
            ],
            options={"db_table": "workforce_employee_credential"},
        ),
        migrations.CreateModel(
            name="WorkforceApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_code", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("requested_from_membership_public_id", models.UUIDField()),
                ("requested_by_public_id", models.UUIDField()),
                ("requested_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by_public_id", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_code", models.CharField(blank=True, max_length=80)),
                ("decision_reason", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_approvals", to="tenant.company")),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approvals", to="workforceops.workforceplan")),
            ],
            options={"db_table": "workforce_approval"},
        ),
        migrations.CreateModel(
            name="WorkforceRisk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_public_id", models.UUIDField(blank=True, null=True)),
                ("risk_code", models.CharField(max_length=100)),
                ("severity_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("message", models.CharField(max_length=1000)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_to_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("resolution_note", models.CharField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_risks", to="tenant.company")),
                ("demand", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="risks", to="workforceops.workforcedemand")),
                ("plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="risks", to="workforceops.workforceplan")),
            ],
            options={"db_table": "workforce_risk"},
        ),
        migrations.CreateModel(
            name="WorkforceExportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("export_type_code", models.CharField(max_length=100)),
                ("provider_code", models.CharField(blank=True, max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("object_key", models.CharField(blank=True, max_length=500)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("requested_by_public_id", models.UUIDField()),
                ("requested_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="workforce_export_batches", to="tenant.company")),
                ("plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="export_batches", to="workforceops.workforceplan")),
            ],
            options={"db_table": "workforce_export_batch"},
        ),
        migrations.AddConstraint(model_name="workforcepolicyversion", constraint=models.UniqueConstraint(fields=("company", "code", "version"), name="wkfpol_company_code_ver_uq")),
        migrations.AddConstraint(model_name="workforcepolicyversion", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="wkfpol_effective_range_ck")),
        migrations.AddConstraint(model_name="workforcepolicyversion", constraint=models.CheckConstraint(condition=models.Q(("retired_at__isnull", True), ("published_at__isnull", False), _connector="OR"), name="wkfpol_retired_publish_ck")),
        migrations.AddIndex(model_name="workforcepolicyversion", index=models.Index(fields=["company", "code", "status_code"], name="wkfpol_company_status_idx")),
        migrations.AddIndex(model_name="workforcepolicyversion", index=models.Index(fields=["company", "effective_from", "effective_to"], name="wkfpol_effective_idx")),
        migrations.AddConstraint(model_name="skilldefinition", constraint=models.UniqueConstraint(fields=("company", "code", "version"), name="wskill_company_code_ver_uq")),
        migrations.AddConstraint(model_name="skilldefinition", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="wskill_effective_range_ck")),
        migrations.AddIndex(model_name="skilldefinition", index=models.Index(fields=["company", "code", "is_active"], name="wskill_lookup_idx")),
        migrations.AddIndex(model_name="skilldefinition", index=models.Index(fields=["company", "category_code", "is_active"], name="wskill_category_idx")),
        migrations.AddConstraint(model_name="workforceplan", constraint=models.UniqueConstraint(fields=("company", "code"), name="wplan_company_code_uq")),
        migrations.AddConstraint(model_name="workforceplan", constraint=models.CheckConstraint(condition=models.Q(("ends_on__gte", models.F("starts_on"))), name="wplan_date_range_ck")),
        migrations.AddIndex(model_name="workforceplan", index=models.Index(fields=["company", "status_code", "created_at"], name="wplan_company_status_idx")),
        migrations.AddIndex(model_name="workforceplan", index=models.Index(fields=["company", "starts_on", "ends_on"], name="wplan_company_dates_idx")),
        migrations.AddConstraint(model_name="workforcedemand", constraint=models.UniqueConstraint(fields=("plan", "demand_code"), name="wdemand_plan_code_uq")),
        migrations.AddConstraint(model_name="workforcedemand", constraint=models.CheckConstraint(condition=models.Q(("quantity_required__gte", 1), ("quantity_filled__lte", models.F("quantity_required"))), name="wdemand_qty_valid_ck")),
        migrations.AddConstraint(model_name="workforcedemand", constraint=models.CheckConstraint(condition=models.Q(("ends_on__gte", models.F("starts_on"))), name="wdemand_date_range_ck")),
        migrations.AddConstraint(model_name="workforcedemand", constraint=models.CheckConstraint(condition=models.Q(("estimated_cost__gte", 0)), name="wdemand_cost_nonneg_ck")),
        migrations.AddIndex(model_name="workforcedemand", index=models.Index(fields=["company", "status_code", "priority_code"], name="wdemand_status_prio_idx")),
        migrations.AddIndex(model_name="workforcedemand", index=models.Index(fields=["company", "project_public_id", "starts_on"], name="wdemand_project_dates_idx")),
        migrations.AddIndex(model_name="workforcedemand", index=models.Index(fields=["plan", "status_code"], name="wdemand_plan_status_idx")),
        migrations.AddConstraint(model_name="workforceassignment", constraint=models.UniqueConstraint(fields=("demand", "employee_public_id", "starts_on"), name="wassign_demand_emp_start_uq")),
        migrations.AddConstraint(model_name="workforceassignment", constraint=models.CheckConstraint(condition=models.Q(("allocation_percent__gte", 0.01), ("allocation_percent__lte", 100)), name="wassign_alloc_range_ck")),
        migrations.AddConstraint(model_name="workforceassignment", constraint=models.CheckConstraint(condition=models.Q(("ends_on__isnull", True), ("ends_on__gte", models.F("starts_on")), _connector="OR"), name="wassign_date_range_ck")),
        migrations.AddIndex(model_name="workforceassignment", index=models.Index(fields=["company", "employee_public_id", "assignment_status_code"], name="wassign_employee_status_idx")),
        migrations.AddIndex(model_name="workforceassignment", index=models.Index(fields=["demand", "assignment_status_code"], name="wassign_demand_status_idx")),
        migrations.AddConstraint(model_name="employeeskillcredential", constraint=models.UniqueConstraint(fields=("company", "employee_public_id", "skill", "issued_on"), name="wcred_emp_skill_issue_uq")),
        migrations.AddConstraint(model_name="employeeskillcredential", constraint=models.CheckConstraint(condition=models.Q(("issued_on__isnull", True), ("expires_on__isnull", True), ("expires_on__gte", models.F("issued_on")), _connector="OR"), name="wcred_date_range_ck")),
        migrations.AddIndex(model_name="employeeskillcredential", index=models.Index(fields=["company", "expires_on", "verification_status_code"], name="wcred_expiry_status_idx")),
        migrations.AddIndex(model_name="employeeskillcredential", index=models.Index(fields=["company", "employee_public_id"], name="wcred_employee_idx")),
        migrations.AddConstraint(model_name="workforceapproval", constraint=models.UniqueConstraint(fields=("plan", "step_code"), name="wapproval_plan_step_uq")),
        migrations.AddIndex(model_name="workforceapproval", index=models.Index(fields=["company", "status_code", "requested_at"], name="wapproval_status_idx")),
        migrations.AddIndex(model_name="workforceapproval", index=models.Index(fields=["company", "due_at", "decided_at"], name="wapproval_due_idx")),
        migrations.AddConstraint(model_name="workforcerisk", constraint=models.CheckConstraint(condition=models.Q(("plan__isnull", False), ("demand__isnull", False), ("employee_public_id__isnull", False), _connector="OR"), name="wrisk_subject_present_ck")),
        migrations.AddIndex(model_name="workforcerisk", index=models.Index(fields=["company", "status_code", "severity_code"], name="wrisk_status_severity_idx")),
        migrations.AddIndex(model_name="workforcerisk", index=models.Index(fields=["company", "due_at", "resolved_at"], name="wrisk_due_idx")),
        migrations.AddIndex(model_name="workforceexportbatch", index=models.Index(fields=["company", "status_code", "created_at"], name="wexport_status_idx")),
    ]
