from django.urls import path

from .views import (
    ApprovalReviewView,
    ApprovalView,
    AssignmentView,
    ChecklistCompletionView,
    ChecklistView,
    DependencyView,
    MilestoneView,
    OverviewView,
    ProgressView,
    ProjectTransitionView,
    ProjectView,
    SiteView,
    TimesheetReviewView,
    TimesheetSubmitView,
    TimesheetView,
    WBSView,
    WorkItemTransitionView,
    WorkItemView,
    WorkPackageView,
)

urlpatterns = [
    path("overview", OverviewView.as_view(), name="work-overview"),
    path("projects", ProjectView.as_view(), name="work-projects"),
    path("projects/<uuid:project_id>/transition", ProjectTransitionView.as_view(), name="work-project-transition"),
    path("sites", SiteView.as_view(), name="work-sites"),
    path("wbs", WBSView.as_view(), name="work-wbs"),
    path("work-packages", WorkPackageView.as_view(), name="work-packages"),
    path("milestones", MilestoneView.as_view(), name="work-milestones"),
    path("work-items", WorkItemView.as_view(), name="work-items"),
    path("work-items/<uuid:work_item_id>/transition", WorkItemTransitionView.as_view(), name="work-item-transition"),
    path("assignments", AssignmentView.as_view(), name="work-assignments"),
    path("dependencies", DependencyView.as_view(), name="work-dependencies"),
    path("checklists", ChecklistView.as_view(), name="work-checklists"),
    path("checklists/<uuid:checklist_id>/complete", ChecklistCompletionView.as_view(), name="work-checklist-complete"),
    path("progress", ProgressView.as_view(), name="work-progress"),
    path("timesheets", TimesheetView.as_view(), name="work-timesheets"),
    path("timesheets/<uuid:timesheet_id>/submit", TimesheetSubmitView.as_view(), name="work-timesheet-submit"),
    path("timesheets/<uuid:timesheet_id>/review", TimesheetReviewView.as_view(), name="work-timesheet-review"),
    path("approvals", ApprovalView.as_view(), name="work-approvals"),
    path("approvals/<uuid:approval_id>/review", ApprovalReviewView.as_view(), name="work-approval-review"),
]
