from decimal import Decimal
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="SustainabilityPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("base_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("organizational_boundary_code", models.CharField(default="OPERATIONAL_CONTROL", max_length=50)),
                ("reporting_frequency_code", models.CharField(default="MONTHLY", max_length=30)),
                ("market_based_scope2", models.BooleanField(default=False)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sustainability_policies", to="tenant.company")),
            ],
            options={
                "db_table": "sustainops_policy",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "version"), name="sus_policy_version_uq"),
                    models.CheckConstraint(condition=models.Q(effective_to__isnull=True) | models.Q(effective_from__isnull=True) | models.Q(effective_to__gt=models.F("effective_from")), name="sus_policy_dates_ck"),
                ],
                "indexes": [models.Index(fields=["company", "status_code"], name="sus_policy_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("category_code", models.CharField(max_length=80)),
                ("scope_code", models.CharField(max_length=20)),
                ("activity_unit_code", models.CharField(max_length=40)),
                ("factor_kg_co2e_per_unit", models.DecimalField(decimal_places=8, max_digits=20)),
                ("region_code", models.CharField(blank=True, max_length=80)),
                ("source_name", models.CharField(max_length=240)),
                ("source_reference", models.CharField(blank=True, max_length=500)),
                ("valid_from", models.DateField()),
                ("valid_to", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="emission_factors", to="tenant.company")),
            ],
            options={
                "db_table": "sustainops_factor",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code", "valid_from"), name="sus_factor_period_uq"),
                    models.CheckConstraint(condition=models.Q(factor_kg_co2e_per_unit__gte=0), name="sus_factor_nonneg_ck"),
                    models.CheckConstraint(condition=models.Q(valid_to__isnull=True) | models.Q(valid_to__gte=models.F("valid_from")), name="sus_factor_dates_ck"),
                ],
                "indexes": [
                    models.Index(fields=["company", "active", "scope_code"], name="sus_factor_active_idx"),
                    models.Index(fields=["company", "category_code"], name="sus_factor_category_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CarbonInventory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("scope1_kg_co2e", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20)),
                ("scope2_kg_co2e", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20)),
                ("scope3_kg_co2e", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20)),
                ("offsets_kg_co2e", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20)),
                ("net_kg_co2e", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20)),
                ("activity_count", models.PositiveIntegerField(default=0)),
                ("methodology_code", models.CharField(default="GHG_PROTOCOL", max_length=80)),
                ("prepared_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="carbon_inventories", to="tenant.company")),
            ],
            options={
                "db_table": "sustainops_inventory",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code"), name="sus_inventory_code_uq"),
                    models.CheckConstraint(condition=models.Q(period_end__gte=models.F("period_start")), name="sus_inventory_dates_ck"),
                    models.CheckConstraint(condition=models.Q(scope1_kg_co2e__gte=0) & models.Q(scope2_kg_co2e__gte=0) & models.Q(scope3_kg_co2e__gte=0) & models.Q(offsets_kg_co2e__gte=0) & models.Q(net_kg_co2e__gte=0), name="sus_inventory_values_ck"),
                ],
                "indexes": [models.Index(fields=["company", "period_end", "status_code"], name="sus_inventory_period_idx")],
            },
        ),
        migrations.CreateModel(
            name="ResourceConsumption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("site_reference", models.CharField(blank=True, max_length=160)),
                ("resource_type_code", models.CharField(max_length=40)),
                ("resource_subtype_code", models.CharField(blank=True, max_length=80)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=20)),
                ("unit_code", models.CharField(max_length=40)),
                ("renewable_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("cost_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("source_reference", models.CharField(blank=True, max_length=300)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("captured_by_public_id", models.UUIDField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="resource_consumption", to="tenant.company")),
            ],
            options={
                "db_table": "sustainops_resource",
                "constraints": [
                    models.CheckConstraint(condition=models.Q(period_end__gte=models.F("period_start")), name="sus_resource_dates_ck"),
                    models.CheckConstraint(condition=models.Q(quantity__gte=0) & models.Q(cost_amount__gte=0), name="sus_resource_values_ck"),
                    models.CheckConstraint(condition=models.Q(renewable_percent__gte=0) & models.Q(renewable_percent__lte=100), name="sus_resource_renew_ck"),
                ],
                "indexes": [
                    models.Index(fields=["company", "resource_type_code", "period_end"], name="sus_resource_type_idx"),
                    models.Index(fields=["company", "project_public_id"], name="sus_resource_project_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WasteMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("site_reference", models.CharField(blank=True, max_length=160)),
                ("movement_date", models.DateField()),
                ("waste_type_code", models.CharField(max_length=80)),
                ("classification_code", models.CharField(default="NON_HAZARDOUS", max_length=40)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=20)),
                ("unit_code", models.CharField(default="KG", max_length=40)),
                ("treatment_code", models.CharField(max_length=40)),
                ("transporter_name", models.CharField(blank=True, max_length=240)),
                ("manifest_reference", models.CharField(blank=True, max_length=200)),
                ("destination", models.CharField(blank=True, max_length=300)),
                ("status_code", models.CharField(default="RECORDED", max_length=30)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("captured_by_public_id", models.UUIDField()),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="waste_movements", to="tenant.company")),
            ],
            options={
                "db_table": "sustainops_waste",
                "constraints": [models.CheckConstraint(condition=models.Q(quantity__gte=0), name="sus_waste_qty_ck")],
                "indexes": [
                    models.Index(fields=["company", "movement_date", "treatment_code"], name="sus_waste_date_idx"),
                    models.Index(fields=["company", "classification_code"], name="sus_waste_class_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SustainabilityTarget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("category_code", models.CharField(max_length=60)),
                ("metric_unit_code", models.CharField(max_length=40)),
                ("direction_code", models.CharField(default="REDUCE", max_length=20)),
                ("baseline_value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("target_value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("latest_value", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("progress_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("start_date", models.DateField()),
                ("target_date", models.DateField()),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sustainability_targets", to="tenant.company")),
            ],
            options={
                "db_table": "sustainops_target",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code"), name="sus_target_code_uq"),
                    models.CheckConstraint(condition=models.Q(target_date__gte=models.F("start_date")), name="sus_target_dates_ck"),
                    models.CheckConstraint(condition=models.Q(progress_percent__gte=0) & models.Q(progress_percent__lte=100), name="sus_target_progress_ck"),
                ],
                "indexes": [models.Index(fields=["company", "status_code", "target_date"], name="sus_target_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="AssuranceAssessment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("assessment_type_code", models.CharField(max_length=60)),
                ("framework_code", models.CharField(default="CUSTOM", max_length=80)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("findings_total", models.PositiveIntegerField(default=0)),
                ("major_findings", models.PositiveIntegerField(default=0)),
                ("minor_findings", models.PositiveIntegerField(default=0)),
                ("opinion_code", models.CharField(default="PENDING", max_length=40)),
                ("assessor_name", models.CharField(blank=True, max_length=240)),
                ("summary", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("prepared_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sustainability_assessments", to="tenant.company")),
            ],
            options={
                "db_table": "sustainops_assessment",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code"), name="sus_assessment_code_uq"),
                    models.CheckConstraint(condition=models.Q(period_end__gte=models.F("period_start")), name="sus_assessment_dates_ck"),
                ],
                "indexes": [models.Index(fields=["company", "status_code", "period_end"], name="sus_assessment_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="DisclosureReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=240)),
                ("framework_code", models.CharField(default="CUSTOM", max_length=80)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("executive_summary", models.TextField(blank=True)),
                ("disclosed_metrics", models.JSONField(blank=True, default=dict)),
                ("climate_risks", models.JSONField(blank=True, default=list)),
                ("prepared_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="sustainability_disclosures", to="tenant.company")),
            ],
            options={
                "db_table": "sustainops_disclosure",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code"), name="sus_disclosure_code_uq"),
                    models.CheckConstraint(condition=models.Q(period_end__gte=models.F("period_start")), name="sus_disclosure_dates_ck"),
                ],
                "indexes": [models.Index(fields=["company", "status_code", "period_end"], name="sus_disclosure_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="CarbonActivity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("site_reference", models.CharField(blank=True, max_length=160)),
                ("activity_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=20)),
                ("activity_unit_code", models.CharField(max_length=40)),
                ("calculated_kg_co2e", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20)),
                ("source_type_code", models.CharField(default="MANUAL", max_length=60)),
                ("source_reference", models.CharField(blank=True, max_length=300)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("captured_by_public_id", models.UUIDField()),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="carbon_activities", to="tenant.company")),
                ("factor", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="activities", to="sustainabilityops.emissionfactor")),
            ],
            options={
                "db_table": "sustainops_activity",
                "constraints": [
                    models.CheckConstraint(condition=models.Q(quantity__gte=0), name="sus_activity_qty_ck"),
                    models.CheckConstraint(condition=models.Q(calculated_kg_co2e__gte=0), name="sus_activity_co2_ck"),
                ],
                "indexes": [
                    models.Index(fields=["company", "activity_date", "status_code"], name="sus_activity_date_idx"),
                    models.Index(fields=["company", "project_public_id"], name="sus_activity_project_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ESGInitiative",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("pillar_code", models.CharField(default="ENVIRONMENTAL", max_length=40)),
                ("status_code", models.CharField(default="PLANNED", max_length=30)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("budget_amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("realized_value", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="esg_initiatives", to="tenant.company")),
                ("target", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="initiatives", to="sustainabilityops.sustainabilitytarget")),
            ],
            options={
                "db_table": "sustainops_initiative",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code"), name="sus_initiative_code_uq"),
                    models.CheckConstraint(condition=models.Q(budget_amount__gte=0) & models.Q(realized_value__gte=0), name="sus_initiative_values_ck"),
                ],
                "indexes": [models.Index(fields=["company", "status_code", "due_date"], name="sus_initiative_status_idx")],
            },
        ),
    ]
