import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("projects", "0001_initial"), ("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="CommercialStage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(choices=[("budget", "Budget"), ("variation", "Variation"), ("invoice", "Invoice"), ("payment", "Payment"), ("retention", "Retention release")], max_length=30)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=160)),
                ("outcome", models.CharField(choices=[("open", "Open"), ("review", "Under review"), ("approved", "Approved"), ("posted", "Posted"), ("paid", "Paid"), ("rejected", "Rejected"), ("cancelled", "Cancelled"), ("reversed", "Reversed"), ("closed", "Closed")], default="open", max_length=20)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("allowed_next_codes", models.JSONField(default=list)),
                ("is_initial", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "finance_commercial_stage",
                "ordering": ["entity_type", "sort_order", "name"],
                "constraints": [models.UniqueConstraint(fields=("company", "entity_type", "code"), name="fin_stage_company_code_uq"), models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="fin_stage_range_valid")],
                "indexes": [models.Index(fields=["company", "entity_type", "is_active", "sort_order"], name="fin_stage_active_idx")],
            },
        ),
        migrations.CreateModel(
            name="FinancePolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enforce_maker_checker", models.BooleanField(default=False)),
                ("allow_backdated_posting", models.BooleanField(default=False)),
                ("default_retention_percent", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=7)),
                ("tax_configuration", models.JSONField(default=dict)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table":"finance_policy","constraints":[models.UniqueConstraint(fields=("company",),name="fin_policy_company_uq"),models.CheckConstraint(condition=models.Q(("default_retention_percent__gte",0),("default_retention_percent__lte",100)),name="fin_policy_retention_valid")]},
        ),
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=120)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("locked_by_public_id", models.UUIDField(blank=True, null=True)),
                ("lock_reason", models.CharField(blank=True, max_length=250)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table":"finance_period","ordering":["-starts_on"],"constraints":[models.UniqueConstraint(fields=("company","code"),name="fin_period_code_uq"),models.CheckConstraint(condition=models.Q(("ends_on__gte",models.F("starts_on"))),name="fin_period_dates_valid")],"indexes":[models.Index(fields=["company","starts_on","ends_on"],name="fin_period_lookup_idx"),models.Index(fields=["company","locked_at"],name="fin_period_lock_idx")]},
        ),
        migrations.CreateModel(
            name="ProjectBudget",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=250)),
                ("currency", models.CharField(max_length=3)),
                ("approved_total", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20)),
                ("forecast_total", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="finance_budgets", to="projects.project")),
                ("stage", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="budgets", to="finance.commercialstage")),
            ],
            options={"db_table":"finance_project_budget","constraints":[models.UniqueConstraint(fields=("company","project","code"),name="fin_budget_project_code_uq"),models.CheckConstraint(condition=models.Q(("approved_total__gte",0),("forecast_total__gte",0)),name="fin_budget_totals_valid")],"indexes":[models.Index(fields=["company","project","stage"],name="fin_budget_lookup_idx")]},
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cost_code", models.CharField(max_length=80)),
                ("description", models.CharField(max_length=500)),
                ("approved_amount", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20)),
                ("committed_amount", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20)),
                ("actual_amount", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20)),
                ("accrued_amount", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20)),
                ("forecast_amount", models.DecimalField(decimal_places=4, default=Decimal("0"), max_digits=20)),
                ("budget", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="finance.projectbudget")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table":"finance_budget_line","constraints":[models.UniqueConstraint(fields=("company","budget","cost_code"),name="fin_budget_line_code_uq"),models.CheckConstraint(condition=models.Q(("approved_amount__gte",0),("committed_amount__gte",0),("actual_amount__gte",0),("accrued_amount__gte",0),("forecast_amount__gte",0)),name="fin_budget_line_values_ok")],"indexes":[models.Index(fields=["company","budget","cost_code"],name="fin_budget_line_idx")]},
        ),
        migrations.CreateModel(
            name="Variation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("variation_number", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=250)),
                ("variation_type", models.CharField(choices=[("client","Client variation"),("vendor","Vendor variation"),("internal","Internal variation")],max_length=20)),
                ("currency", models.CharField(max_length=3)),
                ("amount_ex_tax", models.DecimalField(decimal_places=4,max_digits=20)),
                ("tax_amount", models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=20)),
                ("total_amount", models.DecimalField(decimal_places=4,max_digits=20)),
                ("reason", models.TextField(blank=True)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True,null=True)),
                ("approved_at", models.DateTimeField(blank=True,null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="variations",to="projects.project")),
                ("stage", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="variations",to="finance.commercialstage")),
            ],
            options={"db_table":"finance_variation","constraints":[models.UniqueConstraint(fields=("company","variation_number"),name="fin_variation_number_uq"),models.CheckConstraint(condition=models.Q(("amount_ex_tax__gte",0),("tax_amount__gte",0),("total_amount__gte",0)),name="fin_variation_amounts_valid")],"indexes":[models.Index(fields=["company","project","stage"],name="fin_variation_lookup_idx")]},
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),
                ("created_at",models.DateTimeField(auto_now_add=True,editable=False)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("invoice_number",models.CharField(max_length=80)),
                ("invoice_type",models.CharField(choices=[("client","Client invoice"),("vendor","Vendor invoice")],max_length=20)),
                ("counterparty_name",models.CharField(max_length=250)),
                ("counterparty_reference",models.CharField(blank=True,max_length=120)),
                ("currency",models.CharField(max_length=3)),
                ("invoice_date",models.DateField()),
                ("due_date",models.DateField()),
                ("subtotal",models.DecimalField(decimal_places=4,max_digits=20)),
                ("tax_amount",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=20)),
                ("retention_amount",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=20)),
                ("total_amount",models.DecimalField(decimal_places=4,max_digits=20)),
                ("outstanding_amount",models.DecimalField(decimal_places=4,max_digits=20)),
                ("source_type",models.CharField(blank=True,max_length=80)),
                ("source_public_id",models.UUIDField(blank=True,null=True)),
                ("created_by_public_id",models.UUIDField()),
                ("approved_by_public_id",models.UUIDField(blank=True,null=True)),
                ("approved_at",models.DateTimeField(blank=True,null=True)),
                ("posted_at",models.DateTimeField(blank=True,null=True)),
                ("reversed_at",models.DateTimeField(blank=True,null=True)),
                ("version",models.PositiveBigIntegerField(default=1)),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),
                ("period",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="invoices",to="finance.financialperiod")),
                ("project",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="finance_invoices",to="projects.project")),
                ("reversal_of",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="reversals",to="finance.invoice")),
                ("stage",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="invoices",to="finance.commercialstage")),
            ],
            options={"db_table":"finance_invoice","constraints":[models.UniqueConstraint(fields=("company","invoice_type","invoice_number"),name="fin_invoice_number_uq"),models.CheckConstraint(condition=models.Q(("subtotal__gte",0),("tax_amount__gte",0),("retention_amount__gte",0),("total_amount__gte",0),("outstanding_amount__gte",0)),name="fin_invoice_amounts_valid")],"indexes":[models.Index(fields=["company","project","stage"],name="fin_invoice_lookup_idx"),models.Index(fields=["company","due_date","outstanding_amount"],name="fin_invoice_ageing_idx")]},
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),
                ("created_at",models.DateTimeField(auto_now_add=True,editable=False)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("line_number",models.PositiveIntegerField()),
                ("cost_code",models.CharField(max_length=80)),
                ("description",models.CharField(max_length=500)),
                ("quantity",models.DecimalField(decimal_places=4,max_digits=20)),
                ("unit_rate",models.DecimalField(decimal_places=4,max_digits=20)),
                ("tax_rate_percent",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=7)),
                ("amount",models.DecimalField(decimal_places=4,max_digits=20)),
                ("tax_amount",models.DecimalField(decimal_places=4,max_digits=20)),
                ("total_amount",models.DecimalField(decimal_places=4,max_digits=20)),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),
                ("invoice",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="lines",to="finance.invoice")),
            ],
            options={"db_table":"finance_invoice_line","constraints":[models.UniqueConstraint(fields=("company","invoice","line_number"),name="fin_invoice_line_number_uq"),models.CheckConstraint(condition=models.Q(("quantity__gte",0),("unit_rate__gte",0),("tax_rate_percent__gte",0),("tax_rate_percent__lte",100),("amount__gte",0),("tax_amount__gte",0),("total_amount__gte",0)),name="fin_invoice_line_values_ok")],"indexes":[models.Index(fields=["company","invoice","line_number"],name="fin_invoice_line_idx")]},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),
                ("created_at",models.DateTimeField(auto_now_add=True,editable=False)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("payment_number",models.CharField(max_length=80)),
                ("payment_type",models.CharField(choices=[("standard","Standard payment"),("retention_release","Retention release")],default="standard",max_length=30)),
                ("currency",models.CharField(max_length=3)),
                ("amount",models.DecimalField(decimal_places=4,max_digits=20)),
                ("paid_on",models.DateField()),
                ("reference",models.CharField(blank=True,max_length=160)),
                ("created_by_public_id",models.UUIDField()),
                ("posted_by_public_id",models.UUIDField(blank=True,null=True)),
                ("posted_at",models.DateTimeField(blank=True,null=True)),
                ("reversed_at",models.DateTimeField(blank=True,null=True)),
                ("version",models.PositiveBigIntegerField(default=1)),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),
                ("invoice",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="payments",to="finance.invoice")),
                ("period",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="payments",to="finance.financialperiod")),
                ("reversal_of",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="reversals",to="finance.payment")),
                ("stage",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="payments",to="finance.commercialstage")),
            ],
            options={"db_table":"finance_payment","constraints":[models.UniqueConstraint(fields=("company","payment_number"),name="fin_payment_number_uq"),models.CheckConstraint(condition=models.Q(("amount__gt",0)),name="fin_payment_amount_positive")],"indexes":[models.Index(fields=["company","invoice","stage"],name="fin_payment_lookup_idx")]},
        ),
        migrations.CreateModel(
            name="CommercialLedgerEntry",
            fields=[
                ("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),
                ("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),
                ("created_at",models.DateTimeField(auto_now_add=True,editable=False)),
                ("updated_at",models.DateTimeField(auto_now=True)),
                ("entry_type",models.CharField(choices=[("budget","Budget"),("commitment","Commitment"),("actual","Actual"),("accrual","Accrual"),("forecast","Forecast"),("variation","Variation"),("invoice","Invoice"),("payment","Payment"),("retention","Retention"),("reversal","Reversal")],max_length=30)),
                ("cost_code",models.CharField(blank=True,max_length=80)),
                ("amount",models.DecimalField(decimal_places=4,max_digits=20)),
                ("currency",models.CharField(max_length=3)),
                ("source_type",models.CharField(max_length=80)),
                ("source_public_id",models.UUIDField()),
                ("source_line_key",models.CharField(blank=True,max_length=120)),
                ("occurred_at",models.DateTimeField()),
                ("posted_by_public_id",models.UUIDField()),
                ("description",models.CharField(blank=True,max_length=500)),
                ("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),
                ("period",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="ledger_entries",to="finance.financialperiod")),
                ("project",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="commercial_ledger",to="projects.project")),
                ("reversal_of",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="reversals",to="finance.commercialledgerentry")),
            ],
            options={"db_table":"finance_commercial_ledger","ordering":["-occurred_at","-id"],"constraints":[models.UniqueConstraint(fields=("company","source_type","source_public_id","source_line_key","entry_type"),name="fin_ledger_source_fact_uq"),models.CheckConstraint(condition=models.Q(("amount",0),_negated=True),name="fin_ledger_amount_nonzero")],"indexes":[models.Index(fields=["company","project","period","entry_type"],name="fin_ledger_project_idx"),models.Index(fields=["company","source_type","source_public_id"],name="fin_ledger_source_idx")]},
        ),
    ]
