"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

export type Company = { public_id: string; code: string; display_name: string; currency: string; timezone: string };
export type FinanceSummary = { budgets: number; approved_budget: string; variations: number; variation_value: string; invoices: number; invoice_value: string; outstanding: string; overdue_invoices: number; payments_posted: number; ledger_entries: number; adjustments: number; locked_periods: number; currency: string };
export type Period = { public_id: string; code: string; name: string; starts_on: string; ends_on: string; locked_at: string | null; version: number };
export type Project = { public_id: string; code: string; name: string };
type Stage = { code: string; name: string; outcome: string; allowed_next_codes: string[] };
export type Budget = { public_id: string; code: string; name: string; project: Project; currency: string; stage: Stage; approved_total: string; forecast_total: string; line_count: number; version: number };
export type Variation = { public_id: string; variation_number: string; title: string; variation_type: string; project: Project; stage: Stage; currency: string; amount_ex_tax: string; tax_amount: string; total_amount: string; version: number };
export type Invoice = { public_id: string; invoice_number: string; invoice_type: string; counterparty_name: string; project: Project; period: { public_id: string; code: string }; stage: Stage; currency: string; invoice_date: string; due_date: string; subtotal: string; tax_amount: string; retention_amount: string; total_amount: string; outstanding_amount: string; line_count: number; version: number };
export type Payment = { public_id: string; payment_number: string; payment_type: string; invoice: { public_id: string; invoice_number: string }; period: { public_id: string; code: string }; stage: Stage; currency: string; amount: string; paid_on: string; reference: string; version: number };
export type Adjustment = { public_id: string; posting_number: string; entry_type: string; project: Project; period: { public_id: string; code: string }; cost_code: string; amount: string; currency: string; description: string; posted_at: string };
export type LedgerEntry = { public_id: string; project: Project; period: { public_id: string; code: string }; entry_type: string; cost_code: string; amount: string; currency: string; source_type: string; source_public_id: string; description: string; occurred_at: string };
type Props = { company: Company; permissions: string[]; initialSummary: FinanceSummary | null; initialPeriods: Period[]; initialBudgets: Budget[]; initialVariations: Variation[]; initialInvoices: Invoice[]; initialPayments: Payment[]; initialAdjustments: Adjustment[]; initialLedger: LedgerEntry[]; projects: Project[] };
type ApiError = { message?: string; detail?: string };

async function api<T>(path: string, init?: RequestInit) {
  const response = await fetch(`/api/finance/${path}`, { ...init, headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) } });
  const body = (await response.json().catch(() => ({}))) as T & ApiError;
  if (!response.ok) throw new Error(body.message ?? body.detail ?? "The finance operation could not be completed.");
  return body as T;
}

function Card({ label, value }: { label: string; value: string | number }) {
  return <article className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><p className="text-sm text-[var(--muted)]">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></article>;
}

export function FinanceWorkspace(props: Readonly<Props>) {
  const { company, permissions, projects } = props;
  const [tab, setTab] = useState<"budgets" | "variations" | "invoices" | "payments" | "ledger">("budgets");
  const [summary, setSummary] = useState(props.initialSummary ?? { budgets:0, approved_budget:"0", variations:0, variation_value:"0", invoices:0, invoice_value:"0", outstanding:"0", overdue_invoices:0, payments_posted:0, ledger_entries:0, adjustments:0, locked_periods:0, currency:company.currency });
  const [periods, setPeriods] = useState(props.initialPeriods); const [budgets, setBudgets] = useState(props.initialBudgets); const [variations, setVariations] = useState(props.initialVariations); const [invoices, setInvoices] = useState(props.initialInvoices); const [payments, setPayments] = useState(props.initialPayments); const [adjustments, setAdjustments] = useState(props.initialAdjustments); const [ledger, setLedger] = useState(props.initialLedger);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const openPeriod = periods.find((item) => !item.locked_at);
  async function refresh() { const [s,p,b,v,i,pa,a,l] = await Promise.all([api<FinanceSummary>("summary"), api<{items:Period[]}>("periods"), api<{items:Budget[]}>("budgets"), api<{items:Variation[]}>("variations"), api<{items:Invoice[]}>("invoices"), api<{items:Payment[]}>("payments"), api<{items:Adjustment[]}>("adjustments"), api<{items:LedgerEntry[]}>("ledger")]); setSummary(s); setPeriods(p.items); setBudgets(b.items); setVariations(v.items); setInvoices(i.items); setPayments(pa.items); setAdjustments(a.items); setLedger(l.items); }
  async function run(action: () => Promise<void>, message: string) { setBusy(true); setError(""); setNotice(""); try { await action(); await refresh(); setNotice(message); } catch (caught) { setError(caught instanceof Error ? caught.message : "The finance operation failed."); } finally { setBusy(false); } }
  async function createBudget(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); await run(async()=>{ await api("budgets", { method:"POST", body:JSON.stringify({ project_public_id:f.get("project_public_id"), code:f.get("code"), name:f.get("name"), currency:company.currency, lines:[{ cost_code:f.get("cost_code"), description:f.get("description"), approved_amount:f.get("approved_amount"), forecast_amount:f.get("forecast_amount") || f.get("approved_amount") }] }) }); event.currentTarget.reset(); }, "Project budget created with controlled cost-code values."); }
  async function createVariation(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); await run(async()=>{ await api("variations", { method:"POST", body:JSON.stringify({ project_public_id:f.get("project_public_id"), variation_number:f.get("variation_number"), title:f.get("title"), variation_type:f.get("variation_type"), currency:company.currency, amount_ex_tax:f.get("amount_ex_tax"), tax_amount:f.get("tax_amount") || "0", reason:f.get("reason") }) }); event.currentTarget.reset(); }, "Variation created in the governed commercial lifecycle."); }
  async function createInvoice(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); await run(async()=>{ await api("invoices", { method:"POST", body:JSON.stringify({ project_public_id:f.get("project_public_id"), period_public_id:f.get("period_public_id"), invoice_number:f.get("invoice_number"), invoice_type:f.get("invoice_type"), counterparty_name:f.get("counterparty_name"), currency:company.currency, invoice_date:f.get("invoice_date"), due_date:f.get("due_date"), retention_amount:f.get("retention_amount") || "0", lines:[{ cost_code:f.get("cost_code"), description:f.get("description"), quantity:f.get("quantity"), unit_rate:f.get("unit_rate"), tax_rate_percent:f.get("tax_rate_percent") || "0" }] }) }); event.currentTarget.reset(); }, "Invoice created with fixed-precision tax and retention controls."); }
  async function createPayment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); await run(async()=>{ await api("payments", { method:"POST", body:JSON.stringify({ invoice_public_id:f.get("invoice_public_id"), period_public_id:f.get("period_public_id"), payment_number:f.get("payment_number"), payment_type:f.get("payment_type"), amount:f.get("amount"), paid_on:f.get("paid_on"), reference:f.get("reference") }) }); event.currentTarget.reset(); }, "Payment prepared for maker-checker posting."); }
  async function createAdjustment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); await run(async()=>{ await api("adjustments", { method:"POST", body:JSON.stringify({ project_public_id:f.get("project_public_id"), period_public_id:f.get("period_public_id"), posting_number:f.get("posting_number"), entry_type:f.get("entry_type"), cost_code:f.get("cost_code"), amount:f.get("amount"), currency:company.currency, description:f.get("description") }) }); event.currentTarget.reset(); }, "Commercial commitment, actual, accrual or forecast posted to the append-only ledger."); }
  const input = "rounded-lg border border-[var(--border)] bg-white px-3 py-2 text-sm";
  return <main className="min-h-screen px-5 py-7 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-4 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[var(--brand)]">MPSqre Build360</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Finance and commercial controls</h1><p className="mt-2 text-sm text-[var(--muted)]">{company.display_name} · {company.currency} · governed project commercials</p></div><div className="flex gap-3"><span className="rounded-full bg-emerald-50 px-3 py-2 text-xs font-semibold uppercase tracking-wide text-emerald-900">Phase 8 active</span><Link href="/platform" className="rounded-lg border border-[var(--border)] bg-white px-4 py-2 text-sm font-semibold">Platform</Link></div></header>
    <section className="grid gap-4 py-7 sm:grid-cols-2 xl:grid-cols-4"><Card label="Approved budget" value={`${company.currency} ${summary.approved_budget}`} /><Card label="Outstanding invoices" value={`${company.currency} ${summary.outstanding}`} /><Card label="Overdue invoices" value={summary.overdue_invoices} /><Card label="Ledger entries" value={summary.ledger_entries} /></section>
    <nav className="mb-6 flex flex-wrap gap-2">{(["budgets","variations","invoices","payments","ledger"] as const).map((item)=><button key={item} onClick={()=>setTab(item)} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab===item?"bg-[var(--brand)] text-white":"border border-[var(--border)] bg-white"}`}>{item.charAt(0).toUpperCase()+item.slice(1)}</button>)}</nav>
    {error ? <p className="mb-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p> : null}{notice ? <p className="mb-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{notice}</p> : null}
    {tab==="budgets" ? <section className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={createBudget} className="grid gap-3 rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Create project budget</h2><select name="project_public_id" required className={input}><option value="">Select project</option>{projects.map(p=><option key={p.public_id} value={p.public_id}>{p.code} · {p.name}</option>)}</select><input name="code" placeholder="Budget code" required className={input}/><input name="name" placeholder="Budget name" required className={input}/><input name="cost_code" placeholder="Cost code" required className={input}/><input name="description" placeholder="Cost description" required className={input}/><input name="approved_amount" type="number" step="0.0001" min="0" placeholder="Approved amount" required className={input}/><input name="forecast_amount" type="number" step="0.0001" min="0" placeholder="Forecast amount" className={input}/><button disabled={busy || !permissions.includes("finance.budget.manage")} className="rounded-lg bg-[var(--brand)] px-4 py-2 font-semibold text-white disabled:opacity-50">Create budget</button></form><div className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Budget register</h2><div className="mt-4 grid gap-3">{budgets.map(x=><article key={x.public_id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex justify-between gap-4"><div><p className="font-semibold">{x.code} · {x.name}</p><p className="text-sm text-[var(--muted)]">{x.project.code} · {x.stage.name}</p></div><p className="font-semibold">{x.currency} {x.approved_total}</p></div></article>)}{!budgets.length?<p className="text-sm text-[var(--muted)]">No project budget has been created.</p>:null}</div></div></section> : null}
    {tab==="variations" ? <section className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={createVariation} className="grid gap-3 rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Create variation</h2><select name="project_public_id" required className={input}><option value="">Select project</option>{projects.map(p=><option key={p.public_id} value={p.public_id}>{p.code} · {p.name}</option>)}</select><input name="variation_number" placeholder="Variation number" required className={input}/><input name="title" placeholder="Variation title" required className={input}/><select name="variation_type" className={input}><option value="client">Client</option><option value="vendor">Vendor</option><option value="internal">Internal</option></select><input name="amount_ex_tax" type="number" step="0.0001" min="0" placeholder="Amount before tax" required className={input}/><input name="tax_amount" type="number" step="0.0001" min="0" placeholder="Tax amount" className={input}/><input name="reason" placeholder="Commercial reason" className={input}/><button disabled={busy || !permissions.includes("finance.variation.manage")} className="rounded-lg bg-[var(--brand)] px-4 py-2 font-semibold text-white disabled:opacity-50">Create variation</button></form><div className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Variation register</h2><div className="mt-4 grid gap-3">{variations.map(x=><article key={x.public_id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex justify-between"><div><p className="font-semibold">{x.variation_number} · {x.title}</p><p className="text-sm text-[var(--muted)]">{x.project.code} · {x.variation_type} · {x.stage.name}</p></div><p className="font-semibold">{x.currency} {x.total_amount}</p></div></article>)}{!variations.length?<p className="text-sm text-[var(--muted)]">No variation has been created.</p>:null}</div></div></section> : null}
    {tab==="invoices" ? <section className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={createInvoice} className="grid gap-3 rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Create invoice</h2><select name="project_public_id" required className={input}><option value="">Select project</option>{projects.map(p=><option key={p.public_id} value={p.public_id}>{p.code} · {p.name}</option>)}</select><select name="period_public_id" required className={input}><option value="">Select period</option>{periods.map(p=><option key={p.public_id} value={p.public_id}>{p.code}{p.locked_at?" · Locked":""}</option>)}</select><input name="invoice_number" placeholder="Invoice number" required className={input}/><select name="invoice_type" className={input}><option value="client">Client invoice</option><option value="vendor">Vendor invoice</option></select><input name="counterparty_name" placeholder="Counterparty" required className={input}/><input name="invoice_date" type="date" required className={input}/><input name="due_date" type="date" required className={input}/><input name="cost_code" placeholder="Cost code" required className={input}/><input name="description" placeholder="Line description" required className={input}/><input name="quantity" type="number" step="0.0001" min="0.0001" placeholder="Quantity" required className={input}/><input name="unit_rate" type="number" step="0.0001" min="0" placeholder="Unit rate" required className={input}/><input name="tax_rate_percent" type="number" step="0.0001" min="0" max="100" placeholder="Tax %" className={input}/><input name="retention_amount" type="number" step="0.0001" min="0" placeholder="Retention" className={input}/><button disabled={busy || !permissions.includes("finance.invoice.manage")} className="rounded-lg bg-[var(--brand)] px-4 py-2 font-semibold text-white disabled:opacity-50">Create invoice</button></form><div className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Invoice and ageing register</h2><div className="mt-4 grid gap-3">{invoices.map(x=><article key={x.public_id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex justify-between gap-4"><div><p className="font-semibold">{x.invoice_number} · {x.counterparty_name}</p><p className="text-sm text-[var(--muted)]">{x.invoice_type} · due {x.due_date} · {x.stage.name}</p></div><div className="text-right"><p className="font-semibold">{x.currency} {x.total_amount}</p><p className="text-sm text-[var(--muted)]">Outstanding {x.outstanding_amount}</p></div></div></article>)}{!invoices.length?<p className="text-sm text-[var(--muted)]">No invoice has been created.</p>:null}</div></div></section> : null}
    {tab==="payments" ? <section className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={createPayment} className="grid gap-3 rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Prepare payment</h2><select name="invoice_public_id" required className={input}><option value="">Select invoice</option>{invoices.map(i=><option key={i.public_id} value={i.public_id}>{i.invoice_number} · {i.counterparty_name} · {i.outstanding_amount}</option>)}</select><select name="period_public_id" required className={input}><option value="">Select period</option>{periods.map(p=><option key={p.public_id} value={p.public_id}>{p.code}</option>)}</select><input name="payment_number" placeholder="Payment number" required className={input}/><select name="payment_type" className={input}><option value="standard">Standard payment</option><option value="retention_release">Retention release</option></select><input name="amount" type="number" step="0.0001" min="0.0001" placeholder="Amount" required className={input}/><input name="paid_on" type="date" required className={input}/><input name="reference" placeholder="Bank/reference number" className={input}/><button disabled={busy || !permissions.includes("finance.payment.manage")} className="rounded-lg bg-[var(--brand)] px-4 py-2 font-semibold text-white disabled:opacity-50">Prepare payment</button></form><div className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Payment register</h2><div className="mt-4 grid gap-3">{payments.map(x=><article key={x.public_id} className="rounded-xl border border-[var(--border)] p-4"><div className="flex justify-between"><div><p className="font-semibold">{x.payment_number} · {x.invoice.invoice_number}</p><p className="text-sm text-[var(--muted)]">{x.payment_type} · {x.paid_on} · {x.stage.name}</p></div><p className="font-semibold">{x.currency} {x.amount}</p></div></article>)}{!payments.length?<p className="text-sm text-[var(--muted)]">No payment has been prepared.</p>:null}</div></div></section> : null}
    {tab==="ledger" ? <section className="grid gap-6 lg:grid-cols-[360px_1fr]"><form onSubmit={createAdjustment} className="grid gap-3 rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold">Post commercial adjustment</h2><p className="text-sm text-[var(--muted)]">Controlled commitment, actual, accrual or forecast entry.</p><select name="project_public_id" required className={input}><option value="">Select project</option>{projects.map(p=><option key={p.public_id} value={p.public_id}>{p.code} · {p.name}</option>)}</select><select name="period_public_id" required className={input}><option value="">Select open period</option>{periods.filter(p=>!p.locked_at).map(p=><option key={p.public_id} value={p.public_id}>{p.code}</option>)}</select><input name="posting_number" placeholder="Posting number" required className={input}/><select name="entry_type" className={input}><option value="commitment">Commitment</option><option value="actual">Actual</option><option value="accrual">Accrual</option><option value="forecast">Forecast</option></select><input name="cost_code" placeholder="Cost code" required className={input}/><input name="amount" type="number" step="0.0001" placeholder="Signed amount" required className={input}/><input name="description" placeholder="Posting description" required className={input}/><button disabled={busy || !permissions.includes("finance.adjustment.post")} className="rounded-lg bg-[var(--brand)] px-4 py-2 font-semibold text-white disabled:opacity-50">Post adjustment</button><p className="text-xs text-[var(--muted)]">Posted adjustments: {adjustments.length}</p></form><div className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-semibold">Append-only commercial ledger</h2><p className="text-sm text-[var(--muted)]">Open period: {openPeriod?.code ?? "None"}</p></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-[var(--border)]"><th className="py-3">Date</th><th>Project</th><th>Period</th><th>Entry</th><th>Source</th><th className="text-right">Amount</th></tr></thead><tbody>{ledger.map(x=><tr key={x.public_id} className="border-b border-[var(--border)]"><td className="py-3">{new Date(x.occurred_at).toLocaleDateString()}</td><td>{x.project.code}</td><td>{x.period.code}</td><td>{x.entry_type}</td><td>{x.source_type}</td><td className="text-right font-medium">{x.currency} {x.amount}</td></tr>)}</tbody></table>{!ledger.length?<p className="py-5 text-sm text-[var(--muted)]">No posted financial facts are available.</p>:null}</div></div></section> : null}
  </div></main>;
}
