import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial=True
    dependencies=[("projects","0001_initial"),("tenant","0001_initial")]
    operations=[
        migrations.CreateModel(name="InventoryItem",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("code",models.CharField(max_length=80)),("name",models.CharField(max_length=250)),("category_code",models.CharField(blank=True,max_length=80)),("base_unit_code",models.CharField(max_length=30)),("description",models.TextField(blank=True)),("track_inventory",models.BooleanField(default=True)),("is_active",models.BooleanField(default=True)),("version",models.PositiveBigIntegerField(default=1)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company"))],options={"db_table":"inventory_item","indexes":[models.Index(fields=["company","is_active","name"],name="inv_item_lookup_idx")],"constraints":[models.UniqueConstraint(fields=("company","code"),name="inv_item_company_code_uniq")]}),
        migrations.CreateModel(name="Warehouse",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("code",models.CharField(max_length=60)),("name",models.CharField(max_length=200)),("location",models.JSONField(default=dict)),("is_active",models.BooleanField(default=True)),("version",models.PositiveBigIntegerField(default=1)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("project",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="warehouses",to="projects.project"))],options={"db_table":"inventory_warehouse","indexes":[models.Index(fields=["company","is_active","name"],name="warehouse_lookup_idx")],"constraints":[models.UniqueConstraint(fields=("company","code"),name="warehouse_company_code_uniq")]}),
        migrations.CreateModel(name="StockBalance",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("quantity_on_hand",models.DecimalField(decimal_places=4,default=0,max_digits=20)),("quantity_reserved",models.DecimalField(decimal_places=4,default=0,max_digits=20)),("average_unit_cost",models.DecimalField(decimal_places=4,default=0,max_digits=20)),("version",models.PositiveBigIntegerField(default=1)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("item",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="balances",to="inventory.inventoryitem")),("warehouse",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="balances",to="inventory.warehouse"))],options={"db_table":"inventory_stock_balance","indexes":[models.Index(fields=["company","warehouse","item"],name="stock_balance_lookup_idx")],"constraints":[models.UniqueConstraint(fields=("company","item","warehouse"),name="stock_balance_uniq"),models.CheckConstraint(condition=models.Q(("quantity_reserved__gte",0)),name="stock_reserved_nonnegative")]}),
        migrations.CreateModel(name="StockLedgerEntry",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("movement_type",models.CharField(choices=[("receipt","Receipt"),("issue","Issue"),("return","Return"),("transfer_in","Transfer in"),("transfer_out","Transfer out"),("adjustment","Adjustment"),("reversal","Reversal")],max_length=30)),("quantity",models.DecimalField(decimal_places=4,max_digits=20)),("unit_cost",models.DecimalField(decimal_places=4,default=0,max_digits=20)),("balance_after",models.DecimalField(decimal_places=4,max_digits=20)),("source_type",models.CharField(max_length=80)),("source_public_id",models.UUIDField()),("source_line_key",models.CharField(blank=True,max_length=120)),("occurred_at",models.DateTimeField()),("posted_by_public_id",models.UUIDField()),("reason_code",models.CharField(blank=True,max_length=100)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("item",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="ledger_entries",to="inventory.inventoryitem")),("reversal_of",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="reversals",to="inventory.stockledgerentry")),("warehouse",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="ledger_entries",to="inventory.warehouse"))],options={"db_table":"inventory_stock_ledger","ordering":["-occurred_at","-id"],"indexes":[models.Index(fields=["company","warehouse","item","occurred_at"],name="stock_ledger_lookup_idx"),models.Index(fields=["company","source_type","source_public_id"],name="stock_source_lookup_idx")],"constraints":[models.UniqueConstraint(fields=("company","source_type","source_public_id","source_line_key"),name="stock_source_fact_uniq"),models.CheckConstraint(condition=models.Q(("quantity",0),_negated=True),name="stock_quantity_nonzero")]})
    ]
