import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="ChannelPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(choices=[("in_app", "In-app"), ("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp"), ("voice", "Voice")], max_length=20)),
                ("is_enabled", models.BooleanField(default=False)),
                ("consent_required", models.BooleanField(default=True)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("retry_limit", models.PositiveSmallIntegerField(default=3)),
                ("max_daily_per_subject", models.PositiveIntegerField(default=20)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "communication_channel_policy",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "channel"), name="com_policy_company_channel_uq"),
                    models.CheckConstraint(condition=models.Q(("retry_limit__lte", 10)), name="com_policy_retry_limit_ok"),
                ],
                "indexes": [models.Index(fields=["company", "channel", "is_enabled"], name="com_policy_active_idx")],
            },
        ),
        migrations.CreateModel(
            name="ProviderConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(choices=[("in_app", "In-app"), ("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp"), ("voice", "Voice")], max_length=20)),
                ("code", models.CharField(max_length=80)),
                ("display_name", models.CharField(max_length=160)),
                ("adapter_code", models.CharField(max_length=80)),
                ("secret_reference", models.CharField(blank=True, max_length=250)),
                ("callback_key_id", models.CharField(blank=True, max_length=100)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("is_active", models.BooleanField(default=False)),
                ("supports_inbound", models.BooleanField(default=False)),
                ("supports_delivery_receipts", models.BooleanField(default=False)),
                ("configuration", models.JSONField(default=dict)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "communication_provider_config",
                "ordering": ["channel", "priority", "display_name"],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="com_provider_company_code_uq")],
                "indexes": [models.Index(fields=["company", "channel", "is_active", "priority"], name="com_provider_active_idx")],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("channel", models.CharField(choices=[("in_app", "In-app"), ("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp"), ("voice", "Voice")], max_length=20)),
                ("locale", models.CharField(default="en", max_length=35)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published"), ("retired", "Retired")], default="draft", max_length=20)),
                ("subject_template", models.CharField(blank=True, max_length=300)),
                ("body_template", models.TextField()),
                ("variable_names", models.JSONField(default=list)),
                ("purpose_code", models.CharField(max_length=100)),
                ("created_by_public_id", models.UUIDField()),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "communication_message_template",
                "ordering": ["code", "channel", "locale", "-version"],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code", "channel", "locale", "version"), name="com_template_version_uq"),
                    models.UniqueConstraint(condition=models.Q(("status", "published")), fields=("company", "code", "channel", "locale"), name="com_template_published_uq"),
                ],
                "indexes": [models.Index(fields=["company", "channel", "status", "locale"], name="com_template_lookup_idx")],
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject_type", models.CharField(max_length=80)),
                ("subject_public_id", models.UUIDField()),
                ("channel", models.CharField(choices=[("in_app", "In-app"), ("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp"), ("voice", "Voice")], max_length=20)),
                ("purpose_code", models.CharField(max_length=100)),
                ("status", models.CharField(choices=[("granted", "Granted"), ("withdrawn", "Withdrawn"), ("denied", "Denied")], max_length=20)),
                ("source_code", models.CharField(max_length=100)),
                ("proof_reference", models.CharField(blank=True, max_length=250)),
                ("effective_at", models.DateTimeField()),
                ("recorded_by_public_id", models.UUIDField()),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "communication_consent_record",
                "ordering": ["-effective_at", "-id"],
                "indexes": [models.Index(fields=["company", "subject_type", "subject_public_id", "channel", "purpose_code", "effective_at"], name="com_consent_lookup_idx")],
            },
        ),
        migrations.CreateModel(
            name="CommunicationRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(choices=[("in_app", "In-app"), ("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp"), ("voice", "Voice")], max_length=20)),
                ("subject_type", models.CharField(max_length=80)),
                ("subject_public_id", models.UUIDField()),
                ("recipient_reference_type", models.CharField(max_length=80)),
                ("recipient_reference_public_id", models.UUIDField()),
                ("purpose_code", models.CharField(max_length=100)),
                ("locale", models.CharField(default="en", max_length=35)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("scheduled", "Scheduled"), ("processing", "Processing"), ("sent", "Sent"), ("delivered", "Delivered"), ("failed", "Failed"), ("suppressed", "Suppressed"), ("cancelled", "Cancelled")], default="queued", max_length=20)),
                ("rendered_subject", models.CharField(blank=True, max_length=300)),
                ("rendered_body", models.TextField()),
                ("template_variables", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=120)),
                ("requested_by_public_id", models.UUIDField()),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("suppression_reason", models.CharField(blank=True, max_length=250)),
                ("provider_message_id", models.CharField(blank=True, max_length=250)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("provider", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="communication.providerconfiguration")),
                ("template", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="requests", to="communication.messagetemplate")),
            ],
            options={
                "db_table": "communication_request",
                "ordering": ["-created_at"],
                "constraints": [models.UniqueConstraint(fields=("company", "idempotency_key"), name="com_request_idempotency_uq")],
                "indexes": [
                    models.Index(fields=["company", "status", "scheduled_for"], name="com_request_queue_idx"),
                    models.Index(fields=["company", "subject_type", "subject_public_id", "created_at"], name="com_request_subject_idx"),
                    models.Index(fields=["company", "provider_message_id"], name="com_request_provider_msg_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommunicationAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attempt_number", models.PositiveSmallIntegerField()),
                ("status", models.CharField(choices=[("started", "Started"), ("accepted", "Accepted"), ("delivered", "Delivered"), ("failed", "Failed")], max_length=20)),
                ("provider_message_id", models.CharField(blank=True, max_length=250)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, max_length=100)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("response_metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attempts", to="communication.providerconfiguration")),
                ("request", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="attempts", to="communication.communicationrequest")),
            ],
            options={
                "db_table": "communication_attempt",
                "constraints": [models.UniqueConstraint(fields=("company", "request", "attempt_number"), name="com_attempt_number_uq")],
                "indexes": [models.Index(fields=["company", "request", "status"], name="com_attempt_request_idx")],
            },
        ),
        migrations.CreateModel(
            name="CallbackReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider_event_id", models.CharField(max_length=250)),
                ("event_type", models.CharField(max_length=100)),
                ("provider_message_id", models.CharField(blank=True, max_length=250)),
                ("payload_digest", models.CharField(max_length=64)),
                ("signature_valid", models.BooleanField(default=False)),
                ("received_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.CharField(blank=True, max_length=250)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="callback_receipts", to="communication.providerconfiguration")),
                ("request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="callback_receipts", to="communication.communicationrequest")),
            ],
            options={
                "db_table": "communication_callback_receipt",
                "constraints": [models.UniqueConstraint(fields=("company", "provider", "provider_event_id"), name="com_callback_event_uq")],
                "indexes": [models.Index(fields=["company", "provider", "received_at"], name="com_callback_lookup_idx")],
            },
        ),
        migrations.CreateModel(
            name="InboundCommunication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(choices=[("in_app", "In-app"), ("email", "Email"), ("sms", "SMS"), ("whatsapp", "WhatsApp"), ("voice", "Voice")], max_length=20)),
                ("provider_message_id", models.CharField(max_length=250)),
                ("sender_reference_hash", models.CharField(blank=True, max_length=64)),
                ("subject_reference_type", models.CharField(blank=True, max_length=80)),
                ("subject_reference_public_id", models.UUIDField(blank=True, null=True)),
                ("summary", models.CharField(max_length=500)),
                ("status", models.CharField(choices=[("received", "Received"), ("correlated", "Correlated"), ("review_required", "Review required"), ("processed", "Processed"), ("rejected", "Rejected")], max_length=30)),
                ("received_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inbound_messages", to="communication.providerconfiguration")),
            ],
            options={
                "db_table": "communication_inbound",
                "constraints": [models.UniqueConstraint(fields=("company", "provider", "provider_message_id"), name="com_inbound_message_uq")],
                "indexes": [models.Index(fields=["company", "status", "received_at"], name="com_inbound_queue_idx")],
            },
        ),
    ]
