# Generated by Django 6.0.7 on 2026-07-30 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=150)),
                ('employment_start', models.DateField()),
                ('employment_end', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='tenant.company')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='tenant.membership')),
            ],
            options={
                'db_table': 'employee_employee',
            },
        ),
        migrations.CreateModel(
            name='ReportingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporting_lines', to='tenant.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_history', to='employee.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_history', to='employee.employee')),
            ],
            options={
                'db_table': 'employee_reporting_line',
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'employee_number'], name='employee_company_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company', 'employee_number'), name='employee_company_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('employment_end__isnull', True), ('employment_end__gte', models.F('employment_start')), _connector='OR'), name='employee_employment_range_valid'),
        ),
        migrations.AddConstraint(
            model_name='reportingline',
            constraint=models.CheckConstraint(condition=models.Q(('employee', models.F('manager')), _negated=True), name='reporting_line_no_self_manager'),
        ),
        migrations.AddConstraint(
            model_name='reportingline',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='reporting_line_range_valid'),
        ),
    ]
