import uuid
from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("tenant", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CustomerSuccessAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("display_name", models.CharField(max_length=180)),
                ("segment", models.CharField(choices=[("pilot", "Pilot"), ("standard", "Standard"), ("enterprise", "Enterprise"), ("strategic", "Strategic")], max_length=20)),
                ("status", models.CharField(choices=[("onboarding", "Onboarding"), ("active", "Active"), ("at_risk", "At risk"), ("paused", "Paused"), ("churned", "Churned")], default="onboarding", max_length=20)),
                ("customer_since", models.DateField(default=django.utils.timezone.localdate)),
                ("renewal_on", models.DateField(blank=True, null=True)),
                ("health_score", models.PositiveSmallIntegerField(default=50)),
                ("risk_level", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], default="medium", max_length=20)),
                ("desired_outcomes", models.JSONField(default=list)),
                ("risk_summary", models.CharField(blank=True, max_length=1000)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("account_owner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="success_accounts", to="tenant.membership")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "successops_account", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="SupportSlaPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], max_length=20)),
                ("first_response_minutes", models.PositiveIntegerField()),
                ("resolution_minutes", models.PositiveIntegerField()),
                ("escalation_minutes", models.PositiveIntegerField()),
                ("business_hours_only", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "successops_sla_policy", "ordering": ["severity"]},
        ),
        migrations.CreateModel(
            name="AdoptionSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("captured_on", models.DateField(default=django.utils.timezone.localdate)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("active_projects", models.PositiveIntegerField(default=0)),
                ("support_ticket_count", models.PositiveIntegerField(default=0)),
                ("feature_utilization", models.JSONField(default=dict)),
                ("adoption_score", models.PositiveSmallIntegerField(default=0)),
                ("engagement_score", models.PositiveSmallIntegerField(default=0)),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="customer_success_adoption_snapshots", to="tenant.company")),
            ],
            options={"db_table": "successops_adoption", "ordering": ["-captured_on"]},
        ),
        migrations.CreateModel(
            name="BillingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("legal_name", models.CharField(max_length=220)),
                ("billing_email", models.EmailField(max_length=254)),
                ("tax_identifier_masked", models.CharField(blank=True, max_length=80)),
                ("currency", models.CharField(max_length=3)),
                ("billing_cycle", models.CharField(choices=[("monthly", "Monthly"), ("quarterly", "Quarterly"), ("annual", "Annual"), ("custom", "Custom")], max_length=20)),
                ("payment_terms_days", models.PositiveSmallIntegerField(default=30)),
                ("status", models.CharField(choices=[("active", "Active"), ("on_hold", "On hold"), ("closed", "Closed")], default="active", max_length=20)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("account", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="billing_profile", to="successops.customersuccessaccount")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "successops_billing_profile"},
        ),
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(max_length=100)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("issued_on", models.DateField(blank=True, null=True)),
                ("due_on", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=18)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("outstanding_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("issued", "Issued"), ("partially_paid", "Partially paid"), ("paid", "Paid"), ("overdue", "Overdue"), ("void", "Void")], default="draft", max_length=24)),
                ("external_reference", models.CharField(blank=True, max_length=240)),
                ("evidence_sha256", models.CharField(blank=True, max_length=64)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscription_invoices", to="successops.customersuccessaccount")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "successops_invoice", "ordering": ["-period_end", "-created_at"]},
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ticket_number", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=240)),
                ("description", models.CharField(max_length=2000)),
                ("category", models.CharField(default="general", max_length=100)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], max_length=20)),
                ("status", models.CharField(choices=[("open", "Open"), ("triage", "Triage"), ("in_progress", "In progress"), ("waiting_customer", "Waiting for customer"), ("resolved", "Resolved"), ("closed", "Closed")], default="open", max_length=24)),
                ("requester_user_public_id", models.UUIDField()),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("first_responded_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("response_due_at", models.DateTimeField()),
                ("resolution_due_at", models.DateTimeField()),
                ("escalated_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_summary", models.CharField(blank=True, max_length=2000)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="support_tickets", to="successops.customersuccessaccount")),
                ("assigned_membership", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assigned_support_tickets", to="tenant.membership")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={"db_table": "successops_ticket", "ordering": ["-opened_at"]},
        ),
        migrations.CreateModel(
            name="SuccessPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=240)),
                ("objectives", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("active", "Active"), ("at_risk", "At risk"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="draft", max_length=20)),
                ("next_review_on", models.DateField(blank=True, null=True)),
                ("renewal_on", models.DateField(blank=True, null=True)),
                ("health_score", models.PositiveSmallIntegerField(default=50)),
                ("risk_summary", models.CharField(blank=True, max_length=1000)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="success_plans", to="successops.customersuccessaccount")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("owner_membership", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="owned_success_plans", to="tenant.membership")),
            ],
            options={"db_table": "successops_plan", "ordering": ["code"]},
        ),
        migrations.CreateModel(
            name="PaymentRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=140)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("received_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("verified", "Verified"), ("reversed", "Reversed")], default="pending", max_length=20)),
                ("evidence_sha256", models.CharField(max_length=64)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="successops.subscriptioninvoice")),
            ],
            options={"db_table": "successops_payment", "ordering": ["-received_at"]},
        ),
        migrations.AddConstraint(model_name="customersuccessaccount", constraint=models.UniqueConstraint(fields=("company", "code"), name="suc_account_code_uq")),
        migrations.AddConstraint(model_name="customersuccessaccount", constraint=models.CheckConstraint(condition=models.Q(("health_score__gte", 0), ("health_score__lte", 100)), name="suc_account_health_ck")),
        migrations.AddIndex(model_name="customersuccessaccount", index=models.Index(fields=["company", "status", "risk_level"], name="suc_account_status_idx")),
        migrations.AddIndex(model_name="billingprofile", index=models.Index(fields=["company", "status", "billing_cycle"], name="suc_bill_profile_idx")),
        migrations.AddConstraint(model_name="subscriptioninvoice", constraint=models.UniqueConstraint(fields=("company", "invoice_number"), name="suc_invoice_number_uq")),
        migrations.AddConstraint(model_name="subscriptioninvoice", constraint=models.CheckConstraint(condition=models.Q(("subtotal__gte", 0)), name="suc_invoice_subtotal_ck")),
        migrations.AddConstraint(model_name="subscriptioninvoice", constraint=models.CheckConstraint(condition=models.Q(("tax_amount__gte", 0)), name="suc_invoice_tax_ck")),
        migrations.AddConstraint(model_name="subscriptioninvoice", constraint=models.CheckConstraint(condition=models.Q(("total_amount__gte", 0)), name="suc_invoice_total_ck")),
        migrations.AddConstraint(model_name="subscriptioninvoice", constraint=models.CheckConstraint(condition=models.Q(("outstanding_amount__gte", 0)), name="suc_invoice_due_ck")),
        migrations.AddIndex(model_name="subscriptioninvoice", index=models.Index(fields=["company", "status", "due_on"], name="suc_invoice_status_idx")),
        migrations.AddConstraint(model_name="paymentrecord", constraint=models.UniqueConstraint(fields=("company", "reference"), name="suc_payment_reference_uq")),
        migrations.AddConstraint(model_name="paymentrecord", constraint=models.CheckConstraint(condition=models.Q(("amount__gt", 0)), name="suc_payment_amount_ck")),
        migrations.AddIndex(model_name="paymentrecord", index=models.Index(fields=["company", "status", "received_at"], name="suc_payment_status_idx")),
        migrations.AddConstraint(model_name="supportslapolicy", constraint=models.UniqueConstraint(fields=("company", "code"), name="suc_sla_code_uq")),
        migrations.AddConstraint(model_name="supportslapolicy", constraint=models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("company", "severity"), name="suc_sla_active_uq")),
        migrations.AddConstraint(model_name="supportticket", constraint=models.UniqueConstraint(fields=("company", "ticket_number"), name="suc_ticket_number_uq")),
        migrations.AddIndex(model_name="supportticket", index=models.Index(fields=["company", "status", "severity"], name="suc_ticket_status_idx")),
        migrations.AddIndex(model_name="supportticket", index=models.Index(fields=["company", "resolution_due_at"], name="suc_ticket_due_idx")),
        migrations.AddConstraint(model_name="successplan", constraint=models.UniqueConstraint(fields=("company", "code"), name="suc_plan_code_uq")),
        migrations.AddConstraint(model_name="successplan", constraint=models.CheckConstraint(condition=models.Q(("health_score__gte", 0), ("health_score__lte", 100)), name="suc_plan_health_ck")),
        migrations.AddConstraint(model_name="adoptionsnapshot", constraint=models.UniqueConstraint(fields=("company", "captured_on"), name="suc_adoption_date_uq")),
        migrations.AddConstraint(model_name="adoptionsnapshot", constraint=models.CheckConstraint(condition=models.Q(("adoption_score__gte", 0), ("adoption_score__lte", 100)), name="suc_adoption_score_ck")),
        migrations.AddConstraint(model_name="adoptionsnapshot", constraint=models.CheckConstraint(condition=models.Q(("engagement_score__gte", 0), ("engagement_score__lte", 100)), name="suc_engagement_score_ck")),
    ]
