from django.urls import path

from .views import (
    CallCreateView,
    CallTransitionView,
    ClaimCreateView,
    ClaimTransitionView,
    CounterpartyCreateView,
    CounterpartyTransitionView,
    CoverageCreateView,
    CoverageTransitionView,
    EventCreateView,
    InstrumentCreateView,
    InstrumentTransitionView,
    LossCreateView,
    LossTransitionView,
    OverviewView,
    PremiumCreateView,
    PremiumTransitionView,
    ProgramCreateView,
    ProgramTransitionView,
    SeedDefaultsView,
)

urlpatterns = [
    path("overview", OverviewView.as_view(), name="risk-transfer-overview"),
    path("seed-defaults", SeedDefaultsView.as_view(), name="risk-transfer-seed-defaults"),
    path("counterparties", CounterpartyCreateView.as_view(), name="risk-transfer-counterparty-create"),
    path("counterparties/<uuid:counterparty_id>/transition", CounterpartyTransitionView.as_view(), name="risk-transfer-counterparty-transition"),
    path("programs", ProgramCreateView.as_view(), name="risk-transfer-program-create"),
    path("programs/<uuid:program_id>/transition", ProgramTransitionView.as_view(), name="risk-transfer-program-transition"),
    path("coverages", CoverageCreateView.as_view(), name="risk-transfer-coverage-create"),
    path("coverages/<uuid:coverage_id>/transition", CoverageTransitionView.as_view(), name="risk-transfer-coverage-transition"),
    path("premiums", PremiumCreateView.as_view(), name="risk-transfer-premium-create"),
    path("premiums/<uuid:premium_id>/transition", PremiumTransitionView.as_view(), name="risk-transfer-premium-transition"),
    path("losses", LossCreateView.as_view(), name="risk-transfer-loss-create"),
    path("losses/<uuid:loss_id>/transition", LossTransitionView.as_view(), name="risk-transfer-loss-transition"),
    path("claims", ClaimCreateView.as_view(), name="risk-transfer-claim-create"),
    path("claims/<uuid:claim_id>/transition", ClaimTransitionView.as_view(), name="risk-transfer-claim-transition"),
    path("instruments", InstrumentCreateView.as_view(), name="risk-transfer-instrument-create"),
    path("instruments/<uuid:instrument_id>/transition", InstrumentTransitionView.as_view(), name="risk-transfer-instrument-transition"),
    path("calls", CallCreateView.as_view(), name="risk-transfer-call-create"),
    path("calls/<uuid:call_id>/transition", CallTransitionView.as_view(), name="risk-transfer-call-transition"),
    path("events", EventCreateView.as_view(), name="risk-transfer-event-create"),
]
