import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("fieldops", "0001_initial"), ("projects", "0001_initial"), ("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(name="InspectionTemplate",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("code",models.CharField(max_length=80)),("name",models.CharField(max_length=200)),("discipline_code",models.CharField(max_length=80)),("version_number",models.PositiveIntegerField(default=1)),("checklist",models.JSONField(default=list)),("is_published",models.BooleanField(default=False)),("published_at",models.DateTimeField(blank=True,null=True)),("retired_at",models.DateTimeField(blank=True,null=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company"))],options={"db_table":"quality_inspection_template","constraints":[models.UniqueConstraint(fields=("company","code","version_number"),name="qlt_template_version_uq")],"indexes":[models.Index(fields=["company","discipline_code","is_published"],name="qlt_template_active_idx")]}),
        migrations.CreateModel(name="Inspection",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("inspection_number",models.CharField(max_length=80)),("title",models.CharField(max_length=250)),("location",models.JSONField(default=dict)),("scheduled_at",models.DateTimeField(blank=True,null=True)),("inspected_at",models.DateTimeField(blank=True,null=True)),("inspector_membership_public_id",models.UUIDField()),("checklist_result",models.JSONField(default=list)),("overall_result",models.CharField(blank=True,max_length=30)),("evidence_file_public_ids",models.JSONField(default=list)),("operation_id",models.UUIDField(blank=True,null=True)),("version",models.PositiveBigIntegerField(default=1)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("project",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inspections",to="projects.project")),("stage",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inspections",to="fieldops.fieldstage")),("template",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="inspections",to="quality.inspectiontemplate"))],options={"db_table":"quality_inspection","constraints":[models.UniqueConstraint(fields=("company","inspection_number"),name="qlt_inspection_number_uq"),models.UniqueConstraint(condition=models.Q(("operation_id__isnull",False)),fields=("company","operation_id"),name="qlt_inspection_operation_uq")],"indexes":[models.Index(fields=["company","project","stage"],name="qlt_inspection_project_idx")]}),
        migrations.CreateModel(name="NonConformanceReport",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("ncr_number",models.CharField(max_length=80)),("title",models.CharField(max_length=250)),("description",models.TextField()),("severity",models.CharField(max_length=30)),("responsible_membership_public_id",models.UUIDField(blank=True,null=True)),("due_date",models.DateField(blank=True,null=True)),("root_cause",models.TextField(blank=True)),("corrective_action",models.TextField(blank=True)),("verified_by_public_id",models.UUIDField(blank=True,null=True)),("verified_at",models.DateTimeField(blank=True,null=True)),("version",models.PositiveBigIntegerField(default=1)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("inspection",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="ncrs",to="quality.inspection")),("project",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="ncrs",to="projects.project")),("stage",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="ncrs",to="fieldops.fieldstage"))],options={"db_table":"quality_non_conformance","constraints":[models.UniqueConstraint(fields=("company","ncr_number"),name="qlt_ncr_number_uq")],"indexes":[models.Index(fields=["company","project","stage","due_date"],name="qlt_ncr_project_idx")]})
    ]
