# Generated for MPSqre Build360 Phase 5 design control.
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("projects", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="DesignDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_number", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=250)),
                ("discipline_code", models.CharField(max_length=80)),
                ("document_type_code", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("created_by_public_id", models.UUIDField()),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="design_documents", to="projects.project")),
            ],
            options={"db_table": "design_document"},
        ),
        migrations.CreateModel(
            name="DesignVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                ("revision_code", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                ("file_object_public_id", models.UUIDField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("created_by_public_id", models.UUIDField()),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="versions", to="design.designdocument")),
                ("stage", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="design_versions", to="projects.deliverystage")),
            ],
            options={"db_table": "design_version"},
        ),
        migrations.CreateModel(
            name="DesignReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewer_membership_public_id", models.UUIDField()),
                ("decision", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("approved_with_comments", "Approved with comments"), ("rejected", "Rejected")], default="pending", max_length=40)),
                ("comments", models.TextField(blank=True)),
                ("requested_by_public_id", models.UUIDField()),
                ("requested_at", models.DateTimeField()),
                ("decided_by_public_id", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("design_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="reviews", to="design.designversion")),
            ],
            options={"db_table": "design_review"},
        ),
        migrations.CreateModel(
            name="DesignIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], max_length=20)),
                ("raised_by_public_id", models.UUIDField()),
                ("assigned_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("resolution", models.TextField(blank=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("design_version", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="issues", to="design.designversion")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="design_issues", to="projects.project")),
            ],
            options={"db_table": "design_issue"},
        ),
        migrations.CreateModel(
            name="DesignTransmittal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=120)),
                ("purpose_code", models.CharField(max_length=80)),
                ("recipient", models.CharField(max_length=250)),
                ("notes", models.TextField(blank=True)),
                ("issued_by_public_id", models.UUIDField()),
                ("issued_at", models.DateTimeField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transmittals", to="projects.project")),
            ],
            options={"db_table": "design_transmittal"},
        ),
        migrations.CreateModel(
            name="TransmittalItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("design_version", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="transmittal_items", to="design.designversion")),
                ("transmittal", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="items", to="design.designtransmittal")),
            ],
            options={"db_table": "design_transmittal_item"},
        ),
        migrations.AddConstraint(model_name="designdocument", constraint=models.UniqueConstraint(fields=("company", "project", "document_number"), name="des_doc_number_uq")),
        migrations.AddIndex(model_name="designdocument", index=models.Index(fields=["company", "project", "discipline_code"], name="des_doc_project_idx")),
        migrations.AddConstraint(model_name="designversion", constraint=models.UniqueConstraint(fields=("company", "document", "version_number"), name="des_version_number_uq")),
        migrations.AddConstraint(model_name="designversion", constraint=models.UniqueConstraint(fields=("company", "document", "revision_code"), name="des_revision_code_uq")),
        migrations.AddIndex(model_name="designversion", index=models.Index(fields=["company", "document", "stage", "version_number"], name="des_version_lookup_idx")),
        migrations.AddConstraint(model_name="designreview", constraint=models.UniqueConstraint(fields=("company", "design_version", "reviewer_membership_public_id"), name="des_review_reviewer_uq")),
        migrations.AddIndex(model_name="designreview", index=models.Index(fields=["company", "reviewer_membership_public_id", "decision"], name="des_review_inbox_idx")),
        migrations.AddIndex(model_name="designissue", index=models.Index(fields=["company", "project", "closed_at", "severity"], name="des_issue_project_idx")),
        migrations.AddIndex(model_name="designissue", index=models.Index(fields=["company", "assigned_membership_public_id", "closed_at"], name="des_issue_assignee_idx")),
        migrations.AddConstraint(model_name="designtransmittal", constraint=models.UniqueConstraint(fields=("company", "project", "reference"), name="des_transmittal_ref_uq")),
        migrations.AddIndex(model_name="designtransmittal", index=models.Index(fields=["company", "project", "issued_at"], name="des_transmittal_lookup_idx")),
        migrations.AddConstraint(model_name="transmittalitem", constraint=models.UniqueConstraint(fields=("company", "transmittal", "design_version"), name="des_trans_item_uq")),
    ]
