from decimal import Decimal
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="InsightPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("review_frequency_code", models.CharField(default="MONTHLY", max_length=30)),
                ("on_target_threshold", models.DecimalField(decimal_places=2, default=Decimal("90.00"), max_digits=5)),
                ("warning_threshold", models.DecimalField(decimal_places=2, default=Decimal("75.00"), max_digits=5)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="insight_policies", to="tenant.company")),
            ],
            options={
                "db_table": "insightops_policy_version",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "version"), name="ins_policy_version_uq"),
                    models.CheckConstraint(condition=models.Q(effective_to__isnull=True) | models.Q(effective_from__isnull=True) | models.Q(effective_to__gt=models.F("effective_from")), name="ins_policy_dates_ck"),
                    models.CheckConstraint(condition=models.Q(on_target_threshold__gte=0) & models.Q(on_target_threshold__lte=100) & models.Q(warning_threshold__gte=0) & models.Q(warning_threshold__lte=100), name="ins_policy_threshold_ck"),
                ],
                "indexes": [models.Index(fields=["company", "status_code"], name="ins_policy_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="StrategicObjective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("perspective_code", models.CharField(default="OPERATIONS", max_length=40)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("weight_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=5)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("target_outcome", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="strategic_objectives", to="tenant.company")),
            ],
            options={
                "db_table": "insightops_objective",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code"), name="ins_objective_code_uq"),
                    models.CheckConstraint(condition=models.Q(weight_percent__gte=0) & models.Q(weight_percent__lte=100), name="ins_objective_weight_ck"),
                    models.CheckConstraint(condition=models.Q(target_date__isnull=True) | models.Q(start_date__isnull=True) | models.Q(target_date__gte=models.F("start_date")), name="ins_objective_dates_ck"),
                ],
                "indexes": [models.Index(fields=["company", "status_code", "perspective_code"], name="ins_objective_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="KPIDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("unit_code", models.CharField(default="PERCENT", max_length=40)),
                ("direction_code", models.CharField(default="HIGHER_BETTER", max_length=30)),
                ("aggregation_code", models.CharField(default="LATEST", max_length=30)),
                ("frequency_code", models.CharField(default="MONTHLY", max_length=30)),
                ("target_value", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("warning_value", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("critical_value", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("target_low", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("target_high", models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="kpi_definitions", to="tenant.company")),
                ("objective", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="kpis", to="insightops.strategicobjective")),
            ],
            options={
                "db_table": "insightops_kpi_definition",
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="ins_kpi_code_uq")],
                "indexes": [
                    models.Index(fields=["company", "active", "frequency_code"], name="ins_kpi_active_idx"),
                    models.Index(fields=["company", "objective"], name="ins_kpi_objective_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="KPIObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("actual_value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("source_code", models.CharField(default="MANUAL", max_length=80)),
                ("source_reference", models.CharField(blank=True, max_length=240)),
                ("data_quality_code", models.CharField(default="VERIFIED", max_length=30)),
                ("captured_by_public_id", models.UUIDField()),
                ("captured_at", models.DateTimeField()),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="kpi_observations", to="tenant.company")),
                ("kpi", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="observations", to="insightops.kpidefinition")),
            ],
            options={
                "db_table": "insightops_kpi_observation",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "kpi", "period_end"), name="ins_kpi_observation_uq"),
                    models.CheckConstraint(condition=models.Q(period_end__gte=models.F("period_start")), name="ins_kpi_period_ck"),
                ],
                "indexes": [models.Index(fields=["company", "period_end"], name="ins_kpi_period_idx")],
            },
        ),
        migrations.CreateModel(
            name="PortfolioSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("as_of_date", models.DateField()),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("projects_total", models.PositiveIntegerField(default=0)),
                ("projects_healthy", models.PositiveIntegerField(default=0)),
                ("projects_at_risk", models.PositiveIntegerField(default=0)),
                ("projects_critical", models.PositiveIntegerField(default=0)),
                ("schedule_performance_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=7)),
                ("cost_performance_percent", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=7)),
                ("portfolio_value", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("narrative", models.TextField(blank=True)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="portfolio_snapshots", to="tenant.company")),
            ],
            options={
                "db_table": "insightops_portfolio_snapshot",
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="ins_portfolio_code_uq")],
                "indexes": [models.Index(fields=["company", "as_of_date", "status_code"], name="ins_portfolio_date_idx")],
            },
        ),
        migrations.CreateModel(
            name="BenefitPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("category_code", models.CharField(default="EFFICIENCY", max_length=80)),
                ("status_code", models.CharField(default="PLANNED", max_length=30)),
                ("unit_code", models.CharField(default="PERCENT", max_length=40)),
                ("baseline_value", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20)),
                ("target_value", models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=20)),
                ("expected_financial_value", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="benefit_plans", to="tenant.company")),
                ("objective", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="benefits", to="insightops.strategicobjective")),
            ],
            options={
                "db_table": "insightops_benefit_plan",
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="ins_benefit_code_uq")],
                "indexes": [models.Index(fields=["company", "status_code", "target_date"], name="ins_benefit_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="BenefitMeasurement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("measured_at", models.DateField()),
                ("actual_value", models.DecimalField(decimal_places=4, max_digits=20)),
                ("realized_financial_value", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("confidence_percent", models.DecimalField(decimal_places=2, default=Decimal("100.00"), max_digits=5)),
                ("captured_by_public_id", models.UUIDField()),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("benefit", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="measurements", to="insightops.benefitplan")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="benefit_measurements", to="tenant.company")),
            ],
            options={
                "db_table": "insightops_benefit_measurement",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "benefit", "measured_at"), name="ins_benefit_measure_uq"),
                    models.CheckConstraint(condition=models.Q(confidence_percent__gte=0) & models.Q(confidence_percent__lte=100), name="ins_benefit_confidence_ck"),
                ],
                "indexes": [models.Index(fields=["company", "measured_at"], name="ins_benefit_measure_idx")],
            },
        ),
        migrations.CreateModel(
            name="ExecutiveAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("priority_code", models.CharField(default="P2", max_length=10)),
                ("status_code", models.CharField(default="OPEN", max_length=30)),
                ("source_type_code", models.CharField(default="EXECUTIVE_REVIEW", max_length=80)),
                ("source_public_id", models.UUIDField(blank=True, null=True)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_summary", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="executive_actions", to="tenant.company")),
            ],
            options={
                "db_table": "insightops_executive_action",
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="ins_action_code_uq")],
                "indexes": [
                    models.Index(fields=["company", "status_code", "priority_code"], name="ins_action_status_idx"),
                    models.Index(fields=["company", "due_at"], name="ins_action_due_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BoardReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=240)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("executive_summary", models.TextField(blank=True)),
                ("scorecard", models.JSONField(blank=True, default=dict)),
                ("decisions", models.JSONField(blank=True, default=list)),
                ("prepared_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="board_reports", to="tenant.company")),
            ],
            options={
                "db_table": "insightops_board_report",
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code"), name="ins_board_report_code_uq"),
                    models.CheckConstraint(condition=models.Q(period_end__gte=models.F("period_start")), name="ins_board_period_ck"),
                ],
                "indexes": [models.Index(fields=["company", "period_end", "status_code"], name="ins_board_period_idx")],
            },
        ),
    ]
