# Generated for MPSqre Build360 Phase 11.
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="AIProviderProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("display_name", models.CharField(max_length=160)),
                ("adapter_code", models.CharField(max_length=100)),
                ("secret_reference", models.CharField(blank=True, max_length=240)),
                ("data_residency", models.CharField(blank=True, max_length=80)),
                ("configuration", models.JSONField(default=dict)),
                ("supports_citations", models.BooleanField(default=True)),
                ("supports_extraction", models.BooleanField(default=False)),
                ("supports_tools", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "ai_provider_profile",
                "ordering": ["display_name"],
                "indexes": [models.Index(fields=["company", "is_active", "adapter_code"], name="ai_provider_active_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="ai_provider_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="AIModelPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("model_name", models.CharField(max_length=160)),
                ("purpose", models.CharField(choices=[("assistant", "Grounded assistant"), ("extraction", "Document extraction"), ("risk", "Risk signal detection"), ("evaluation", "Model evaluation")], max_length=20)),
                ("system_instruction", models.TextField(blank=True)),
                ("allowed_source_types", models.JSONField(default=list)),
                ("allowed_data_classifications", models.JSONField(default=list)),
                ("allowed_tool_codes", models.JSONField(default=list)),
                ("max_context_records", models.PositiveSmallIntegerField(default=20)),
                ("max_output_characters", models.PositiveIntegerField(default=6000)),
                ("human_review_required", models.BooleanField(default=True)),
                ("citations_required", models.BooleanField(default=True)),
                ("retention_days", models.PositiveIntegerField(default=30)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("provider", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="policies", to="ai.aiproviderprofile")),
            ],
            options={
                "db_table": "ai_model_policy",
                "ordering": ["purpose", "name", "-version"],
                "indexes": [models.Index(fields=["company", "purpose", "is_active"], name="ai_policy_purpose_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code", "version"), name="ai_policy_version_uq"),
                    models.UniqueConstraint(condition=models.Q(("is_active", True)), fields=("company", "code"), name="ai_policy_active_uq"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIInteraction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_by_public_id", models.UUIDField()),
                ("membership_public_id", models.UUIDField()),
                ("idempotency_key", models.CharField(max_length=120)),
                ("purpose", models.CharField(choices=[("assistant", "Grounded assistant"), ("extraction", "Document extraction"), ("risk", "Risk signal detection"), ("evaluation", "Model evaluation")], max_length=20)),
                ("prompt_digest", models.CharField(max_length=64)),
                ("prompt_excerpt", models.CharField(blank=True, max_length=500)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed"), ("blocked", "Blocked")], default="queued", max_length=20)),
                ("response_text", models.TextField(blank=True)),
                ("confidence", models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ("citations_required", models.BooleanField(default=True)),
                ("review_status", models.CharField(choices=[("not_required", "Not required"), ("pending", "Pending review"), ("approved", "Approved"), ("rejected", "Rejected"), ("corrected", "Corrected")], default="pending", max_length=20)),
                ("reviewed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_reason", models.CharField(blank=True, max_length=500)),
                ("input_metadata", models.JSONField(default=dict)),
                ("output_metadata", models.JSONField(default=dict)),
                ("provider_request_id", models.CharField(blank=True, max_length=200)),
                ("provider_code_snapshot", models.CharField(max_length=80)),
                ("model_name_snapshot", models.CharField(max_length=160)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.CharField(blank=True, max_length=1000)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="interactions", to="ai.aimodelpolicy")),
            ],
            options={
                "db_table": "ai_interaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["company", "status", "created_at"], name="ai_interaction_status_idx"),
                    models.Index(fields=["company", "requested_by_public_id", "created_at"], name="ai_interaction_user_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("company", "idempotency_key"), name="ai_interaction_idem_uq")],
            },
        ),
        migrations.CreateModel(
            name="AICitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rank", models.PositiveSmallIntegerField()),
                ("source_type", models.CharField(max_length=100)),
                ("source_public_id", models.UUIDField()),
                ("source_label", models.CharField(max_length=240)),
                ("source_version", models.CharField(blank=True, max_length=80)),
                ("excerpt", models.CharField(blank=True, max_length=600)),
                ("authorization_basis", models.CharField(max_length=160)),
                ("data_classification", models.CharField(default="internal", max_length=30)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("interaction", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="citations", to="ai.aiinteraction")),
            ],
            options={
                "db_table": "ai_citation",
                "ordering": ["rank"],
                "indexes": [models.Index(fields=["company", "source_type", "source_public_id"], name="ai_citation_source_idx")],
                "constraints": [models.UniqueConstraint(fields=("interaction", "rank"), name="ai_citation_rank_uq")],
            },
        ),
        migrations.CreateModel(
            name="AIExtractionJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_by_public_id", models.UUIDField()),
                ("idempotency_key", models.CharField(max_length=120)),
                ("source_type", models.CharField(max_length=100)),
                ("source_public_id", models.UUIDField(blank=True, null=True)),
                ("source_digest", models.CharField(max_length=64)),
                ("schema_code", models.CharField(max_length=100)),
                ("requested_fields", models.JSONField(default=list)),
                ("extracted_payload", models.JSONField(default=dict)),
                ("confidence_by_field", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("completed", "Completed"), ("failed", "Failed"), ("reviewed", "Reviewed"), ("rejected", "Rejected")], default="queued", max_length=20)),
                ("reviewed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("corrections", models.JSONField(default=dict)),
                ("review_reason", models.CharField(blank=True, max_length=500)),
                ("error_message", models.CharField(blank=True, max_length=1000)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="extraction_jobs", to="ai.aimodelpolicy")),
            ],
            options={
                "db_table": "ai_extraction_job",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company", "status", "created_at"], name="ai_extract_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "idempotency_key"), name="ai_extract_idem_uq")],
            },
        ),
        migrations.CreateModel(
            name="AIRiskSignal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("signal_code", models.CharField(max_length=120)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")], max_length=20)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField()),
                ("source_type", models.CharField(max_length=100)),
                ("source_public_id", models.UUIDField(blank=True, null=True)),
                ("evidence", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("open", "Open"), ("acknowledged", "Acknowledged"), ("resolved", "Resolved"), ("dismissed", "Dismissed")], default="open", max_length=20)),
                ("assigned_to_public_id", models.UUIDField(blank=True, null=True)),
                ("resolved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("disposition_reason", models.CharField(blank=True, max_length=500)),
                ("fingerprint", models.CharField(max_length=64)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("detected_by_interaction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="risk_signals", to="ai.aiinteraction")),
            ],
            options={
                "db_table": "ai_risk_signal",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company", "status", "severity"], name="ai_risk_status_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("status__in", ["open", "acknowledged"])), fields=("company", "fingerprint"), name="ai_risk_open_fingerprint_uq")],
            },
        ),
        migrations.CreateModel(
            name="AIToolAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_code", models.CharField(max_length=120)),
                ("target_type", models.CharField(max_length=100)),
                ("target_public_id", models.UUIDField(blank=True, null=True)),
                ("proposed_payload", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("proposed", "Proposed"), ("confirmed", "Confirmed"), ("rejected", "Rejected"), ("expired", "Expired")], default="proposed", max_length=20)),
                ("proposed_by_public_id", models.UUIDField()),
                ("decided_by_public_id", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.CharField(blank=True, max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("idempotency_key", models.CharField(max_length=120)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("interaction", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="tool_actions", to="ai.aiinteraction")),
            ],
            options={
                "db_table": "ai_tool_action",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company", "status", "expires_at"], name="ai_action_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "idempotency_key"), name="ai_action_idem_uq")],
            },
        ),
        migrations.CreateModel(
            name="AIEvaluationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("requested_by_public_id", models.UUIDField()),
                ("suite_code", models.CharField(max_length=100)),
                ("status", models.CharField(choices=[("completed", "Completed"), ("failed", "Failed")], max_length=20)),
                ("scenario_count", models.PositiveIntegerField(default=0)),
                ("passed_count", models.PositiveIntegerField(default=0)),
                ("scores", models.JSONField(default=dict)),
                ("failures", models.JSONField(default=list)),
                ("provider_code_snapshot", models.CharField(max_length=80)),
                ("model_name_snapshot", models.CharField(max_length=160)),
                ("completed_at", models.DateTimeField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="evaluation_runs", to="ai.aimodelpolicy")),
            ],
            options={
                "db_table": "ai_evaluation_run",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company", "suite_code", "created_at"], name="ai_eval_suite_idx")],
            },
        ),
    ]
