import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="DigitalTwinPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("coordinate_system_code", models.CharField(default="PROJECT_LOCAL", max_length=80)),
                ("model_review_frequency_code", models.CharField(default="WEEKLY", max_length=30)),
                ("telemetry_retention_days", models.PositiveIntegerField(default=365)),
                ("alert_acknowledgement_minutes", models.PositiveIntegerField(default=30)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="digital_twin_policies", to="tenant.company")),
            ],
            options={"db_table": "twinops_policy"},
        ),
        migrations.CreateModel(
            name="BIMModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("site_reference", models.CharField(blank=True, max_length=160)),
                ("discipline_code", models.CharField(max_length=60)),
                ("model_type_code", models.CharField(default="AUTHORING", max_length=40)),
                ("file_format_code", models.CharField(default="IFC", max_length=30)),
                ("authoring_tool", models.CharField(blank=True, max_length=160)),
                ("coordinate_system_code", models.CharField(default="PROJECT_LOCAL", max_length=80)),
                ("storage_reference", models.CharField(blank=True, max_length=500)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("current_revision_code", models.CharField(blank=True, max_length=40)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                ("model_metadata", models.JSONField(blank=True, default=dict)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bim_models", to="tenant.company")),
            ],
            options={"db_table": "twinops_model"},
        ),
        migrations.CreateModel(
            name="ModelFederation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("model_public_ids", models.JSONField(blank=True, default=list)),
                ("model_count", models.PositiveIntegerField(default=0)),
                ("coordination_date", models.DateField(blank=True, null=True)),
                ("prepared_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="model_federations", to="tenant.company")),
            ],
            options={"db_table": "twinops_federation"},
        ),
        migrations.CreateModel(
            name="IoTDevice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("site_reference", models.CharField(blank=True, max_length=160)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("device_type_code", models.CharField(max_length=60)),
                ("external_device_reference", models.CharField(blank=True, max_length=200)),
                ("provider_code", models.CharField(default="GENERIC", max_length=80)),
                ("protocol_code", models.CharField(default="HTTP", max_length=40)),
                ("metric_code", models.CharField(max_length=80)),
                ("unit_code", models.CharField(max_length=40)),
                ("status_code", models.CharField(default="REGISTERED", max_length=30)),
                ("threshold_configuration", models.JSONField(blank=True, default=dict)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("installed_at", models.DateTimeField(blank=True, null=True)),
                ("firmware_version", models.CharField(blank=True, max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="smart_site_devices", to="tenant.company")),
            ],
            options={"db_table": "twinops_device"},
        ),
        migrations.CreateModel(
            name="BIMRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision_code", models.CharField(max_length=40)),
                ("issue_purpose_code", models.CharField(default="COORDINATION", max_length=60)),
                ("file_reference", models.CharField(max_length=500)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("authored_by_public_id", models.UUIDField()),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bim_revisions", to="tenant.company")),
                ("model", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="revisions", to="digitaltwinops.bimmodel")),
            ],
            options={"db_table": "twinops_revision"},
        ),
        migrations.CreateModel(
            name="ClashRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clash_number", models.CharField(max_length=80)),
                ("clash_type_code", models.CharField(default="HARD", max_length=60)),
                ("severity_code", models.CharField(default="MEDIUM", max_length=30)),
                ("discipline_a_code", models.CharField(max_length=60)),
                ("discipline_b_code", models.CharField(max_length=60)),
                ("element_a_reference", models.CharField(blank=True, max_length=200)),
                ("element_b_reference", models.CharField(blank=True, max_length=200)),
                ("location_reference", models.CharField(blank=True, max_length=240)),
                ("coordinates", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("status_code", models.CharField(default="OPEN", max_length=30)),
                ("assigned_to_public_id", models.UUIDField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bim_clashes", to="tenant.company")),
                ("federation", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="clashes", to="digitaltwinops.modelfederation")),
            ],
            options={"db_table": "twinops_clash"},
        ),
        migrations.CreateModel(
            name="BIMIssue",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("site_reference", models.CharField(blank=True, max_length=160)),
                ("issue_code", models.CharField(max_length=80)),
                ("category_code", models.CharField(default="COORDINATION", max_length=60)),
                ("priority_code", models.CharField(default="NORMAL", max_length=30)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("status_code", models.CharField(default="OPEN", max_length=30)),
                ("assigned_to_public_id", models.UUIDField(blank=True, null=True)),
                ("raised_by_public_id", models.UUIDField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="bim_issues", to="tenant.company")),
                ("model", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="issues", to="digitaltwinops.bimmodel")),
                ("revision", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="issues", to="digitaltwinops.bimrevision")),
            ],
            options={"db_table": "twinops_issue"},
        ),
        migrations.CreateModel(
            name="TelemetryReading",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observed_at", models.DateTimeField()),
                ("metric_code", models.CharField(max_length=80)),
                ("numeric_value", models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ("text_value", models.CharField(blank=True, max_length=500)),
                ("unit_code", models.CharField(max_length=40)),
                ("quality_code", models.CharField(default="GOOD", max_length=30)),
                ("source_reference", models.CharField(blank=True, max_length=300)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="smart_site_telemetry", to="tenant.company")),
                ("device", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="readings", to="digitaltwinops.iotdevice")),
            ],
            options={"db_table": "twinops_telemetry"},
        ),
        migrations.CreateModel(
            name="SmartAlert",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("alert_code", models.CharField(max_length=80)),
                ("alert_type_code", models.CharField(max_length=60)),
                ("severity_code", models.CharField(default="MEDIUM", max_length=30)),
                ("status_code", models.CharField(default="OPEN", max_length=30)),
                ("message", models.TextField()),
                ("triggered_at", models.DateTimeField()),
                ("acknowledged_by_public_id", models.UUIDField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("source_reading_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="smart_site_alerts", to="tenant.company")),
                ("device", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="alerts", to="digitaltwinops.iotdevice")),
            ],
            options={"db_table": "twinops_alert"},
        ),
        migrations.CreateModel(
            name="HandoverAssetRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("site_reference", models.CharField(blank=True, max_length=160)),
                ("asset_tag", models.CharField(max_length=100)),
                ("asset_name", models.CharField(max_length=240)),
                ("classification_code", models.CharField(max_length=80)),
                ("model_element_reference", models.CharField(blank=True, max_length=200)),
                ("serial_number", models.CharField(blank=True, max_length=160)),
                ("manufacturer", models.CharField(blank=True, max_length=240)),
                ("location_reference", models.CharField(blank=True, max_length=240)),
                ("commissioned_on", models.DateField(blank=True, null=True)),
                ("warranty_end_on", models.DateField(blank=True, null=True)),
                ("operation_status_code", models.CharField(default="DRAFT", max_length=40)),
                ("maintainable", models.BooleanField(default=True)),
                ("document_references", models.JSONField(blank=True, default=list)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("captured_by_public_id", models.UUIDField()),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="digital_handover_assets", to="tenant.company")),
                ("model", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="handover_assets", to="digitaltwinops.bimmodel")),
            ],
            options={"db_table": "twinops_asset"},
        ),
        migrations.AddConstraint(model_name="digitaltwinpolicyversion", constraint=models.UniqueConstraint(fields=("company", "version"), name="twin_policy_version_uq")),
        migrations.AddConstraint(model_name="digitaltwinpolicyversion", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_from__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="twin_policy_dates_ck")),
        migrations.AddIndex(model_name="digitaltwinpolicyversion", index=models.Index(fields=["company", "status_code"], name="twin_policy_status_idx")),
        migrations.AddConstraint(model_name="bimmodel", constraint=models.UniqueConstraint(fields=("company", "code"), name="twin_model_code_uq")),
        migrations.AddIndex(model_name="bimmodel", index=models.Index(fields=["company", "project_public_id", "status_code"], name="twin_model_project_idx")),
        migrations.AddIndex(model_name="bimmodel", index=models.Index(fields=["company", "discipline_code"], name="twin_model_discipline_idx")),
        migrations.AddConstraint(model_name="modelfederation", constraint=models.UniqueConstraint(fields=("company", "code"), name="twin_federation_code_uq")),
        migrations.AddIndex(model_name="modelfederation", index=models.Index(fields=["company", "project_public_id", "status_code"], name="twin_federation_project_idx")),
        migrations.AddConstraint(model_name="iotdevice", constraint=models.UniqueConstraint(fields=("company", "code"), name="twin_device_code_uq")),
        migrations.AddIndex(model_name="iotdevice", index=models.Index(fields=["company", "status_code", "last_seen_at"], name="twin_device_status_idx")),
        migrations.AddIndex(model_name="iotdevice", index=models.Index(fields=["company", "project_public_id"], name="twin_device_project_idx")),
        migrations.AddConstraint(model_name="bimrevision", constraint=models.UniqueConstraint(fields=("model", "revision_code"), name="twin_revision_code_uq")),
        migrations.AddIndex(model_name="bimrevision", index=models.Index(fields=["company", "status_code", "created_at"], name="twin_revision_status_idx")),
        migrations.AddConstraint(model_name="clashrecord", constraint=models.UniqueConstraint(fields=("federation", "clash_number"), name="twin_clash_number_uq")),
        migrations.AddIndex(model_name="clashrecord", index=models.Index(fields=["company", "status_code", "severity_code"], name="twin_clash_status_idx")),
        migrations.AddIndex(model_name="clashrecord", index=models.Index(fields=["company", "due_date"], name="twin_clash_due_idx")),
        migrations.AddConstraint(model_name="bimissue", constraint=models.UniqueConstraint(fields=("company", "issue_code"), name="twin_issue_code_uq")),
        migrations.AddIndex(model_name="bimissue", index=models.Index(fields=["company", "status_code", "priority_code"], name="twin_issue_status_idx")),
        migrations.AddIndex(model_name="bimissue", index=models.Index(fields=["company", "project_public_id"], name="twin_issue_project_idx")),
        migrations.AddIndex(model_name="telemetryreading", index=models.Index(fields=["company", "device", "observed_at"], name="twin_telemetry_device_idx")),
        migrations.AddIndex(model_name="telemetryreading", index=models.Index(fields=["company", "metric_code", "observed_at"], name="twin_telemetry_metric_idx")),
        migrations.AddConstraint(model_name="smartalert", constraint=models.UniqueConstraint(fields=("company", "alert_code"), name="twin_alert_code_uq")),
        migrations.AddIndex(model_name="smartalert", index=models.Index(fields=["company", "status_code", "severity_code"], name="twin_alert_status_idx")),
        migrations.AddIndex(model_name="smartalert", index=models.Index(fields=["company", "triggered_at"], name="twin_alert_time_idx")),
        migrations.AddConstraint(model_name="handoverassetrecord", constraint=models.UniqueConstraint(fields=("company", "asset_tag"), name="twin_asset_tag_uq")),
        migrations.AddConstraint(model_name="handoverassetrecord", constraint=models.CheckConstraint(condition=models.Q(("warranty_end_on__isnull", True), ("commissioned_on__isnull", True), ("warranty_end_on__gte", models.F("commissioned_on")), _connector="OR"), name="twin_asset_warranty_ck")),
        migrations.AddIndex(model_name="handoverassetrecord", index=models.Index(fields=["company", "project_public_id", "operation_status_code"], name="twin_asset_project_idx")),
        migrations.AddIndex(model_name="handoverassetrecord", index=models.Index(fields=["company", "classification_code"], name="twin_asset_class_idx")),
    ]
