import uuid
from decimal import Decimal
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("fieldops", "0001_initial"), ("projects", "0001_initial"), ("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(name="EquipmentAsset", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("code",models.CharField(max_length=80)),("name",models.CharField(max_length=200)),("category_code",models.CharField(max_length=80)),("ownership_type",models.CharField(default="owned",max_length=30)),("serial_number",models.CharField(blank=True,max_length=120)),("registration_number",models.CharField(blank=True,max_length=120)),("acquisition_date",models.DateField(blank=True,null=True)),("hourly_cost",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=19)),("currency",models.CharField(max_length=3)),("current_meter",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=14)),("meter_unit",models.CharField(default="hours",max_length=20)),("version",models.PositiveBigIntegerField(default=1)),("retired_at",models.DateTimeField(blank=True,null=True)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("stage",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="equipment_assets",to="fieldops.fieldstage"))], options={"db_table":"equipment_asset","constraints":[models.UniqueConstraint(fields=("company","code"),name="eqp_asset_code_uq"),models.CheckConstraint(condition=models.Q(("hourly_cost__gte",0)),name="eqp_hourly_cost_valid"),models.CheckConstraint(condition=models.Q(("current_meter__gte",0)),name="eqp_meter_nonnegative")],"indexes":[models.Index(fields=["company","stage","category_code"],name="eqp_asset_stage_idx")]}),
        migrations.CreateModel(name="EquipmentAllocation", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("allocated_from",models.DateTimeField()),("allocated_to",models.DateTimeField(blank=True,null=True)),("custodian_membership_public_id",models.UUIDField(blank=True,null=True)),("planned_meter_usage",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=14)),("notes",models.TextField(blank=True)),("version",models.PositiveBigIntegerField(default=1)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("equipment",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="allocations",to="equipment.equipmentasset")),("project",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="equipment_allocations",to="projects.project")),("stage",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="equipment_allocations",to="fieldops.fieldstage"))], options={"db_table":"equipment_allocation","constraints":[models.CheckConstraint(condition=models.Q(("allocated_to__isnull",True),("allocated_to__gte",models.F("allocated_from")),_connector="OR"),name="eqp_alloc_dates_valid"),models.CheckConstraint(condition=models.Q(("planned_meter_usage__gte",0)),name="eqp_alloc_usage_valid")],"indexes":[models.Index(fields=["company","project","stage"],name="eqp_alloc_project_idx")]}),
        migrations.CreateModel(name="MeterReading", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("reading",models.DecimalField(decimal_places=2,max_digits=14)),("reading_at",models.DateTimeField()),("source",models.CharField(default="web",max_length=20)),("operation_id",models.UUIDField(blank=True,null=True)),("recorded_by_public_id",models.UUIDField()),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("equipment",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="meter_readings",to="equipment.equipmentasset"))], options={"db_table":"equipment_meter_reading","constraints":[models.UniqueConstraint(condition=models.Q(("operation_id__isnull",False)),fields=("company","operation_id"),name="eqp_meter_operation_uq"),models.CheckConstraint(condition=models.Q(("reading__gte",0)),name="eqp_reading_valid")],"indexes":[models.Index(fields=["company","equipment","reading_at"],name="eqp_meter_lookup_idx")]}),
        migrations.CreateModel(name="MaintenanceWorkOrder", fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("work_order_number",models.CharField(max_length=80)),("maintenance_type",models.CharField(max_length=40)),("summary",models.CharField(max_length=250)),("description",models.TextField(blank=True)),("due_date",models.DateField(blank=True,null=True)),("opened_at",models.DateTimeField()),("completed_at",models.DateTimeField(blank=True,null=True)),("meter_at_open",models.DecimalField(decimal_places=2,default=Decimal("0"),max_digits=14)),("cost",models.DecimalField(decimal_places=4,default=Decimal("0"),max_digits=19)),("currency",models.CharField(max_length=3)),("version",models.PositiveBigIntegerField(default=1)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("equipment",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="maintenance_orders",to="equipment.equipmentasset")),("stage",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="maintenance_orders",to="fieldops.fieldstage"))], options={"db_table":"equipment_maintenance_order","constraints":[models.UniqueConstraint(fields=("company","work_order_number"),name="eqp_work_order_uq"),models.CheckConstraint(condition=models.Q(("cost__gte",0)),name="eqp_maintenance_cost_valid")],"indexes":[models.Index(fields=["company","stage","due_date"],name="eqp_maintenance_due_idx")]})
    ]
