# Generated for MPSqre Build360 Phase 21 Payroll Operations.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollPeriod",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("payment_due_on", models.DateField()),
                ("status_code", models.CharField(max_length=80)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("configuration", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_periods", to="tenant.company")),
            ],
            options={"db_table": "payroll_period"},
        ),
        migrations.CreateModel(
            name="PayrollPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(max_length=80)),
                ("locale_code", models.CharField(blank=True, max_length=35)),
                ("currency", models.CharField(max_length=3)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(default=dict)),
                ("change_note", models.CharField(blank=True, max_length=500)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_policy_versions", to="tenant.company")),
            ],
            options={"db_table": "payroll_policy_version"},
        ),
        migrations.CreateModel(
            name="PayComponentDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField(default=1)),
                ("component_type_code", models.CharField(max_length=80)),
                ("calculation_method_code", models.CharField(max_length=80)),
                ("unit_code", models.CharField(blank=True, max_length=50)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("taxable_policy_code", models.CharField(blank=True, max_length=80)),
                ("ledger_mapping_code", models.CharField(blank=True, max_length=100)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("configuration", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="pay_component_definitions", to="tenant.company")),
            ],
            options={"db_table": "payroll_component_definition"},
        ),
        migrations.CreateModel(
            name="CompensationAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_public_id", models.UUIDField()),
                ("employment_public_id", models.UUIDField(blank=True, null=True)),
                ("compensation_plan_code", models.CharField(max_length=100)),
                ("currency", models.CharField(max_length=3)),
                ("annualized_cost", models.DecimalField(decimal_places=2, max_digits=18)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("source_reference", models.CharField(blank=True, max_length=150)),
                ("configuration", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="compensation_assignments", to="tenant.company")),
            ],
            options={"db_table": "payroll_comp_assignment"},
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_number", models.PositiveIntegerField(default=1)),
                ("run_type_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("currency", models.CharField(max_length=3)),
                ("version", models.PositiveIntegerField(default=1)),
                ("initiated_by_public_id", models.UUIDField()),
                ("calculated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("gross_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("deduction_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("employer_cost_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("net_amount", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("employee_count", models.PositiveIntegerField(default=0)),
                ("exception_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_runs", to="tenant.company")),
                ("period", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="payrollops.payrollperiod")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="runs", to="payrollops.payrollpolicyversion")),
            ],
            options={"db_table": "payroll_run"},
        ),
        migrations.CreateModel(
            name="PayrollRunLine",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_public_id", models.UUIDField()),
                ("employment_public_id", models.UUIDField(blank=True, null=True)),
                ("currency", models.CharField(max_length=3)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("deduction_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("employer_cost_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=18)),
                ("status_code", models.CharField(max_length=80)),
                ("exception_codes", models.JSONField(default=list)),
                ("component_breakdown", models.JSONField(default=list)),
                ("calculation_trace", models.JSONField(default=dict)),
                ("source_reference", models.CharField(blank=True, max_length=150)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_run_lines", to="tenant.company")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lines", to="payrollops.payrollrun")),
            ],
            options={"db_table": "payroll_run_line"},
        ),
        migrations.CreateModel(
            name="PayrollException",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("employee_public_id", models.UUIDField(blank=True, null=True)),
                ("exception_code", models.CharField(max_length=100)),
                ("severity_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("message", models.CharField(max_length=500)),
                ("owner_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("resolution_note", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_exceptions", to="tenant.company")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="exceptions", to="payrollops.payrollrun")),
            ],
            options={"db_table": "payroll_exception"},
        ),
        migrations.CreateModel(
            name="PayrollApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("step_code", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("requested_from_membership_public_id", models.UUIDField()),
                ("requested_by_public_id", models.UUIDField()),
                ("requested_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by_public_id", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_code", models.CharField(blank=True, max_length=80)),
                ("decision_reason", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_approvals", to="tenant.company")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approvals", to="payrollops.payrollrun")),
            ],
            options={"db_table": "payroll_approval"},
        ),
        migrations.CreateModel(
            name="PayrollExportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("export_type_code", models.CharField(max_length=100)),
                ("provider_code", models.CharField(blank=True, max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("object_key", models.CharField(blank=True, max_length=500)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("released_by_public_id", models.UUIDField(blank=True, null=True)),
                ("metadata", models.JSONField(default=dict)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payroll_export_batches", to="tenant.company")),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="export_batches", to="payrollops.payrollrun")),
            ],
            options={"db_table": "payroll_export_batch"},
        ),
        migrations.AddConstraint(model_name="payrollperiod", constraint=models.UniqueConstraint(fields=("company", "code"), name="payperiod_company_code_uq")),
        migrations.AddConstraint(model_name="payrollperiod", constraint=models.CheckConstraint(condition=models.Q(("ends_on__gte", models.F("starts_on"))), name="payperiod_date_range_ck")),
        migrations.AddConstraint(model_name="payrollperiod", constraint=models.CheckConstraint(condition=models.Q(("payment_due_on__gte", models.F("ends_on"))), name="payperiod_due_date_ck")),
        migrations.AddIndex(model_name="payrollperiod", index=models.Index(fields=["company", "starts_on", "ends_on"], name="payperiod_company_dates_idx")),
        migrations.AddIndex(model_name="payrollperiod", index=models.Index(fields=["company", "status_code"], name="payperiod_status_idx")),
        migrations.AddConstraint(model_name="payrollpolicyversion", constraint=models.UniqueConstraint(fields=("company", "code", "version"), name="paypol_company_code_ver_uq")),
        migrations.AddConstraint(model_name="payrollpolicyversion", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="paypol_effective_range_ck")),
        migrations.AddConstraint(model_name="payrollpolicyversion", constraint=models.CheckConstraint(condition=models.Q(("retired_at__isnull", True), ("published_at__isnull", False), _connector="OR"), name="paypol_retired_publish_ck")),
        migrations.AddIndex(model_name="payrollpolicyversion", index=models.Index(fields=["company", "code", "status_code"], name="paypol_company_status_idx")),
        migrations.AddIndex(model_name="payrollpolicyversion", index=models.Index(fields=["company", "effective_from", "effective_to"], name="paypol_effective_idx")),
        migrations.AddConstraint(model_name="paycomponentdefinition", constraint=models.UniqueConstraint(fields=("company", "code", "version"), name="paycomp_company_code_ver_uq")),
        migrations.AddConstraint(model_name="paycomponentdefinition", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="paycomp_effective_range_ck")),
        migrations.AddIndex(model_name="paycomponentdefinition", index=models.Index(fields=["company", "code", "is_active"], name="paycomp_lookup_idx")),
        migrations.AddConstraint(model_name="compensationassignment", constraint=models.UniqueConstraint(fields=("company", "employee_public_id", "effective_from"), name="payassign_employee_from_uq")),
        migrations.AddConstraint(model_name="compensationassignment", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="payassign_effective_range_ck")),
        migrations.AddConstraint(model_name="compensationassignment", constraint=models.CheckConstraint(condition=models.Q(("annualized_cost__gte", 0)), name="payassign_cost_nonneg_ck")),
        migrations.AddIndex(model_name="compensationassignment", index=models.Index(fields=["company", "employee_public_id", "effective_from"], name="payassign_employee_idx")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.UniqueConstraint(fields=("period", "run_number"), name="payrun_period_number_uq")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=models.Q(("gross_amount__gte", 0), ("deduction_amount__gte", 0), ("employer_cost_amount__gte", 0), ("net_amount__gte", 0)), name="payrun_amounts_nonneg_ck")),
        migrations.AddConstraint(model_name="payrollrun", constraint=models.CheckConstraint(condition=models.Q(("net_amount", models.F("gross_amount") - models.F("deduction_amount"))), name="payrun_net_formula_ck")),
        migrations.AddIndex(model_name="payrollrun", index=models.Index(fields=["company", "status_code", "created_at"], name="payrun_company_status_idx")),
        migrations.AddIndex(model_name="payrollrun", index=models.Index(fields=["company", "period", "run_number"], name="payrun_period_lookup_idx")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.UniqueConstraint(fields=("run", "employee_public_id"), name="payline_run_employee_uq")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=models.Q(("gross_amount__gte", 0), ("deduction_amount__gte", 0), ("employer_cost_amount__gte", 0), ("net_amount__gte", 0)), name="payline_amounts_nonneg_ck")),
        migrations.AddConstraint(model_name="payrollrunline", constraint=models.CheckConstraint(condition=models.Q(("net_amount", models.F("gross_amount") - models.F("deduction_amount"))), name="payline_net_formula_ck")),
        migrations.AddIndex(model_name="payrollrunline", index=models.Index(fields=["company", "employee_public_id", "created_at"], name="payline_employee_idx")),
        migrations.AddIndex(model_name="payrollrunline", index=models.Index(fields=["company", "status_code"], name="payline_status_idx")),
        migrations.AddIndex(model_name="payrollexception", index=models.Index(fields=["company", "status_code", "severity_code"], name="payexc_status_severity_idx")),
        migrations.AddIndex(model_name="payrollexception", index=models.Index(fields=["company", "due_at", "resolved_at"], name="payexc_due_idx")),
        migrations.AddConstraint(model_name="payrollapproval", constraint=models.UniqueConstraint(fields=("run", "step_code"), name="payapproval_run_step_uq")),
        migrations.AddIndex(model_name="payrollapproval", index=models.Index(fields=["company", "status_code", "requested_at"], name="payapproval_status_idx")),
        migrations.AddIndex(model_name="payrollapproval", index=models.Index(fields=["company", "due_at", "decided_at"], name="payapproval_due_idx")),
        migrations.AddConstraint(model_name="payrollexportbatch", constraint=models.UniqueConstraint(fields=("run", "export_type_code", "provider_code"), name="payexport_run_type_uq")),
        migrations.AddIndex(model_name="payrollexportbatch", index=models.Index(fields=["company", "status_code", "created_at"], name="payexport_status_idx")),
    ]
