import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial"), ("salesops", "0003_seed_defaults")]

    operations = [
        migrations.CreateModel(
            name="LandPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("due_diligence_target_days", models.PositiveIntegerField(default=45)),
                ("approval_alert_days", models.PositiveIntegerField(default=60)),
                ("minimum_margin_percent", models.DecimalField(decimal_places=4, default=Decimal("15.0000"), max_digits=7)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_acquisition_policies", to="tenant.company")),
            ],
            options={
                "db_table": "landops_policy",
                "indexes": [models.Index(fields=["company", "status_code"], name="land_policy_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "version"), name="land_policy_ver_uq"),
                    models.CheckConstraint(condition=models.Q(effective_to__isnull=True) | models.Q(effective_from__isnull=True) | models.Q(effective_to__gt=models.F("effective_from")), name="land_policy_dates_ck"),
                    models.CheckConstraint(condition=models.Q(minimum_margin_percent__gte=0), name="land_policy_margin_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="LandParcel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("parcel_code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("parcel_type_code", models.CharField(default="FREEHOLD", max_length=60)),
                ("jurisdiction_code", models.CharField(blank=True, max_length=80)),
                ("survey_reference", models.CharField(blank=True, max_length=160)),
                ("title_reference", models.CharField(blank=True, max_length=160)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("gross_area", models.DecimalField(decimal_places=3, max_digits=18)),
                ("usable_area", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("area_unit_code", models.CharField(default="SQ_M", max_length=30)),
                ("zoning_code", models.CharField(blank=True, max_length=80)),
                ("current_use_code", models.CharField(blank=True, max_length=80)),
                ("latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("status_code", models.CharField(default="PROSPECT", max_length=30)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_parcels", to="tenant.company")),
            ],
            options={
                "db_table": "landops_parcel",
                "indexes": [
                    models.Index(fields=["company", "status_code"], name="land_parcel_status_idx"),
                    models.Index(fields=["company", "jurisdiction_code"], name="land_parcel_juris_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "parcel_code"), name="land_parcel_code_uq"),
                    models.CheckConstraint(condition=models.Q(gross_area__gt=0), name="land_parcel_area_ck"),
                    models.CheckConstraint(condition=models.Q(usable_area__isnull=True) | models.Q(usable_area__gte=0), name="land_parcel_usable_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="OwnershipInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_name", models.CharField(max_length=240)),
                ("owner_type_code", models.CharField(default="INDIVIDUAL", max_length=60)),
                ("share_percent", models.DecimalField(decimal_places=4, default=Decimal("100.0000"), max_digits=7)),
                ("ownership_document_reference", models.CharField(blank=True, max_length=240)),
                ("encumbrance_flag", models.BooleanField(default=False)),
                ("encumbrance_summary", models.TextField(blank=True)),
                ("verification_status_code", models.CharField(default="PENDING", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_ownership_interests", to="tenant.company")),
                ("parcel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="ownership_interests", to="landops.landparcel")),
            ],
            options={
                "db_table": "landops_owner",
                "indexes": [models.Index(fields=["company", "verification_status_code"], name="land_owner_verify_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("parcel", "owner_name"), name="land_owner_name_uq"),
                    models.CheckConstraint(condition=models.Q(share_percent__gt=0) & models.Q(share_percent__lte=100), name="land_owner_share_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="DueDiligenceCase",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_number", models.CharField(max_length=80)),
                ("category_code", models.CharField(default="TITLE", max_length=60)),
                ("opened_on", models.DateField()),
                ("target_on", models.DateField(blank=True, null=True)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("risk_rating_code", models.CharField(default="MEDIUM", max_length=30)),
                ("findings", models.JSONField(blank=True, default=list)),
                ("blockers", models.JSONField(blank=True, default=list)),
                ("created_by_public_id", models.UUIDField()),
                ("reviewed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_due_diligence_cases", to="tenant.company")),
                ("parcel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="due_diligence_cases", to="landops.landparcel")),
            ],
            options={
                "db_table": "landops_diligence",
                "indexes": [
                    models.Index(fields=["company", "status_code", "target_on"], name="land_dd_status_idx"),
                    models.Index(fields=["company", "risk_rating_code"], name="land_dd_risk_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("company", "case_number"), name="land_dd_case_uq")],
            },
        ),
        migrations.CreateModel(
            name="FeasibilityScenario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("scenario_code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("scenario_type_code", models.CharField(default="BASE_CASE", max_length=60)),
                ("gross_development_area", models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ("saleable_area", models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ("area_unit_code", models.CharField(default="SQ_M", max_length=30)),
                ("planned_units", models.PositiveIntegerField(default=0)),
                ("estimated_revenue", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("land_cost", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("construction_cost", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("soft_cost", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("finance_cost", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("contingency_cost", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("projected_margin_percent", models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ("irr_percent", models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("assumptions", models.JSONField(blank=True, default=dict)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_feasibility_scenarios", to="tenant.company")),
                ("parcel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="feasibility_scenarios", to="landops.landparcel")),
            ],
            options={
                "db_table": "landops_feasibility",
                "indexes": [models.Index(fields=["company", "status_code"], name="land_feas_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("parcel", "scenario_code"), name="land_feas_code_uq"),
                    models.CheckConstraint(condition=models.Q(gross_development_area__gte=0), name="land_feas_gda_ck"),
                    models.CheckConstraint(condition=models.Q(saleable_area__gte=0), name="land_feas_sale_ck"),
                    models.CheckConstraint(condition=models.Q(estimated_revenue__gte=0), name="land_feas_revenue_ck"),
                    models.CheckConstraint(condition=models.Q(land_cost__gte=0), name="land_feas_landcost_ck"),
                    models.CheckConstraint(condition=models.Q(construction_cost__gte=0), name="land_feas_buildcost_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AcquisitionOpportunity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("opportunity_code", models.CharField(max_length=80)),
                ("seller_name", models.CharField(max_length=240)),
                ("acquisition_method_code", models.CharField(default="PURCHASE", max_length=60)),
                ("stage_code", models.CharField(default="IDENTIFIED", max_length=30)),
                ("asking_price", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("target_price", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("approved_budget", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("probability_percent", models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ("expected_close_on", models.DateField(blank=True, null=True)),
                ("sponsor_public_id", models.UUIDField(blank=True, null=True)),
                ("owner_public_id", models.UUIDField()),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_acquisition_opportunities", to="tenant.company")),
                ("feasibility", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="acquisition_opportunities", to="landops.feasibilityscenario")),
                ("parcel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="acquisition_opportunities", to="landops.landparcel")),
            ],
            options={
                "db_table": "landops_opportunity",
                "indexes": [
                    models.Index(fields=["company", "stage_code", "expected_close_on"], name="land_opp_stage_idx"),
                    models.Index(fields=["company", "parcel"], name="land_opp_parcel_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "opportunity_code"), name="land_opp_code_uq"),
                    models.CheckConstraint(condition=models.Q(probability_percent__gte=0) & models.Q(probability_percent__lte=100), name="land_opp_prob_ck"),
                    models.CheckConstraint(condition=models.Q(asking_price__isnull=True) | models.Q(asking_price__gte=0), name="land_opp_ask_ck"),
                    models.CheckConstraint(condition=models.Q(target_price__isnull=True) | models.Q(target_price__gte=0), name="land_opp_target_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommercialOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("offer_number", models.CharField(max_length=80)),
                ("offer_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("validity_until", models.DateField(blank=True, null=True)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_commercial_offers", to="tenant.company")),
                ("opportunity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="offers", to="landops.acquisitionopportunity")),
            ],
            options={
                "db_table": "landops_offer",
                "indexes": [models.Index(fields=["company", "status_code", "validity_until"], name="land_offer_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "offer_number"), name="land_offer_no_uq"),
                    models.CheckConstraint(condition=models.Q(amount__gte=0), name="land_offer_amount_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StatutoryApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approval_code", models.CharField(max_length=80)),
                ("approval_type_code", models.CharField(max_length=80)),
                ("authority_name", models.CharField(max_length=240)),
                ("application_reference", models.CharField(blank=True, max_length=160)),
                ("submitted_on", models.DateField(blank=True, null=True)),
                ("expected_on", models.DateField(blank=True, null=True)),
                ("approved_on", models.DateField(blank=True, null=True)),
                ("expiry_on", models.DateField(blank=True, null=True)),
                ("status_code", models.CharField(default="PLANNED", max_length=30)),
                ("mandatory_for_acquisition", models.BooleanField(default=False)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("evidence_reference", models.CharField(blank=True, max_length=240)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_statutory_approvals", to="tenant.company")),
                ("opportunity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="statutory_approvals", to="landops.acquisitionopportunity")),
                ("parcel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="statutory_approvals", to="landops.landparcel")),
            ],
            options={
                "db_table": "landops_approval",
                "indexes": [
                    models.Index(fields=["company", "status_code", "expiry_on"], name="land_approval_status_idx"),
                    models.Index(fields=["company", "parcel"], name="land_approval_parcel_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("company", "approval_code"), name="land_approval_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="LandRisk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("risk_number", models.CharField(max_length=80)),
                ("category_code", models.CharField(default="LEGAL", max_length=60)),
                ("severity_code", models.CharField(default="MEDIUM", max_length=30)),
                ("probability_code", models.CharField(default="POSSIBLE", max_length=30)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("mitigation_plan", models.TextField(blank=True)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("due_on", models.DateField(blank=True, null=True)),
                ("status_code", models.CharField(default="OPEN", max_length=30)),
                ("accepted_by_public_id", models.UUIDField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_acquisition_risks", to="tenant.company")),
                ("opportunity", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="risks", to="landops.acquisitionopportunity")),
                ("parcel", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_risks", to="landops.landparcel")),
            ],
            options={
                "db_table": "landops_risk",
                "indexes": [
                    models.Index(fields=["company", "status_code", "severity_code"], name="land_risk_status_idx"),
                    models.Index(fields=["company", "due_on"], name="land_risk_due_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("company", "risk_number"), name="land_risk_no_uq")],
            },
        ),
        migrations.CreateModel(
            name="AcquisitionEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type_code", models.CharField(max_length=60)),
                ("event_on", models.DateTimeField()),
                ("summary", models.CharField(max_length=500)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("recorded_by_public_id", models.UUIDField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="land_acquisition_events", to="tenant.company")),
                ("opportunity", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="events", to="landops.acquisitionopportunity")),
            ],
            options={
                "db_table": "landops_event",
                "indexes": [models.Index(fields=["company", "opportunity", "event_on"], name="land_event_opp_idx")],
            },
        ),
    ]
