"use client";

import Link from "next/link";
import { FormEvent, useMemo, useState } from "react";

export type Stage = { public_id: string; code: string; name: string; outcome: string; allowed_next_codes: string[] };
export type Vendor = { public_id:string; code:string; display_name:string; legal_name:string; stage:Stage; categories:string[]; service_regions:string[]; version:number; qualified_at:string|null };
export type PurchaseRequest = { public_id:string; request_number:string; title:string; stage:Stage; currency:string; estimated_total:string; line_count:number; version:number; created_at:string };
export type InventoryItem = { public_id:string; code:string; name:string; category_code:string; base_unit_code:string; track_inventory:boolean; is_active:boolean; version:number };
export type Warehouse = { public_id:string; code:string; name:string; location:Record<string,unknown>; is_active:boolean; version:number };
export type StockBalance = { public_id:string; item:InventoryItem; warehouse:Warehouse; quantity_on_hand:string; quantity_reserved:string; available_quantity:string; average_unit_cost:string; stock_value:string; version:number };
export type VendorSummary = { vendors:number; qualified:number; pending:number; suspended:number };
export type ProcurementSummary = { purchase_requests:number; open_rfqs:number; quotes:number; purchase_orders:number; po_value:string; unposted_receipts:number; currency:string };
export type InventorySummary = { items:number; warehouses:number; stock_positions:number; negative_positions:number; stock_value:string; currency:string };
type Company = { public_id:string; code:string; display_name:string; currency:string; timezone:string };
type Props = { company:Company; permissions:string[]; initialVendorSummary:VendorSummary; initialProcurementSummary:ProcurementSummary; initialInventorySummary:InventorySummary; initialVendors:Vendor[]; initialRequests:PurchaseRequest[]; initialItems:InventoryItem[]; initialWarehouses:Warehouse[]; initialBalances:StockBalance[] };
type ApiError = { message?:string; detail?:string };

async function api<T>(scope:"vendors"|"procurement"|"inventory", path:string, init?:RequestInit) {
  const response=await fetch(`/api/supply/${scope}/${path}`,{...init,headers:{"Content-Type":"application/json",...(init?.headers??{})}});
  const body=(await response.json().catch(()=>({}))) as T & ApiError;
  if(!response.ok) throw new Error(body.message??body.detail??"The operation could not be completed.");
  return body as T;
}
function money(value:string,currency:string){return new Intl.NumberFormat("en-IN",{style:"currency",currency,maximumFractionDigits:2}).format(Number(value||0));}
function Card({label,value}:{label:string;value:string|number}){return <article className="rounded-2xl border border-[var(--border)] bg-white p-5 shadow-sm"><p className="text-sm text-[var(--muted)]">{label}</p><p className="mt-2 text-3xl font-semibold">{value}</p></article>}

export function SupplyWorkspace(props:Readonly<Props>){
  const {company,permissions}=props;
  const [tab,setTab]=useState<"vendors"|"procurement"|"inventory">("vendors");
  const [vendors,setVendors]=useState(props.initialVendors); const [requests,setRequests]=useState(props.initialRequests); const [items,setItems]=useState(props.initialItems); const [,setWarehouses]=useState(props.initialWarehouses); const [balances,setBalances]=useState(props.initialBalances);
  const [vendorSummary,setVendorSummary]=useState(props.initialVendorSummary); const [procurementSummary,setProcurementSummary]=useState(props.initialProcurementSummary); const [inventorySummary,setInventorySummary]=useState(props.initialInventorySummary);
  const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
  const itemOptions=useMemo(()=>items.map(item=>({id:item.public_id,label:`${item.code} — ${item.name}`})),[items]);
  async function refresh(){const [vs,ps,is,v,r,i,w,b]=await Promise.all([api<VendorSummary>("vendors","summary"),api<ProcurementSummary>("procurement","summary"),api<InventorySummary>("inventory","summary"),api<{items:Vendor[]}>("vendors","items"),api<{items:PurchaseRequest[]}>("procurement","requests"),api<{items:InventoryItem[]}>("inventory","items"),api<{items:Warehouse[]}>("inventory","warehouses"),api<{items:StockBalance[]}>("inventory","balances")]);setVendorSummary(vs);setProcurementSummary(ps);setInventorySummary(is);setVendors(v.items);setRequests(r.items);setItems(i.items);setWarehouses(w.items);setBalances(b.items);}
  async function run(action:()=>Promise<void>,message:string){setBusy(true);setError("");setNotice("");try{await action();await refresh();setNotice(message);}catch(caught){setError(caught instanceof Error?caught.message:"The operation failed.");}finally{setBusy(false);}}
  async function createVendor(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(async()=>{await api("vendors","items",{method:"POST",body:JSON.stringify({code:form.get("code"),legal_name:form.get("legal_name"),display_name:form.get("display_name"),categories:String(form.get("categories")||"").split(",").map(x=>x.trim()).filter(Boolean),service_regions:String(form.get("service_regions")||"").split(",").map(x=>x.trim()).filter(Boolean)})});event.currentTarget.reset();},"Vendor registered with a configurable qualification lifecycle.");}
  async function createItem(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(async()=>{await api("inventory","items",{method:"POST",body:JSON.stringify({code:form.get("code"),name:form.get("name"),base_unit_code:form.get("base_unit_code"),category_code:form.get("category_code")})});event.currentTarget.reset();},"Inventory item created.");}
  async function createWarehouse(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);await run(async()=>{await api("inventory","warehouses",{method:"POST",body:JSON.stringify({code:form.get("code"),name:form.get("name"),location:{city:form.get("city")||""}})});event.currentTarget.reset();},"Warehouse created with tenant-safe stock controls.");}
  async function createRequest(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const item=items.find(x=>x.public_id===form.get("item_public_id"));await run(async()=>{await api("procurement","requests",{method:"POST",body:JSON.stringify({request_number:form.get("request_number"),title:form.get("title"),currency:company.currency,required_by_date:form.get("required_by_date")||null,lines:[{item_public_id:item?.public_id||null,item_code:item?.code||form.get("item_code"),description:form.get("description"),quantity:form.get("quantity"),unit_code:item?.base_unit_code||form.get("unit_code"),estimated_unit_rate:form.get("estimated_unit_rate")||"0"}]})});event.currentTarget.reset();},"Purchase request created with one controlled line and audit evidence.");}
  const tabs=[{id:"vendors",label:"Vendors"},{id:"procurement",label:"Procurement"},{id:"inventory",label:"Inventory"}] as const;
  return <main className="min-h-screen px-5 py-7 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-4 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[var(--brand)]">MPSqre Build360 · Supply spine</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Vendors, procurement and inventory</h1><p className="mt-2 text-sm text-[var(--muted)]">{company.display_name} · {company.code} · {company.timezone}</p></div><div className="flex flex-wrap gap-3"><span className="rounded-full bg-emerald-50 px-3 py-2 text-xs font-semibold uppercase text-emerald-900">Phase 6 active</span><Link className="rounded-lg border border-[var(--border)] bg-white px-4 py-2 text-sm font-semibold" href="/delivery">Delivery</Link><Link className="rounded-lg border border-[var(--border)] bg-white px-4 py-2 text-sm font-semibold" href="/platform">Platform</Link></div></header>
    {(error||notice)&&<div className={`mt-5 rounded-xl border p-4 text-sm ${error?"border-red-200 bg-red-50 text-red-800":"border-emerald-200 bg-emerald-50 text-emerald-900"}`}>{error||notice}</div>}
    <section className="grid gap-4 py-7 sm:grid-cols-2 xl:grid-cols-6"><Card label="Vendors" value={vendorSummary.vendors}/><Card label="Qualified" value={vendorSummary.qualified}/><Card label="Purchase requests" value={procurementSummary.purchase_requests}/><Card label="Open RFQs" value={procurementSummary.open_rfqs}/><Card label="PO value" value={money(procurementSummary.po_value,company.currency)}/><Card label="Stock value" value={money(inventorySummary.stock_value,company.currency)}/></section>
    <nav className="mb-6 flex gap-2 overflow-x-auto">{tabs.map(x=><button key={x.id} onClick={()=>setTab(x.id)} className={`rounded-lg px-4 py-2 text-sm font-semibold ${tab===x.id?"bg-[var(--brand)] text-white":"border border-[var(--border)] bg-white"}`}>{x.label}</button>)}</nav>
    {tab==="vendors"&&<section className="grid gap-6 lg:grid-cols-[380px_1fr]"><form onSubmit={createVendor} className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Register vendor</h2><div className="mt-5 grid gap-4"><input name="code" required placeholder="Vendor code"/><input name="legal_name" required placeholder="Legal name"/><input name="display_name" required placeholder="Display name"/><input name="categories" placeholder="Categories, comma separated"/><input name="service_regions" placeholder="Service regions, comma separated"/><button disabled={busy||!permissions.includes("vendor.vendor.manage")} className="rounded-lg bg-[var(--brand)] px-4 py-3 font-semibold text-white">Create vendor</button></div></form><article className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Vendor register</h2><div className="mt-4 divide-y divide-[var(--border)]">{vendors.map(v=><div key={v.public_id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-semibold">{v.code} · {v.display_name}</p><p className="text-sm text-[var(--muted)]">{v.legal_name}</p></div><span className="text-xs font-semibold uppercase text-[var(--brand)]">{v.stage.name}</span></div>)}{!vendors.length&&<p className="py-5 text-sm text-[var(--muted)]">No vendors registered.</p>}</div></article></section>}
    {tab==="procurement"&&<section className="grid gap-6 lg:grid-cols-[420px_1fr]"><form onSubmit={createRequest} className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Create purchase request</h2><div className="mt-5 grid gap-4"><input name="request_number" required placeholder="Request number"/><input name="title" required placeholder="Request title"/><select name="item_public_id" defaultValue=""><option value="">Select inventory item</option>{itemOptions.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select><input name="item_code" placeholder="Item code when not catalogued"/><input name="description" required placeholder="Line description"/><div className="grid grid-cols-2 gap-3"><input name="quantity" required type="number" min="0.0001" step="0.0001" placeholder="Quantity"/><input name="unit_code" placeholder="Unit"/></div><input name="estimated_unit_rate" type="number" min="0" step="0.01" placeholder="Estimated unit rate"/><input name="required_by_date" type="date"/><button disabled={busy||!permissions.includes("procurement.request.manage")} className="rounded-lg bg-[var(--brand)] px-4 py-3 font-semibold text-white">Create request</button></div></form><article className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Purchase requests</h2><div className="mt-4 divide-y divide-[var(--border)]">{requests.map(r=><div key={r.public_id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-semibold">{r.request_number} · {r.title}</p><p className="text-sm text-[var(--muted)]">{r.line_count} line · {money(r.estimated_total,r.currency)}</p></div><span className="text-xs font-semibold uppercase text-[var(--brand)]">{r.stage.name}</span></div>)}{!requests.length&&<p className="py-5 text-sm text-[var(--muted)]">No purchase requests created.</p>}</div></article></section>}
    {tab==="inventory"&&<section className="grid gap-6 lg:grid-cols-2"><form onSubmit={createItem} className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Create inventory item</h2><div className="mt-5 grid gap-4"><input name="code" required placeholder="Item code"/><input name="name" required placeholder="Item name"/><input name="category_code" placeholder="Category code"/><input name="base_unit_code" required placeholder="Base unit, e.g. nos, kg, m3"/><button disabled={busy||!permissions.includes("inventory.item.manage")} className="rounded-lg bg-[var(--brand)] px-4 py-3 font-semibold text-white">Create item</button></div></form><form onSubmit={createWarehouse} className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Create warehouse</h2><div className="mt-5 grid gap-4"><input name="code" required placeholder="Warehouse code"/><input name="name" required placeholder="Warehouse name"/><input name="city" placeholder="City / site"/><button disabled={busy||!permissions.includes("inventory.warehouse.manage")} className="rounded-lg bg-[var(--brand)] px-4 py-3 font-semibold text-white">Create warehouse</button></div></form><article className="rounded-2xl border border-[var(--border)] bg-white p-6 shadow-sm lg:col-span-2"><h2 className="text-xl font-semibold">Stock positions</h2><div className="mt-4 overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Warehouse</th><th className="p-3">Item</th><th className="p-3">On hand</th><th className="p-3">Available</th><th className="p-3">Value</th></tr></thead><tbody>{balances.map(b=><tr key={b.public_id} className="border-b"><td className="p-3">{b.warehouse.code}</td><td className="p-3">{b.item.code} · {b.item.name}</td><td className="p-3">{b.quantity_on_hand}</td><td className="p-3">{b.available_quantity}</td><td className="p-3">{money(b.stock_value,company.currency)}</td></tr>)}</tbody></table>{!balances.length&&<p className="py-5 text-sm text-[var(--muted)]">No stock movements posted yet.</p>}</div></article></section>}
  </div></main>;
}
