import decimal
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("tenant", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="CommercialPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField()),
                ("status_code", models.CharField(max_length=80)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(default=dict)),
                ("change_note", models.TextField(blank=True)),
                ("created_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("published_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commercial_policy_versions", to="tenant.company")),
            ],
            options={
                "db_table": "commercialops_policy_version",
                "indexes": [models.Index(fields=["company", "code", "published_at", "retired_at"], name="cops_pol_active_ix")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code", "version"), name="cops_pol_code_ver_uq"),
                    models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="cops_pol_range_ck"),
                    models.CheckConstraint(condition=models.Q(("retired_at__isnull", True), ("published_at__isnull", False), _connector="OR"), name="cops_pol_retire_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommercialContract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contract_number", models.CharField(max_length=120)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("parent_contract_public_id", models.UUIDField(blank=True, null=True)),
                ("counterparty_public_id", models.UUIDField(blank=True, null=True)),
                ("counterparty_name", models.CharField(max_length=250)),
                ("contract_type_code", models.CharField(max_length=100)),
                ("procurement_route_code", models.CharField(blank=True, max_length=100)),
                ("title", models.CharField(max_length=300)),
                ("status_code", models.CharField(max_length=80)),
                ("currency_code", models.CharField(max_length=3)),
                ("original_value", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("approved_variation_value", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("current_contract_value", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("retention_percent", models.DecimalField(decimal_places=4, default=decimal.Decimal("0"), max_digits=7)),
                ("start_date", models.DateField()),
                ("planned_completion_date", models.DateField()),
                ("actual_completion_date", models.DateField(blank=True, null=True)),
                ("owner_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("attributes", models.JSONField(default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commercial_contracts", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="contracts", to="commercialops.commercialpolicyversion")),
            ],
            options={
                "db_table": "commercialops_contract",
                "indexes": [
                    models.Index(fields=["company", "status_code", "planned_completion_date"], name="cops_con_status_ix"),
                    models.Index(fields=["company", "project_public_id", "contract_type_code"], name="cops_con_project_ix"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "contract_number"), name="cops_con_number_uq"),
                    models.CheckConstraint(condition=models.Q(("original_value__gte", 0)), name="cops_con_orig_ck"),
                    models.CheckConstraint(condition=models.Q(("approved_variation_value__gte", 0)), name="cops_con_var_ck"),
                    models.CheckConstraint(condition=models.Q(("current_contract_value__gte", 0)), name="cops_con_curr_ck"),
                    models.CheckConstraint(condition=models.Q(("retention_percent__gte", 0), ("retention_percent__lte", 100)), name="cops_con_ret_ck"),
                    models.CheckConstraint(condition=models.Q(("planned_completion_date__gte", models.F("start_date"))), name="cops_con_dates_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractMilestone",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("milestone_number", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=300)),
                ("status_code", models.CharField(max_length=80)),
                ("due_date", models.DateField()),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("currency_code", models.CharField(max_length=3)),
                ("milestone_value", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("weight_percent", models.DecimalField(decimal_places=4, default=decimal.Decimal("0"), max_digits=7)),
                ("evidence_reference", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commercial_milestones", to="tenant.company")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="milestones", to="commercialops.commercialcontract")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="milestones", to="commercialops.commercialpolicyversion")),
            ],
            options={
                "db_table": "commercialops_milestone",
                "indexes": [models.Index(fields=["company", "status_code", "due_date"], name="cops_mile_due_ix")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "contract", "milestone_number"), name="cops_milestone_uq"),
                    models.CheckConstraint(condition=models.Q(("milestone_value__gte", 0)), name="cops_mile_value_ck"),
                    models.CheckConstraint(condition=models.Q(("weight_percent__gte", 0), ("weight_percent__lte", 100)), name="cops_mile_weight_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="VariationOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("variation_number", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=300)),
                ("reason_code", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("currency_code", models.CharField(max_length=3)),
                ("submitted_value", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("approved_value", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("time_impact_days", models.IntegerField(default=0)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decision_due_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("requested_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("decided_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commercial_variations", to="tenant.company")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="variations", to="commercialops.commercialcontract")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="variations", to="commercialops.commercialpolicyversion")),
            ],
            options={
                "db_table": "commercialops_variation",
                "indexes": [models.Index(fields=["company", "status_code", "decision_due_at"], name="cops_var_status_ix")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "contract", "variation_number"), name="cops_var_number_uq"),
                    models.CheckConstraint(condition=models.Q(("submitted_value__gte", 0)), name="cops_var_sub_ck"),
                    models.CheckConstraint(condition=models.Q(("approved_value__isnull", True), ("approved_value__gte", 0), _connector="OR"), name="cops_var_appr_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("application_number", models.CharField(max_length=120)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("status_code", models.CharField(max_length=80)),
                ("currency_code", models.CharField(max_length=3)),
                ("gross_claimed", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("certified_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("retention_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("deduction_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("net_payable", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("certification_due_at", models.DateTimeField(blank=True, null=True)),
                ("certified_at", models.DateTimeField(blank=True, null=True)),
                ("applicant_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("certifier_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commercial_payments", to="tenant.company")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="commercialops.commercialcontract")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="payments", to="commercialops.commercialpolicyversion")),
            ],
            options={
                "db_table": "commercialops_payment",
                "indexes": [models.Index(fields=["company", "status_code", "certification_due_at"], name="cops_pay_status_ix")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "contract", "application_number"), name="cops_pay_number_uq"),
                    models.CheckConstraint(condition=models.Q(("period_end__gte", models.F("period_start"))), name="cops_pay_period_ck"),
                    models.CheckConstraint(condition=models.Q(("gross_claimed__gte", 0)), name="cops_pay_gross_ck"),
                    models.CheckConstraint(condition=models.Q(("certified_amount__isnull", True), ("certified_amount__gte", 0), _connector="OR"), name="cops_pay_cert_ck"),
                    models.CheckConstraint(condition=models.Q(("retention_amount__gte", 0)), name="cops_pay_ret_ck"),
                    models.CheckConstraint(condition=models.Q(("deduction_amount__gte", 0)), name="cops_pay_ded_ck"),
                    models.CheckConstraint(condition=models.Q(("net_payable__isnull", True), ("net_payable__gte", 0), _connector="OR"), name="cops_pay_net_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommercialClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_number", models.CharField(max_length=120)),
                ("claim_type_code", models.CharField(max_length=100)),
                ("priority_code", models.CharField(max_length=80)),
                ("cause_code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=300)),
                ("status_code", models.CharField(max_length=80)),
                ("currency_code", models.CharField(max_length=3)),
                ("claimed_amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=20)),
                ("assessed_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ("event_date", models.DateField()),
                ("notice_date", models.DateField(blank=True, null=True)),
                ("response_due_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("claimant_party_public_id", models.UUIDField(blank=True, null=True)),
                ("owner_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commercial_claims", to="tenant.company")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="claims", to="commercialops.commercialcontract")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="claims", to="commercialops.commercialpolicyversion")),
            ],
            options={
                "db_table": "commercialops_claim",
                "indexes": [
                    models.Index(fields=["company", "status_code", "response_due_at"], name="cops_claim_status_ix"),
                    models.Index(fields=["company", "priority_code", "event_date"], name="cops_claim_priority_ix"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "contract", "claim_number"), name="cops_claim_number_uq"),
                    models.CheckConstraint(condition=models.Q(("claimed_amount__gte", 0)), name="cops_claim_value_ck"),
                    models.CheckConstraint(condition=models.Q(("assessed_amount__isnull", True), ("assessed_amount__gte", 0), _connector="OR"), name="cops_claim_assess_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExtensionOfTime",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("eot_number", models.CharField(max_length=120)),
                ("reason_code", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("requested_days", models.PositiveIntegerField(default=0)),
                ("assessed_days", models.PositiveIntegerField(blank=True, null=True)),
                ("approved_days", models.PositiveIntegerField(blank=True, null=True)),
                ("impact_start_date", models.DateField(blank=True, null=True)),
                ("impact_end_date", models.DateField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decision_due_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("requested_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("decided_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("claim", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="eot_requests", to="commercialops.commercialclaim")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commercial_eot_requests", to="tenant.company")),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="eot_requests", to="commercialops.commercialcontract")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="eot_requests", to="commercialops.commercialpolicyversion")),
            ],
            options={
                "db_table": "commercialops_eot",
                "indexes": [models.Index(fields=["company", "status_code", "decision_due_at"], name="cops_eot_status_ix")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "contract", "eot_number"), name="cops_eot_number_uq"),
                    models.CheckConstraint(condition=models.Q(("impact_end_date__isnull", True), ("impact_start_date__isnull", True), ("impact_end_date__gte", models.F("impact_start_date")), _connector="OR"), name="cops_eot_impact_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommercialApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type_code", models.CharField(max_length=100)),
                ("entity_public_id", models.UUIDField()),
                ("step_code", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("requested_by_membership_public_id", models.UUIDField()),
                ("approver_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("requested_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_code", models.CharField(blank=True, max_length=80)),
                ("reason", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commercial_approvals", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approvals", to="commercialops.commercialpolicyversion")),
            ],
            options={
                "db_table": "commercialops_approval",
                "indexes": [models.Index(fields=["company", "status_code", "due_at"], name="cops_approval_due_ix")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "entity_type_code", "entity_public_id", "step_code"), name="cops_approval_step_uq"),
                    models.CheckConstraint(condition=models.Q(("decided_at__isnull", True), models.Q(("decision_code", ""), _negated=True), _connector="OR"), name="cops_approval_dec_ck"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommercialRisk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linked_entity_type_code", models.CharField(max_length=100)),
                ("linked_entity_public_id", models.UUIDField(blank=True, null=True)),
                ("risk_code", models.CharField(max_length=100)),
                ("severity_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("message", models.TextField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("assigned_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="commercial_risks", to="tenant.company")),
                ("contract", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="commercial_risks", to="commercialops.commercialcontract")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="risks", to="commercialops.commercialpolicyversion")),
            ],
            options={
                "db_table": "commercialops_risk",
                "indexes": [
                    models.Index(fields=["company", "status_code", "severity_code", "due_at"], name="cops_risk_open_ix"),
                    models.Index(fields=["company", "linked_entity_type_code", "linked_entity_public_id"], name="cops_risk_entity_ix"),
                ],
            },
        ),
    ]
