# Generated by Django 6.0.7 on 2026-07-30 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('build360_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_public_id', models.UUIDField(blank=True, null=True)),
                ('actor_type', models.CharField(max_length=50)),
                ('actor_public_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=200)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_public_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('request_id', models.UUIDField()),
                ('correlation_id', models.UUIDField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'platform_audit_event',
                'indexes': [models.Index(fields=['company_public_id', 'occurred_at'], name='audit_company_time_idx'), models.Index(fields=['entity_type', 'entity_public_id', 'occurred_at'], name='audit_entity_time_idx'), models.Index(fields=['actor_public_id', 'occurred_at'], name='audit_actor_time_idx'), models.Index(fields=['correlation_id'], name='audit_correlation_idx')],
            },
        ),
    ]
