# Generated for MPSqre Build360 Phase 14.
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [
        ("identity", "0014_phase14_integration_permissions"),
        ("tenant", "0001_initial"),
    ]
    operations = [
        migrations.CreateModel(
            name="LocalizationPack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("country_code", models.CharField(max_length=2)),
                ("locale", models.CharField(max_length=35)),
                ("currency", models.CharField(max_length=3)),
                ("timezone", models.CharField(max_length=64)),
                ("unit_system_code", models.CharField(max_length=50)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=50)),
                ("time_format", models.CharField(default="24h", max_length=20)),
                ("number_format", models.JSONField(default=dict)),
                ("address_schema", models.JSONField(default=dict)),
                ("tax_schema", models.JSONField(default=dict)),
                ("terminology", models.JSONField(default=dict)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published"), ("RETIRED", "Retired")], default="DRAFT", max_length=20)),
                ("is_default", models.BooleanField(default=False)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="localization_packs", to="tenant.company")),
            ],
            options={
                "db_table": "integration_localization_pack",
                "ordering": ["company_id", "country_code", "code", "-version"],
                "indexes": [models.Index(fields=["company", "status", "country_code"], name="int_loc_status_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "code", "version"), name="int_loc_code_ver_uq"),
                    models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="int_loc_range_valid"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRateSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_currency", models.CharField(max_length=3)),
                ("quote_currency", models.CharField(max_length=3)),
                ("rate", models.DecimalField(decimal_places=8, max_digits=20)),
                ("effective_at", models.DateTimeField()),
                ("source_code", models.CharField(max_length=100)),
                ("checksum_sha256", models.CharField(max_length=64)),
                ("recorded_by_public_id", models.UUIDField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="exchange_rate_snapshots", to="tenant.company")),
            ],
            options={
                "db_table": "integration_exchange_rate",
                "ordering": ["-effective_at"],
                "indexes": [models.Index(fields=["company", "base_currency", "quote_currency", "effective_at"], name="int_fx_lookup_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("company", "base_currency", "quote_currency", "effective_at"), name="int_fx_pair_time_uq"),
                    models.CheckConstraint(condition=models.Q(("rate__gt", 0)), name="int_fx_rate_positive"),
                    models.CheckConstraint(condition=models.Q(("base_currency", models.F("quote_currency")), _negated=True), name="int_fx_pair_distinct"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConnectorProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("connector_type", models.CharField(choices=[("ACCOUNTING", "Accounting"), ("IDENTITY", "Identity"), ("STORAGE", "Storage"), ("COMMUNICATION", "Communication"), ("ANALYTICS", "Analytics"), ("CUSTOM", "Custom")], max_length=30)),
                ("provider_code", models.CharField(max_length=100)),
                ("direction", models.CharField(choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound"), ("BIDIRECTIONAL", "Bidirectional")], max_length=20)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("RETIRED", "Retired")], default="DRAFT", max_length=20)),
                ("base_url", models.URLField(blank=True, max_length=500)),
                ("public_config", models.JSONField(default=dict)),
                ("secret_ref", models.CharField(blank=True, max_length=500)),
                ("allowed_data_classes", models.JSONField(default=list)),
                ("health_status", models.CharField(choices=[("UNKNOWN", "Unknown"), ("HEALTHY", "Healthy"), ("DEGRADED", "Degraded"), ("UNAVAILABLE", "Unavailable")], default="UNKNOWN", max_length=20)),
                ("last_health_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_health_message", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="integration_connectors", to="tenant.company")),
            ],
            options={
                "db_table": "integration_connector_profile",
                "ordering": ["company_id", "code"],
                "indexes": [models.Index(fields=["company", "status", "connector_type"], name="int_connector_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="int_connector_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="ApiClientCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("client_key", models.CharField(max_length=100, unique=True)),
                ("secret_digest_sha256", models.CharField(max_length=64)),
                ("scopes", models.JSONField(default=list)),
                ("allowed_ip_ranges", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("SUSPENDED", "Suspended"), ("REVOKED", "Revoked"), ("EXPIRED", "Expired")], default="ACTIVE", max_length=20)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_public_id", models.UUIDField()),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="api_client_credentials", to="tenant.company")),
            ],
            options={
                "db_table": "integration_api_client",
                "ordering": ["company_id", "name"],
                "indexes": [models.Index(fields=["company", "status", "expires_at"], name="int_client_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="WebhookSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("event_code", models.CharField(max_length=200)),
                ("target_url", models.URLField(max_length=500)),
                ("status", models.CharField(choices=[("ACTIVE", "Active"), ("PAUSED", "Paused"), ("DISABLED", "Disabled")], default="PAUSED", max_length=20)),
                ("secret_ref", models.CharField(max_length=500)),
                ("headers_public", models.JSONField(default=dict)),
                ("allowed_data_classes", models.JSONField(default=list)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="webhook_subscriptions", to="tenant.company")),
            ],
            options={
                "db_table": "integration_webhook_subscription",
                "indexes": [models.Index(fields=["company", "status", "event_code"], name="int_webhook_event_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="int_webhook_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="DataMappingProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("name", models.CharField(max_length=200)),
                ("source_schema_code", models.CharField(max_length=150)),
                ("target_schema_code", models.CharField(max_length=150)),
                ("mappings", models.JSONField(default=list)),
                ("transformations", models.JSONField(default=list)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published"), ("RETIRED", "Retired")], default="DRAFT", max_length=20)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("connector", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="mapping_profiles", to="integration.connectorprofile")),
            ],
            options={
                "db_table": "integration_data_mapping",
                "indexes": [models.Index(fields=["connector", "status", "code"], name="int_mapping_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("connector", "code", "version"), name="int_mapping_code_ver_uq")],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_public_id", models.UUIDField()),
                ("event_type", models.CharField(max_length=200)),
                ("payload_digest_sha256", models.CharField(max_length=64)),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("DELIVERED", "Delivered"), ("FAILED", "Failed"), ("DEAD_LETTER", "Dead letter")], default="PENDING", max_length=20)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("response_code", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("response_digest_sha256", models.CharField(blank=True, max_length=64)),
                ("error_summary", models.CharField(blank=True, max_length=500)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("subscription", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="deliveries", to="integration.webhooksubscription")),
            ],
            options={
                "db_table": "integration_webhook_delivery",
                "indexes": [models.Index(fields=["subscription", "status", "next_retry_at"], name="int_delivery_retry_idx")],
                "constraints": [models.UniqueConstraint(fields=("subscription", "event_public_id"), name="int_webhook_event_uq")],
            },
        ),
        migrations.CreateModel(
            name="SynchronizationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("direction", models.CharField(choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound"), ("BIDIRECTIONAL", "Bidirectional")], max_length=20)),
                ("status", models.CharField(choices=[("QUEUED", "Queued"), ("RUNNING", "Running"), ("COMPLETED", "Completed"), ("PARTIAL", "Partial"), ("FAILED", "Failed"), ("CANCELLED", "Cancelled")], default="QUEUED", max_length=20)),
                ("idempotency_key", models.CharField(max_length=150)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("records_read", models.PositiveBigIntegerField(default=0)),
                ("records_written", models.PositiveBigIntegerField(default=0)),
                ("records_rejected", models.PositiveBigIntegerField(default=0)),
                ("evidence_checksum_sha256", models.CharField(blank=True, max_length=64)),
                ("error_summary", models.CharField(blank=True, max_length=500)),
                ("initiated_by_public_id", models.UUIDField()),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="synchronization_runs", to="tenant.company")),
                ("connector", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="synchronization_runs", to="integration.connectorprofile")),
                ("mapping_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="synchronization_runs", to="integration.datamappingprofile")),
            ],
            options={
                "db_table": "integration_sync_run",
                "indexes": [models.Index(fields=["company", "status", "created_at"], name="int_sync_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "idempotency_key"), name="int_sync_idempotency_uq")],
            },
        ),
    ]
