import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial=True
    dependencies=[("fieldops","0001_initial"),("projects","0001_initial"),("tenant","0001_initial")]
    operations=[
        migrations.CreateModel(name="SafetyIncident",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("incident_number",models.CharField(max_length=80)),("title",models.CharField(max_length=250)),("description",models.TextField()),("severity",models.CharField(choices=[("near_miss","Near miss"),("minor","Minor"),("major","Major"),("critical","Critical"),("fatal","Fatal")],max_length=30)),("occurred_at",models.DateTimeField()),("reported_at",models.DateTimeField()),("reported_by_membership_public_id",models.UUIDField()),("location",models.JSONField(default=dict)),("people_involved",models.JSONField(default=list)),("immediate_actions",models.TextField(blank=True)),("root_cause",models.TextField(blank=True)),("corrective_actions",models.JSONField(default=list)),("evidence_file_public_ids",models.JSONField(default=list)),("operation_id",models.UUIDField(blank=True,null=True)),("version",models.PositiveBigIntegerField(default=1)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("project",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="safety_incidents",to="projects.project")),("stage",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="safety_incidents",to="fieldops.fieldstage"))],options={"db_table":"safety_incident","constraints":[models.UniqueConstraint(fields=("company","incident_number"),name="sft_incident_number_uq"),models.UniqueConstraint(condition=models.Q(("operation_id__isnull",False)),fields=("company","operation_id"),name="sft_incident_operation_uq")],"indexes":[models.Index(fields=["company","project","stage","occurred_at"],name="sft_incident_project_idx")]}),
        migrations.CreateModel(name="SafetyObservation",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("public_id",models.UUIDField(default=uuid.uuid4,editable=False,unique=True)),("created_at",models.DateTimeField(auto_now_add=True,editable=False)),("updated_at",models.DateTimeField(auto_now=True)),("observation_number",models.CharField(max_length=80)),("observation_type",models.CharField(max_length=40)),("description",models.TextField()),("observed_at",models.DateTimeField()),("observed_by_membership_public_id",models.UUIDField()),("is_positive",models.BooleanField(default=False)),("action_required",models.BooleanField(default=False)),("due_date",models.DateField(blank=True,null=True)),("closed_at",models.DateTimeField(blank=True,null=True)),("version",models.PositiveBigIntegerField(default=1)),("company",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to="tenant.company")),("project",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="safety_observations",to="projects.project"))],options={"db_table":"safety_observation","constraints":[models.UniqueConstraint(fields=("company","observation_number"),name="sft_observation_number_uq")],"indexes":[models.Index(fields=["company","project","closed_at"],name="sft_observation_open_idx")]})
    ]
