import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="FacilityPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("preventive_horizon_days", models.PositiveIntegerField(default=90)),
                ("warranty_alert_days", models.PositiveIntegerField(default=60)),
                ("service_response_minutes", models.PositiveIntegerField(default=240)),
                ("service_resolution_minutes", models.PositiveIntegerField(default=1440)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("effective_from", models.DateTimeField(blank=True, null=True)),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_by_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facility_policies", to="tenant.company")),
            ],
            options={"db_table": "facilityops_policy"},
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("facility_type_code", models.CharField(default="BUILDING", max_length=60)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("site_reference", models.CharField(blank=True, max_length=160)),
                ("external_reference", models.CharField(blank=True, max_length=160)),
                ("address", models.JSONField(blank=True, default=dict)),
                ("timezone", models.CharField(blank=True, max_length=80)),
                ("gross_area", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("area_unit_code", models.CharField(default="SQ_M", max_length=30)),
                ("occupancy_capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("status_code", models.CharField(default="ACTIVE", max_length=30)),
                ("operational_from", models.DateField(blank=True, null=True)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="managed_facilities", to="tenant.company")),
            ],
            options={"db_table": "facilityops_facility"},
        ),
        migrations.CreateModel(
            name="FacilitySpace",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("space_type_code", models.CharField(default="ROOM", max_length=60)),
                ("floor_reference", models.CharField(blank=True, max_length=80)),
                ("area", models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ("area_unit_code", models.CharField(default="SQ_M", max_length=30)),
                ("criticality_code", models.CharField(default="NORMAL", max_length=30)),
                ("status_code", models.CharField(default="ACTIVE", max_length=30)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facility_spaces", to="tenant.company")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="spaces", to="facilityops.facility")),
                ("parent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="facilityops.facilityspace")),
            ],
            options={"db_table": "facilityops_space"},
        ),
        migrations.CreateModel(
            name="OperationalAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("asset_tag", models.CharField(max_length=100)),
                ("asset_name", models.CharField(max_length=240)),
                ("classification_code", models.CharField(max_length=80)),
                ("source_handover_public_id", models.UUIDField(blank=True, null=True)),
                ("model_element_reference", models.CharField(blank=True, max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=240)),
                ("model_number", models.CharField(blank=True, max_length=160)),
                ("serial_number", models.CharField(blank=True, max_length=160)),
                ("commissioned_on", models.DateField(blank=True, null=True)),
                ("warranty_start_on", models.DateField(blank=True, null=True)),
                ("warranty_end_on", models.DateField(blank=True, null=True)),
                ("criticality_code", models.CharField(default="NORMAL", max_length=30)),
                ("condition_code", models.CharField(default="GOOD", max_length=30)),
                ("operation_status_code", models.CharField(default="DRAFT", max_length=40)),
                ("maintainable", models.BooleanField(default=True)),
                ("service_interval_days", models.PositiveIntegerField(blank=True, null=True)),
                ("last_service_on", models.DateField(blank=True, null=True)),
                ("next_service_on", models.DateField(blank=True, null=True)),
                ("document_references", models.JSONField(blank=True, default=list)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("captured_by_public_id", models.UUIDField()),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="operational_assets", to="tenant.company")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="facilityops.facility")),
                ("space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assets", to="facilityops.facilityspace")),
            ],
            options={"db_table": "facilityops_asset"},
        ),
        migrations.CreateModel(
            name="MaintenancePlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=240)),
                ("plan_type_code", models.CharField(default="PREVENTIVE", max_length=40)),
                ("frequency_days", models.PositiveIntegerField()),
                ("lead_time_days", models.PositiveIntegerField(default=7)),
                ("next_due_date", models.DateField()),
                ("estimated_duration_minutes", models.PositiveIntegerField(default=60)),
                ("checklist", models.JSONField(blank=True, default=list)),
                ("status_code", models.CharField(default="ACTIVE", max_length=30)),
                ("owner_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="maintenance_plans", to="facilityops.operationalasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facility_maintenance_plans", to="tenant.company")),
            ],
            options={"db_table": "facilityops_plan"},
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("request_number", models.CharField(max_length=80)),
                ("category_code", models.CharField(default="GENERAL", max_length=60)),
                ("priority_code", models.CharField(default="NORMAL", max_length=30)),
                ("channel_code", models.CharField(default="PORTAL", max_length=30)),
                ("requester_public_id", models.UUIDField(blank=True, null=True)),
                ("requester_reference", models.CharField(blank=True, max_length=160)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("status_code", models.CharField(default="NEW", max_length=30)),
                ("assigned_to_public_id", models.UUIDField(blank=True, null=True)),
                ("response_due_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_due_at", models.DateTimeField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closure_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="service_requests", to="facilityops.operationalasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facility_service_requests", to="tenant.company")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="service_requests", to="facilityops.facility")),
                ("space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="service_requests", to="facilityops.facilityspace")),
            ],
            options={"db_table": "facilityops_request"},
        ),
        migrations.CreateModel(
            name="FacilityWorkOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("work_order_number", models.CharField(max_length=80)),
                ("work_type_code", models.CharField(default="CORRECTIVE", max_length=40)),
                ("priority_code", models.CharField(default="NORMAL", max_length=30)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("assigned_to_public_id", models.UUIDField(blank=True, null=True)),
                ("vendor_reference", models.CharField(blank=True, max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("scheduled_start_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_end_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("actual_cost", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("completion_evidence", models.JSONField(blank=True, default=dict)),
                ("created_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="work_orders", to="facilityops.operationalasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facility_work_orders", to="tenant.company")),
                ("plan", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="work_orders", to="facilityops.maintenanceplan")),
                ("service_request", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="work_orders", to="facilityops.servicerequest")),
            ],
            options={"db_table": "facilityops_work_order"},
        ),
        migrations.CreateModel(
            name="WarrantyClaim",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("claim_number", models.CharField(max_length=80)),
                ("supplier_reference", models.CharField(blank=True, max_length=200)),
                ("warranty_reference", models.CharField(blank=True, max_length=200)),
                ("reported_on", models.DateField()),
                ("failure_date", models.DateField(blank=True, null=True)),
                ("issue_description", models.TextField()),
                ("claimed_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("approved_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("currency_code", models.CharField(default="INR", max_length=3)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("filed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                ("settled_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("owner_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="warranty_claims", to="facilityops.operationalasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facility_warranty_claims", to="tenant.company")),
                ("work_order", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="warranty_claims", to="facilityops.facilityworkorder")),
            ],
            options={"db_table": "facilityops_warranty"},
        ),
        migrations.CreateModel(
            name="ConditionInspection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inspection_number", models.CharField(max_length=80)),
                ("inspection_type_code", models.CharField(default="CONDITION", max_length=60)),
                ("scheduled_on", models.DateField(blank=True, null=True)),
                ("inspected_on", models.DateField(blank=True, null=True)),
                ("condition_code", models.CharField(default="GOOD", max_length=30)),
                ("score", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("findings", models.TextField(blank=True)),
                ("actions_required", models.TextField(blank=True)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("status_code", models.CharField(default="DRAFT", max_length=30)),
                ("inspector_public_id", models.UUIDField()),
                ("verified_by_public_id", models.UUIDField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("asset", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="condition_inspections", to="facilityops.operationalasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facility_condition_inspections", to="tenant.company")),
                ("facility", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="condition_inspections", to="facilityops.facility")),
                ("space", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="condition_inspections", to="facilityops.facilityspace")),
            ],
            options={"db_table": "facilityops_inspection"},
        ),
        migrations.CreateModel(
            name="AssetLifecycleEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("event_type_code", models.CharField(max_length=60)),
                ("occurred_at", models.DateTimeField()),
                ("from_status_code", models.CharField(blank=True, max_length=40)),
                ("to_status_code", models.CharField(blank=True, max_length=40)),
                ("summary", models.CharField(max_length=300)),
                ("reference", models.CharField(blank=True, max_length=300)),
                ("event_metadata", models.JSONField(blank=True, default=dict)),
                ("recorded_by_public_id", models.UUIDField()),
                ("asset", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="lifecycle_events", to="facilityops.operationalasset")),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="facility_asset_events", to="tenant.company")),
            ],
            options={"db_table": "facilityops_event"},
        ),
        migrations.AddConstraint(model_name="facilitypolicyversion", constraint=models.UniqueConstraint(fields=("company", "version"), name="fac_policy_ver_uq")),
        migrations.AddConstraint(model_name="facilitypolicyversion", constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_from__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="fac_policy_dates_ck")),
        migrations.AddIndex(model_name="facilitypolicyversion", index=models.Index(fields=["company", "status_code"], name="fac_policy_status_idx")),
        migrations.AddConstraint(model_name="facility", constraint=models.UniqueConstraint(fields=("company", "code"), name="fac_facility_code_uq")),
        migrations.AddIndex(model_name="facility", index=models.Index(fields=["company", "status_code"], name="fac_facility_status_idx")),
        migrations.AddIndex(model_name="facility", index=models.Index(fields=["company", "project_public_id"], name="fac_facility_project_idx")),
        migrations.AddConstraint(model_name="facilityspace", constraint=models.UniqueConstraint(fields=("facility", "code"), name="fac_space_code_uq")),
        migrations.AddIndex(model_name="facilityspace", index=models.Index(fields=["company", "status_code"], name="fac_space_status_idx")),
        migrations.AddIndex(model_name="facilityspace", index=models.Index(fields=["company", "facility", "parent"], name="fac_space_parent_idx")),
        migrations.AddConstraint(model_name="operationalasset", constraint=models.UniqueConstraint(fields=("company", "asset_tag"), name="fac_asset_tag_uq")),
        migrations.AddConstraint(model_name="operationalasset", constraint=models.CheckConstraint(condition=models.Q(("warranty_end_on__isnull", True), ("warranty_start_on__isnull", True), ("warranty_end_on__gte", models.F("warranty_start_on")), _connector="OR"), name="fac_asset_warranty_ck")),
        migrations.AddIndex(model_name="operationalasset", index=models.Index(fields=["company", "operation_status_code", "criticality_code"], name="fac_asset_status_idx")),
        migrations.AddIndex(model_name="operationalasset", index=models.Index(fields=["company", "next_service_on"], name="fac_asset_due_idx")),
        migrations.AddConstraint(model_name="maintenanceplan", constraint=models.UniqueConstraint(fields=("company", "code"), name="fac_plan_code_uq")),
        migrations.AddIndex(model_name="maintenanceplan", index=models.Index(fields=["company", "next_due_date", "status_code"], name="fac_plan_due_idx")),
        migrations.AddIndex(model_name="maintenanceplan", index=models.Index(fields=["company", "asset", "status_code"], name="fac_plan_status_idx")),
        migrations.AddConstraint(model_name="servicerequest", constraint=models.UniqueConstraint(fields=("company", "request_number"), name="fac_request_no_uq")),
        migrations.AddIndex(model_name="servicerequest", index=models.Index(fields=["company", "status_code", "priority_code"], name="fac_request_status_idx")),
        migrations.AddIndex(model_name="servicerequest", index=models.Index(fields=["company", "resolution_due_at"], name="fac_request_due_idx")),
        migrations.AddConstraint(model_name="facilityworkorder", constraint=models.UniqueConstraint(fields=("company", "work_order_number"), name="fac_wo_no_uq")),
        migrations.AddIndex(model_name="facilityworkorder", index=models.Index(fields=["company", "status_code", "priority_code"], name="fac_wo_status_idx")),
        migrations.AddIndex(model_name="facilityworkorder", index=models.Index(fields=["company", "due_date"], name="fac_wo_due_idx")),
        migrations.AddConstraint(model_name="warrantyclaim", constraint=models.UniqueConstraint(fields=("company", "claim_number"), name="fac_claim_no_uq")),
        migrations.AddIndex(model_name="warrantyclaim", index=models.Index(fields=["company", "status_code"], name="fac_claim_status_idx")),
        migrations.AddIndex(model_name="warrantyclaim", index=models.Index(fields=["company", "reported_on"], name="fac_claim_date_idx")),
        migrations.AddConstraint(model_name="conditioninspection", constraint=models.UniqueConstraint(fields=("company", "inspection_number"), name="fac_insp_no_uq")),
        migrations.AddIndex(model_name="conditioninspection", index=models.Index(fields=["company", "status_code", "condition_code"], name="fac_insp_status_idx")),
        migrations.AddIndex(model_name="conditioninspection", index=models.Index(fields=["company", "scheduled_on"], name="fac_insp_due_idx")),
        migrations.AddIndex(model_name="assetlifecycleevent", index=models.Index(fields=["company", "asset", "occurred_at"], name="fac_event_asset_idx")),
        migrations.AddIndex(model_name="assetlifecycleevent", index=models.Index(fields=["company", "event_type_code"], name="fac_event_type_idx")),
    ]
