# Generated for MPSqre Build360 Phase 12.
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("tenant", "0001_initial")]
    operations = [
        migrations.CreateModel(
            name="RuntimeEnvironment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=60)),
                ("name", models.CharField(max_length=160)),
                ("environment_type", models.CharField(choices=[("local", "Local"), ("development", "Development"), ("staging", "Staging"), ("production", "Production"), ("disaster_recovery", "Disaster recovery")], max_length=24)),
                ("base_url", models.URLField(blank=True)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("data_residency", models.CharField(blank=True, max_length=100)),
                ("production_data_allowed", models.BooleanField(default=False)),
                ("requires_change_approval", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "adminops_runtime_environment",
                "ordering": ["environment_type", "code"],
                "indexes": [models.Index(fields=["company", "environment_type", "is_active"], name="adm_env_type_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="adm_env_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="ReleaseRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_label", models.CharField(max_length=80)),
                ("release_name", models.CharField(max_length=180)),
                ("source_revision", models.CharField(max_length=160)),
                ("artifact_sha256", models.CharField(max_length=64)),
                ("migration_plan_sha256", models.CharField(blank=True, max_length=64)),
                ("change_summary", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("validated", "Validated"), ("approved", "Approved"), ("deployed", "Deployed"), ("failed", "Failed"), ("rolled_back", "Rolled back")], default="draft", max_length=20)),
                ("requested_by_public_id", models.UUIDField()),
                ("validated_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("deployed_by_public_id", models.UUIDField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("deployed_at", models.DateTimeField(blank=True, null=True)),
                ("rollback_reference", models.CharField(blank=True, max_length=240)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="releases", to="adminops.runtimeenvironment")),
            ],
            options={
                "db_table": "adminops_release_record",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["company", "environment", "status", "created_at"], name="adm_release_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "environment", "version_label"), name="adm_release_env_ver_uq")],
            },
        ),
        migrations.CreateModel(
            name="ReleaseCheck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("category", models.CharField(choices=[("security", "Security"), ("database", "Database"), ("api", "API"), ("frontend", "Frontend"), ("recovery", "Recovery"), ("observability", "Observability"), ("governance", "Governance")], max_length=24)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("passed", "Passed"), ("failed", "Failed"), ("waived", "Waived")], default="pending", max_length=20)),
                ("is_critical", models.BooleanField(default=True)),
                ("target_value", models.CharField(blank=True, max_length=160)),
                ("measured_value", models.CharField(blank=True, max_length=160)),
                ("evidence", models.CharField(blank=True, max_length=1000)),
                ("waiver_reason", models.CharField(blank=True, max_length=500)),
                ("checked_by_public_id", models.UUIDField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("release", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="checks", to="adminops.releaserecord")),
            ],
            options={
                "db_table": "adminops_release_check",
                "ordering": ["category", "code"],
                "indexes": [models.Index(fields=["company", "status", "is_critical"], name="adm_check_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("release", "code"), name="adm_release_check_uq")],
            },
        ),
        migrations.CreateModel(
            name="ServiceObjective",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("service_code", models.CharField(max_length=100)),
                ("indicator_type", models.CharField(choices=[("availability", "Availability"), ("latency", "Latency"), ("error_rate", "Error rate"), ("queue_age", "Queue age")], max_length=20)),
                ("target_value", models.DecimalField(decimal_places=4, max_digits=12)),
                ("warning_threshold", models.DecimalField(decimal_places=4, max_digits=12)),
                ("critical_threshold", models.DecimalField(decimal_places=4, max_digits=12)),
                ("window_days", models.PositiveSmallIntegerField(default=30)),
                ("unit_code", models.CharField(default="percent", max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "adminops_service_objective",
                "ordering": ["service_code", "code"],
                "indexes": [models.Index(fields=["company", "service_code", "is_active"], name="adm_slo_service_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="adm_slo_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="HealthSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("service_code", models.CharField(max_length=100)),
                ("status", models.CharField(choices=[("healthy", "Healthy"), ("degraded", "Degraded"), ("unavailable", "Unavailable"), ("unknown", "Unknown")], max_length=20)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("observed_value", models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ("source", models.CharField(default="manual", max_length=120)),
                ("details", models.JSONField(default=dict)),
                ("checked_at", models.DateTimeField()),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="health_snapshots", to="adminops.runtimeenvironment")),
            ],
            options={
                "db_table": "adminops_health_snapshot",
                "ordering": ["-checked_at"],
                "indexes": [models.Index(fields=["company", "environment", "service_code", "checked_at"], name="adm_health_lookup_idx")],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("number", models.CharField(max_length=60)),
                ("severity", models.CharField(choices=[("sev1", "Critical"), ("sev2", "High"), ("sev3", "Medium"), ("sev4", "Low")], max_length=10)),
                ("title", models.CharField(max_length=220)),
                ("summary", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("identified", "Identified"), ("investigating", "Investigating"), ("mitigated", "Mitigated"), ("resolved", "Resolved"), ("closed", "Closed")], default="identified", max_length=20)),
                ("owner_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("detected_at", models.DateTimeField()),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("mitigated_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("customer_impact", models.TextField(blank=True)),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_actions", models.JSONField(default=list)),
                ("postmortem_required", models.BooleanField(default=False)),
                ("postmortem_reference", models.CharField(blank=True, max_length=240)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="adminops.runtimeenvironment")),
            ],
            options={
                "db_table": "adminops_incident",
                "ordering": ["-detected_at"],
                "indexes": [models.Index(fields=["company", "status", "severity", "detected_at"], name="adm_incident_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "number"), name="adm_incident_number_uq")],
            },
        ),
        migrations.CreateModel(
            name="Runbook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=220)),
                ("category", models.CharField(max_length=100)),
                ("purpose", models.TextField(blank=True)),
                ("steps", models.JSONField(default=list)),
                ("owner_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("review_due_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "adminops_runbook",
                "ordering": ["category", "code"],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="adm_runbook_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                ("is_enabled", models.BooleanField(default=False)),
                ("rollout_percent", models.PositiveSmallIntegerField(default=0)),
                ("scope", models.JSONField(default=dict)),
                ("requires_approval", models.BooleanField(default=True)),
                ("requested_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
            ],
            options={
                "db_table": "adminops_feature_flag",
                "ordering": ["code"],
                "indexes": [models.Index(fields=["company", "is_enabled"], name="adm_flag_enabled_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "code"), name="adm_flag_code_uq")],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceWindow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=220)),
                ("reason", models.TextField(blank=True)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("planned", "Planned"), ("approved", "Approved"), ("in_progress", "In progress"), ("completed", "Completed"), ("cancelled", "Cancelled")], default="planned", max_length=20)),
                ("affected_services", models.JSONField(default=list)),
                ("requested_by_public_id", models.UUIDField()),
                ("approved_by_public_id", models.UUIDField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveBigIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="tenant.company")),
                ("environment", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="maintenance_windows", to="adminops.runtimeenvironment")),
            ],
            options={
                "db_table": "adminops_maintenance_window",
                "ordering": ["-starts_at"],
                "indexes": [models.Index(fields=["company", "environment", "status", "starts_at"], name="adm_maint_status_idx")],
                "constraints": [models.UniqueConstraint(fields=("company", "reference"), name="adm_maint_ref_uq")],
            },
        ),
    ]
