# Generated for MPSqre Build360 Phase 24 HSE & Safety Operations.

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyPolicyVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=80)),
                ("name", models.CharField(max_length=200)),
                ("version", models.PositiveIntegerField()),
                ("status_code", models.CharField(max_length=80)),
                ("effective_from", models.DateTimeField()),
                ("effective_to", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("retired_at", models.DateTimeField(blank=True, null=True)),
                ("configuration", models.JSONField(default=dict)),
                ("change_note", models.TextField(blank=True)),
                ("created_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("published_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="safety_policy_versions", to="tenant.company")),
            ],
            options={"db_table": "safetyops_policy_version"},
        ),
        migrations.CreateModel(
            name="SafetyObservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("observation_code", models.CharField(max_length=80)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("location_public_id", models.UUIDField(blank=True, null=True)),
                ("category_code", models.CharField(max_length=100)),
                ("severity_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("observed_at", models.DateTimeField()),
                ("observed_by_membership_public_id", models.UUIDField()),
                ("responsible_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("closure_note", models.TextField(blank=True)),
                ("evidence_reference", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="safety_observations", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="observations", to="safetyops.safetypolicyversion")),
            ],
            options={"db_table": "safetyops_observation"},
        ),
        migrations.CreateModel(
            name="SafetyIncident",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("incident_code", models.CharField(max_length=80)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("location_public_id", models.UUIDField(blank=True, null=True)),
                ("incident_type_code", models.CharField(max_length=100)),
                ("severity_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField()),
                ("occurred_at", models.DateTimeField()),
                ("reported_at", models.DateTimeField()),
                ("reported_by_membership_public_id", models.UUIDField()),
                ("affected_people_count", models.PositiveIntegerField(default=0)),
                ("lost_time", models.BooleanField(default=False)),
                ("regulator_reportable", models.BooleanField(default=False)),
                ("immediate_action", models.TextField(blank=True)),
                ("root_cause", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("evidence_reference", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="safety_incidents", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="incidents", to="safetyops.safetypolicyversion")),
            ],
            options={"db_table": "safetyops_incident"},
        ),
        migrations.CreateModel(
            name="PermitToWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("permit_code", models.CharField(max_length=80)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("location_public_id", models.UUIDField(blank=True, null=True)),
                ("permit_type_code", models.CharField(max_length=100)),
                ("risk_level_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("work_summary", models.CharField(max_length=300)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                ("issuer_membership_public_id", models.UUIDField()),
                ("receiver_membership_public_id", models.UUIDField()),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("conditions", models.JSONField(default=list)),
                ("isolation_points", models.JSONField(default=list)),
                ("evidence_reference", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="safety_permits", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="permits", to="safetyops.safetypolicyversion")),
            ],
            options={"db_table": "safetyops_permit"},
        ),
        migrations.CreateModel(
            name="SafetyInspection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("inspection_code", models.CharField(max_length=80)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("location_public_id", models.UUIDField(blank=True, null=True)),
                ("inspection_type_code", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("result_code", models.CharField(blank=True, max_length=80)),
                ("scheduled_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("inspector_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("score_percent", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal("0.00")), django.core.validators.MaxValueValidator(Decimal("100.00"))])),
                ("checklist_result", models.JSONField(default=dict)),
                ("evidence_reference", models.CharField(blank=True, max_length=500)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="safety_inspections", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="inspections", to="safetyops.safetypolicyversion")),
            ],
            options={"db_table": "safetyops_inspection"},
        ),
        migrations.CreateModel(
            name="ToolboxTalk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("talk_code", models.CharField(max_length=80)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("location_public_id", models.UUIDField(blank=True, null=True)),
                ("topic_code", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=240)),
                ("delivered_at", models.DateTimeField()),
                ("facilitator_membership_public_id", models.UUIDField()),
                ("attendee_count", models.PositiveIntegerField(default=0)),
                ("acknowledgement_count", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("evidence_reference", models.CharField(blank=True, max_length=500)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="toolbox_talks", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="toolbox_talks", to="safetyops.safetypolicyversion")),
            ],
            options={"db_table": "safetyops_toolbox_talk"},
        ),
        migrations.CreateModel(
            name="CorrectiveAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action_code", models.CharField(max_length=80)),
                ("source_type_code", models.CharField(max_length=80)),
                ("source_public_id", models.UUIDField(blank=True, null=True)),
                ("project_public_id", models.UUIDField(blank=True, null=True)),
                ("location_public_id", models.UUIDField(blank=True, null=True)),
                ("category_code", models.CharField(max_length=100)),
                ("priority_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=240)),
                ("description", models.TextField(blank=True)),
                ("owner_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("verified_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("closure_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="safety_corrective_actions", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="corrective_actions", to="safetyops.safetypolicyversion")),
            ],
            options={"db_table": "safetyops_corrective_action"},
        ),
        migrations.CreateModel(
            name="SafetyApproval",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type_code", models.CharField(max_length=80)),
                ("entity_public_id", models.UUIDField()),
                ("step_code", models.CharField(max_length=100)),
                ("status_code", models.CharField(max_length=80)),
                ("requested_by_membership_public_id", models.UUIDField()),
                ("requested_from_membership_public_id", models.UUIDField()),
                ("requested_at", models.DateTimeField()),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="safety_approvals", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="approvals", to="safetyops.safetypolicyversion")),
            ],
            options={"db_table": "safetyops_approval"},
        ),
        migrations.CreateModel(
            name="SafetyRisk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("public_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("linked_entity_type_code", models.CharField(max_length=80)),
                ("linked_entity_public_id", models.UUIDField(blank=True, null=True)),
                ("risk_code", models.CharField(max_length=100)),
                ("severity_code", models.CharField(max_length=80)),
                ("status_code", models.CharField(max_length=80)),
                ("message", models.CharField(max_length=500)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by_membership_public_id", models.UUIDField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="safety_risks", to="tenant.company")),
                ("policy", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="risks", to="safetyops.safetypolicyversion")),
            ],
            options={"db_table": "safetyops_risk"},
        ),
        migrations.AddConstraint(
            model_name="safetypolicyversion",
            constraint=models.UniqueConstraint(fields=("company", "code", "version"), name="safe_policy_code_ver_uniq"),
        ),
        migrations.AddConstraint(
            model_name="safetypolicyversion",
            constraint=models.CheckConstraint(condition=models.Q(("effective_to__isnull", True), ("effective_to__gt", models.F("effective_from")), _connector="OR"), name="safe_policy_range_valid"),
        ),
        migrations.AddConstraint(
            model_name="safetypolicyversion",
            constraint=models.CheckConstraint(condition=models.Q(("retired_at__isnull", True), ("published_at__isnull", False), _connector="OR"), name="safe_retire_after_publish"),
        ),
        migrations.AddIndex(
            model_name="safetypolicyversion",
            index=models.Index(fields=["company", "code", "published_at", "retired_at"], name="safe_policy_active_idx"),
        ),
        migrations.AddConstraint(
            model_name="safetyobservation",
            constraint=models.UniqueConstraint(fields=("company", "observation_code"), name="safe_obs_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="safetyobservation",
            constraint=models.CheckConstraint(condition=models.Q(("closed_at__isnull", True), ("closed_at__gte", models.F("observed_at")), _connector="OR"), name="safe_obs_close_valid"),
        ),
        migrations.AddIndex(
            model_name="safetyobservation",
            index=models.Index(fields=["company", "status_code", "due_at"], name="safe_obs_status_due_idx"),
        ),
        migrations.AddIndex(
            model_name="safetyobservation",
            index=models.Index(fields=["company", "severity_code", "observed_at"], name="safe_obs_severity_idx"),
        ),
        migrations.AddConstraint(
            model_name="safetyincident",
            constraint=models.UniqueConstraint(fields=("company", "incident_code"), name="safe_inc_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="safetyincident",
            constraint=models.CheckConstraint(condition=models.Q(("reported_at__gte", models.F("occurred_at"))), name="safe_inc_report_valid"),
        ),
        migrations.AddConstraint(
            model_name="safetyincident",
            constraint=models.CheckConstraint(condition=models.Q(("closed_at__isnull", True), ("closed_at__gte", models.F("reported_at")), _connector="OR"), name="safe_inc_close_valid"),
        ),
        migrations.AddIndex(
            model_name="safetyincident",
            index=models.Index(fields=["company", "status_code", "reported_at"], name="safe_inc_status_idx"),
        ),
        migrations.AddIndex(
            model_name="safetyincident",
            index=models.Index(fields=["company", "severity_code", "reported_at"], name="safe_inc_severity_idx"),
        ),
        migrations.AddConstraint(
            model_name="permittowork",
            constraint=models.UniqueConstraint(fields=("company", "permit_code"), name="safe_permit_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="permittowork",
            constraint=models.CheckConstraint(condition=models.Q(("valid_until__gt", models.F("valid_from"))), name="safe_permit_range_valid"),
        ),
        migrations.AddIndex(
            model_name="permittowork",
            index=models.Index(fields=["company", "status_code", "valid_until"], name="safe_permit_expiry_idx"),
        ),
        migrations.AddIndex(
            model_name="permittowork",
            index=models.Index(fields=["company", "project_public_id", "location_public_id"], name="safe_permit_scope_idx"),
        ),
        migrations.AddConstraint(
            model_name="safetyinspection",
            constraint=models.UniqueConstraint(fields=("company", "inspection_code"), name="safe_insp_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="safetyinspection",
            constraint=models.CheckConstraint(condition=models.Q(("completed_at__isnull", True), ("completed_at__gte", models.F("scheduled_at")), _connector="OR"), name="safe_insp_time_valid"),
        ),
        migrations.AddConstraint(
            model_name="safetyinspection",
            constraint=models.CheckConstraint(condition=models.Q(("score_percent__isnull", True), models.Q(("score_percent__gte", 0), ("score_percent__lte", 100)), _connector="OR"), name="safe_insp_score_valid"),
        ),
        migrations.AddIndex(
            model_name="safetyinspection",
            index=models.Index(fields=["company", "status_code", "scheduled_at"], name="safe_insp_schedule_idx"),
        ),
        migrations.AddConstraint(
            model_name="toolboxtalk",
            constraint=models.UniqueConstraint(fields=("company", "talk_code"), name="safe_talk_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="toolboxtalk",
            constraint=models.CheckConstraint(condition=models.Q(("acknowledgement_count__lte", models.F("attendee_count"))), name="safe_talk_ack_valid"),
        ),
        migrations.AddIndex(
            model_name="toolboxtalk",
            index=models.Index(fields=["company", "delivered_at"], name="safe_talk_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="correctiveaction",
            constraint=models.UniqueConstraint(fields=("company", "action_code"), name="safe_action_code_uniq"),
        ),
        migrations.AddConstraint(
            model_name="correctiveaction",
            constraint=models.CheckConstraint(condition=models.Q(("verified_at__isnull", True), ("completed_at__isnull", False), _connector="OR"), name="safe_action_verify_valid"),
        ),
        migrations.AddIndex(
            model_name="correctiveaction",
            index=models.Index(fields=["company", "status_code", "due_at"], name="safe_action_due_idx"),
        ),
        migrations.AddIndex(
            model_name="correctiveaction",
            index=models.Index(fields=["company", "source_type_code", "source_public_id"], name="safe_action_source_idx"),
        ),
        migrations.AddConstraint(
            model_name="safetyapproval",
            constraint=models.UniqueConstraint(fields=("company", "entity_type_code", "entity_public_id", "step_code"), name="safe_approval_step_uniq"),
        ),
        migrations.AddConstraint(
            model_name="safetyapproval",
            constraint=models.CheckConstraint(condition=models.Q(("decided_at__isnull", True), ("decided_by_membership_public_id__isnull", False), _connector="OR"), name="safe_approval_dec_valid"),
        ),
        migrations.AddIndex(
            model_name="safetyapproval",
            index=models.Index(fields=["company", "status_code", "due_at"], name="safe_approval_due_idx"),
        ),
        migrations.AddConstraint(
            model_name="safetyrisk",
            constraint=models.CheckConstraint(condition=models.Q(("resolved_at__isnull", True), ("resolved_by_membership_public_id__isnull", False), _connector="OR"), name="safe_risk_resolve_valid"),
        ),
        migrations.AddIndex(
            model_name="safetyrisk",
            index=models.Index(fields=["company", "status_code", "severity_code"], name="safe_risk_status_idx"),
        ),
        migrations.AddIndex(
            model_name="safetyrisk",
            index=models.Index(fields=["company", "linked_entity_type_code", "linked_entity_public_id"], name="safe_risk_entity_idx"),
        ),
    ]
