"use client";

import type { Route } from "next";
import Link from "next/link";

export type ExecutivePayload = {
  generated_at: string;
  summary: { active_projects: number; projects_with_attention: number; schedule_attention: number; approved_budget: string; currency: string };
  finance: { client_invoiced: string; client_outstanding: string; vendor_invoiced: string; currency: string } | null;
  history_available: boolean;
  history: {
    public_id: string; code: string; as_of_date: string; projects_total: number; projects_healthy: number;
    projects_at_risk: number; projects_critical: number; schedule_performance_percent: string;
    cost_performance_percent: string; portfolio_value: string; currency: string; narrative: string;
  }[];
  snapshot_prefill: null | {
    as_of_date: string; projects_total: number; projects_healthy: number; projects_at_risk: number;
    projects_critical: number; schedule_performance_percent: string; portfolio_value: string;
    currency: string; cost_performance_percent: null; note: string;
  };
  projects: {
    public_id: string; code: string; name: string; stage_name: string; planned_end_date: string | null; approved_budget: string; currency: string;
    progress_percent: number; task_count: number; completed_tasks: number; overdue_tasks: number; open_ncrs: number | null; safety_incidents_30d: number | null;
    client_invoiced: string | null; client_outstanding: string | null; vendor_invoiced: string | null; health: "CRITICAL" | "ATTENTION" | "ON_TRACK"; href: Route;
  }[];
};

const healthStyle: Record<string, string> = {
  CRITICAL: "bg-red-50 text-red-800 border-red-200",
  ATTENTION: "bg-amber-50 text-amber-900 border-amber-200",
  ON_TRACK: "bg-emerald-50 text-emerald-800 border-emerald-200",
};
const money = (currency: string, value: string) => new Intl.NumberFormat("en-IN", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(value));

export function ExecutiveWorkspace({ payload }: Readonly<{ payload: ExecutivePayload }>) {
  return <main className="min-h-screen bg-[var(--background)] px-4 py-6 sm:px-7 lg:px-10"><div className="mx-auto max-w-[1550px] space-y-6">
    <header className="overflow-hidden rounded-[30px] border border-[var(--border)] bg-white shadow-sm"><div className="grid gap-6 p-6 lg:grid-cols-[1.15fr_.85fr] lg:p-8"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--brand)]">Executive portfolio</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">See where leadership attention is needed — not just where charts are green.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[var(--muted)]">Project health is derived from governed tasks, schedule, quality, safety and finance only when your permissions allow those records.</p>{payload.snapshot_prefill ? <div className="mt-5 rounded-2xl border border-[var(--border)] bg-slate-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[var(--brand)]">Snapshot drafting assistant</p><p className="mt-1 text-xs text-[var(--muted)]">{payload.snapshot_prefill.note}</p></div><Link className="rounded-xl border border-[var(--border)] bg-white px-3 py-2 text-xs font-semibold text-[var(--brand)]" href="/platform/executive-intelligence">Open governed snapshot editor →</Link></div><div className="mt-3 flex flex-wrap gap-2 text-[10px] text-[var(--muted)]"><span>{payload.snapshot_prefill.projects_total} projects</span><span>·</span><span>Schedule {payload.snapshot_prefill.schedule_performance_percent}%</span><span>·</span><span>{payload.snapshot_prefill.projects_at_risk + payload.snapshot_prefill.projects_critical} need attention</span></div></div> : null}</div><div className="rounded-[24px] p-5 text-white" style={{background:"linear-gradient(145deg,var(--brand),var(--brand-strong))"}}><p className="text-xs font-bold uppercase tracking-[.16em] text-white/70">Portfolio attention</p><p className="mt-2 text-5xl font-semibold">{payload.summary.projects_with_attention}</p><p className="mt-2 text-sm text-white/70">of {payload.summary.active_projects} active project(s)</p></div></div>
      <div className="grid border-t border-[var(--border)] sm:grid-cols-2 lg:grid-cols-4"><div className="p-5"><p className="text-xs text-[var(--muted)]">Active projects</p><p className="mt-2 text-3xl font-semibold">{payload.summary.active_projects}</p></div><div className="border-t border-[var(--border)] p-5 sm:border-l sm:border-t-0"><p className="text-xs text-[var(--muted)]">Schedule attention</p><p className="mt-2 text-3xl font-semibold">{payload.summary.schedule_attention}</p></div><div className="border-t border-[var(--border)] p-5 lg:border-l lg:border-t-0"><p className="text-xs text-[var(--muted)]">Approved budget</p><p className="mt-2 text-2xl font-semibold">{money(payload.summary.currency,payload.summary.approved_budget)}</p></div><div className="border-t border-[var(--border)] p-5 sm:border-l lg:border-t-0"><p className="text-xs text-[var(--muted)]">Client outstanding</p><p className="mt-2 text-2xl font-semibold">{payload.finance?money(payload.finance.currency,payload.finance.client_outstanding):"Restricted"}</p></div></div>
    </header>

    {payload.finance?<section className="grid gap-4 md:grid-cols-3"><article className="rounded-[24px] border border-[var(--border)] bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-[var(--muted)]">Client invoiced</p><p className="mt-2 text-2xl font-semibold">{money(payload.finance.currency,payload.finance.client_invoiced)}</p></article><article className="rounded-[24px] border border-[var(--border)] bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-[var(--muted)]">Outstanding</p><p className="mt-2 text-2xl font-semibold">{money(payload.finance.currency,payload.finance.client_outstanding)}</p></article><article className="rounded-[24px] border border-[var(--border)] bg-white p-5 shadow-sm"><p className="text-xs font-semibold text-[var(--muted)]">Vendor invoiced</p><p className="mt-2 text-2xl font-semibold">{money(payload.finance.currency,payload.finance.vendor_invoiced)}</p></article></section>:null}

    {payload.history_available?<section className="rounded-[28px] border border-[var(--border)] bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[var(--brand)]">Published portfolio history</p><h2 className="mt-1 text-2xl font-semibold">Trend, not just today&apos;s snapshot</h2><p className="mt-1 text-sm text-[var(--muted)]">Only governed published PortfolioSnapshot records are charted.</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold">{payload.history.length} snapshot(s)</span></div>{payload.history.length?<div className="mt-6 overflow-x-auto"><div className="flex min-w-[760px] items-end gap-4">{payload.history.map((item)=>{const schedule=Math.max(0,Math.min(100,Number(item.schedule_performance_percent)));const cost=Math.max(0,Math.min(100,Number(item.cost_performance_percent)));return <article className="min-w-[150px] flex-1" key={item.public_id}><div className="flex h-44 items-end gap-2 rounded-2xl bg-slate-50 p-4"><div className="flex h-full flex-1 items-end"><div className="w-full rounded-t-lg bg-[var(--brand)]" style={{height:`${schedule}%`}} title={`Schedule ${schedule}%`}/></div><div className="flex h-full flex-1 items-end"><div className="w-full rounded-t-lg bg-slate-400" style={{height:`${cost}%`}} title={`Cost ${cost}%`}/></div></div><p className="mt-2 text-xs font-semibold">{new Date(item.as_of_date).toLocaleDateString()}</p><p className="mt-1 text-[10px] text-[var(--muted)]">Schedule {schedule}% · Cost {cost}%</p><p className="mt-1 text-[10px] text-[var(--muted)]">{item.projects_at_risk + item.projects_critical} project(s) at risk</p></article>})}</div></div>:<p className="mt-5 rounded-2xl bg-slate-50 p-5 text-sm text-[var(--muted)]">No published portfolio history exists yet. Publish governed snapshots in Portfolio / KPI operations to build the trend.</p>}</section>:null}

    <section className="grid gap-4 xl:grid-cols-2">{payload.projects.map((project)=><Link className="rounded-[28px] border border-[var(--border)] bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-[var(--brand)] sm:p-6" href={project.href} key={project.public_id}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--muted)]">{project.code} · {project.stage_name}</p><h2 className="mt-1 text-xl font-semibold">{project.name}</h2><p className="mt-1 text-xs text-[var(--muted)]">{project.planned_end_date?`Planned finish ${project.planned_end_date}`:"No planned finish"}</p></div><span className={`rounded-full border px-3 py-1 text-[10px] font-bold ${healthStyle[project.health]}`}>{project.health.replaceAll("_"," ")}</span></div><div className="mt-5"><div className="flex justify-between text-xs"><span>Overall task progress</span><span className="font-semibold">{project.progress_percent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[var(--brand)]" style={{width:`${Math.min(project.progress_percent,100)}%`}}/></div></div><div className="mt-5 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Overdue",project.overdue_tasks],["Open NCR",project.open_ncrs??"—"],["Safety 30d",project.safety_incidents_30d??"—"],["Outstanding",project.client_outstanding!==null?money(project.currency,project.client_outstanding):"—"]].map(([label,value])=><div className="rounded-2xl bg-slate-50 p-3" key={String(label)}><p className="text-[10px] text-[var(--muted)]">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><div className="mt-4 flex items-center justify-between text-xs"><span className="text-[var(--muted)]">Budget {money(project.currency,project.approved_budget)}</span><span className="font-semibold text-[var(--brand)]">Open Project 360 →</span></div></Link>)}</section>
  </div></main>;
}
